call-center/src/objects/Adjustment__c.object
<CustomObject>
    <description>Metadata about Adjustments</description>
    <fields>
        <fullName>Aggregate_Id__c</fullName>
        <description>Composite key: External Guarantor Id, Post Date, Payor</description>
        <externalId>true</externalId>
        <label>Aggregate ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_Guarantor__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>External Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Adjustments (External Guarantor)</relationshipLabel>
        <relationshipName>AdjustmentsExtGT</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Adjustments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipName>Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>External_Guarantor_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (External Guarantor ID)</relationshipLabel>
        <relationshipName>Charge_Groups2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Guarantor_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono External Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Payor__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

call-center/src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Adjustment2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>Adjustment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>Date and Time stamp</description>
        <label>Post Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
    <fields>
        <fullName>Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>Payment_Adjustments__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>

call-center/src/classes/AdjustmentService.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

public with sharing class AdjustmentService extends AbstractService {
    @TestVisible
    private class AdjustmentRestClient extends SironoRestClient {

        /**
         * Provides the URL map to the HttpSirono class for looking up urls.
         */
        @TestVisible
        private Map<String, String> getUrls() {
            return RestClientConstants.ADJUSTMENT_URLS;
        }

        /**
         * Make the call to add an Adjustment
         *
         * @param PaymentPlanInformation ppInfo - An object that holds the information required to create a payment plan.
         * @return HttpResponse The response to the call.
         **/
        @TestVisible
        private HttpResponse addAdjustment(AdjustmentRequest info) {

            return postRequestor()
                .url(RestClientConstants.ADJUSTMENT_KEY, new String[] {})
                .body(buildAddAdjustmentBody(info))
                .call();
        }

        /**
         * Get the transactions for the given Adjustment
         *
         * @param String Adjustment SironoId
         * @return HttpResponse The response to the call.
         **/
        @TestVisible
        private HttpResponse getTransactions(String adjSironoId) {

            return getRequestor()
                .url(RestClientConstants.ADJUSTMENT_TXNS_KEY, new String[] { adjSironoId })
                .call();
        }

        /**
         * Build the JSON structure required to add an adjustment.
          *
          * @param - info  The AdjustmentRequest
          * @return - The Json payload.
         */
        @TestVisible
        private String buildAddAdjustmentBody(AdjustmentRequest info) {
            Map<String, Object> rawData = new Map<String, Object> {
                RestClientConstants.AMOUNT => convertToCents(info.adjustmentAmount),
                RestClientConstants.CHARGE_GROUP => asChargeGroupURL(info.chargeGroupSironoId.toPlainString()),
                RestClientConstants.CODE => info.adjustmentCode,
                RestClientConstants.CSRF_JSON_KEY => getCsrf()
            };

            String body = JSON.serializePretty(rawData);
            System.debug('addAdjustmentBody: ' + body);
            return body;
        }
    }

    //TODO add the aggregateId when it is added to the response
    @TestVisible
    private class AdjJsonWrapper {
        public String url;
        public Integer amount;
        public String code;
        public String description;
        public String post_date;
        public String chargegroup;
    }

    /**
     * JSON Parsing Class for the response which comes from Adjustment/Discount Request.
     */
    @TestVisible
    private class AdjustmentResponseParser extends AbstractSironoJSONParser {

        private String jsonString;

        public Adjustment__c newAdjustment;
        public String adjSironoId;
        public String cgSironoId;

        @TestVisible
        public AdjustmentResponseParser(String jsonString) {
            this.jsonString = jsonString;
        }

        public void parse() {
            AdjJsonWrapper wrapper = (AdjJsonWrapper) System.JSON.deserialize(jsonString, AdjJsonWrapper.class);
            //TODO we need to add the aggregateId to the JSON response body
            newAdjustment = new Adjustment__c(Description__c = wrapper.description,
                Amount__c = convertToDollars(wrapper.amount),
                Post_Date__c = parseDate(wrapper.post_date));
            System.debug('adj parsed');
            adjSironoId = parseSironoId(wrapper.url, RestClientConstants.ADJUSTMENT_URL_RESOURCE_TYPE);
            System.debug('adj id: ' + adjSironoId);

            cgSironoId = parseSironoId(wrapper.chargegroup, RestClientConstants.CHARGE_GROUP_URL_RESOURCE_TYPE);
            System.debug('cg id: ' + cgSironoId);
        }
    }

    public class AdjustmentRequest {
        public AdjustmentRequest(Id gtId, Decimal cgSironoId, String adjCode, Decimal adjAmount) {
            this.guarantorId = gtId;
            this.chargeGroupSironoId = cgSironoId;
            this.adjustmentCode = adjCode;
            this.adjustmentAmount = adjAmount;
        }

        Id guarantorId;
        Decimal chargeGroupSironoId;
        String adjustmentCode;
        Decimal adjustmentAmount;

        public Boolean isValid() {
            return chargeGroupSironoId != null && !String.isBlank(adjustmentCode) && adjustmentAmount > 0 && guarantorId != null;
        }
    }

    //TODO not ready for primetime
//    public static void createDiscount(DiscountRequest request) {
//        if (!request.isValid()) {
//            throw new ServiceException('DiscountRequest is invalid');
//        }
//
//    }

    public static void createAdjustment(AdjustmentRequest request) {
        if (!request.isValid()) {
            throw new ServiceException('AdjustmentRequest is invalid');
        }

        //Create the adjustment in Sirono
        AdjustmentResponseParser parser = createSironoAdjustment(request);

        Adjustment__c adj = parser.newAdjustment;
        adj.Guarantor__c = request.guarantorId;

        Payment_Plan__c originalPaymentPlan = null;
        // Read the cg from the db to get the GTExternalId & PP Id
        List<Charge_Group__c> dbChargeGroups = ChargeGroupDao.getBySironoIds(new List<Decimal> { Decimal.valueOf(parser.cgSironoId) });
        if (dbChargeGroups[0].Payment_Plan__c != null) {
            originalPaymentPlan = PaymentPlanService.retrievePlan(dbChargeGroups[0].Payment_Plan__r.Sirono_ID__c);

            dbChargeGroups = ChargeGroupDao.getByPaymentPlanIds(new Set<Id> { dbChargeGroups[0].Payment_Plan__c });
        }

        List<Charge_Group__c> cgsToUpdate = new List<Charge_Group__c>();

        // Retrieve the affected chargegroup from sirono so that we get the proper status/substatus for them
        for (Charge_Group__c cg : dbChargeGroups) {
            ChargeGroupJSONParser.ChargeGroupJSON cgp = ChargeGroupService.retrieveBySironoId(parser.cgSironoId);
            Charge_Group__c cgToUpdate = new ChargeGroupJSONParser().asChargeGroup(cgp);
            cgToUpdate.Id = cg.Id;
            cgsToUpdate.add(cgToUpdate);
        }

        //retrieve the adjustment transactions from sirono
        List<Transaction__c> transactions = retrieveAdjustmentTransactions(parser.adjSironoId);

        //TODO hack the aggregateId
        List<String> aggregateIdStrings = new List<String>();
        if (dbChargeGroups[0].External_Guarantor_ID__r != null) {
            aggregateIdStrings.add(dbChargeGroups[0].External_Guarantor_ID__r.External_Guarantor_Id__c.toPlainString());
        } else {
            aggregateIdStrings.add('');
        }
        aggregateIdStrings.add(Datetime.newInstance(adj.Post_Date__c, Time.newInstance(0, 0, 0, 0)).format('YYYYMMdd'));
        if (adj.Payor__c != null) {
            //TODO get the payor's SironoId
        } else {
            aggregateIdStrings.add('');
        }

        String aggregateId = String.join(aggregateIdStrings, ':');
        System.debug('aggregateId: ' + aggregateId);
        adj.Aggregate_Id__c = aggregateId;

        //TODO hack until the ExternalGT is returned via the api
        adj.External_Guarantor__c = dbChargeGroups[0].External_Guarantor_ID__c;
        AdjustmentDao.save(new List<Adjustment__c> { adj });
        System.debug('Saved adj, Id: ' + adj.Id);

        if (originalPaymentPlan != null) {
            System.debug('Updated pp, Id: ' + originalPaymentPlan.Id);
            PaymentPlanDao.updateAll(new List<Payment_Plan__c> { originalPaymentPlan });
        }
        System.debug('Updating ' + cgsToUpdate.size() + ' chargegroups');
        ChargeGroupDao.updateChargeGroups(cgsToUpdate);

        for (Transaction__c txn : transactions) {
            txn.Adjustment2__c = adj.Id;
        }
        System.debug('Saving ' + transactions.size() + ' transactions');
        TransactionDao.save(transactions);
    }

    private static AdjustmentResponseParser createSironoAdjustment(AdjustmentRequest request) {
        //Create the adjustment
        AdjustmentRestClient client = new AdjustmentRestClient();
        HttpResponse response = client.addAdjustment(request);
        System.debug('addAdjustment response: ' + response.getBody());
        AdjustmentResponseParser parser = new AdjustmentResponseParser(response.getBody());
        parser.parse();
        return parser;
    }

    private static List<Transaction__c> retrieveAdjustmentTransactions(String adjSironoId) {
        //retrieve the adjustment transactions from sirono
        AdjustmentRestClient client = new AdjustmentRestClient();
        HttpResponse response = client.getTransactions(adjSironoId);

        TransactionJSONParser txnParser = new TransactionJSONParser(response.getBody());
        return txnParser.parse();
    }
}