call-center/src/objects/Adjustment__c.object
<CustomObject>
    <description>Metadata about Adjustments</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if active account</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge_Group_External_Id__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used for integration</description>
        <label>Charge Group External ID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>External_Guarantor_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (External Guarantor ID)</relationshipLabel>
        <relationshipName>Charge_Groups2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Guarantor_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono External Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>


    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Patient of the account or case</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>

call-center/src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>Invoice Id External</description>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>Id number</description>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Participant is past due</description>
        <label>Delinquent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Service2__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Adjustment2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>Adjustment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Tranaction_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>Date and Time stamp</description>
        <label>Post Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service2__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Txn_Method__c</fullName>
        <description>Determine the transaction method based on the linked objects</description>
        <formula>IF(Service2__c != NULL, &apos;Service&apos;, IF(Adjustment2__c != NULL, &apos;Adjustment&apos;, IF(Payment__c != NULL, &apos;Payment&apos;, &apos;Unknown&apos;)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Method</label>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
    <fields>
        <fullName>Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>Payment_Adjustments__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>

call-center/src/classes/AdjustmentServiceTest.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

@IsTest
public with sharing class AdjustmentServiceTest {

    public static String CREATE_ADJUSTMENT_JSON_RESPONSE = '{' +
            '   "url": "https://test.sirono.com/paystaff/api/adjustments/3151479/", ' +
            '   "chargegroup":"https://test.sirono.com/paystaff/api/chargegroups/'+RestClientConstants.CHARGE_GROUP_ID+'/",' +
            '   "amount":125,' +
            '   "code":"ADM",' +
            '   "description":"BC/BS adjustment",' +
            '   "display_kind":"",' +
            '   "post_date":"2016-10-13"' +
            '}';

    @TestSetup
    public static void setupData() {
        // Create Guarantor Contact record.
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        guarantorContact.Profile_Pointer_Id__c = Decimal.valueOf(MockHttpResponseGenerator.guarantorSironoId);
        insert guarantorContact;

        Contact externalGT = TestUtility.generateExternalGuarantor();
        insert externalGT;

        // Create Patient Contact record.
        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        // Create Payment Plan record.
        Payment_Plan__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
        paymentPlan.Sirono_Id__c = Decimal.valueOf(MockHttpResponseGenerator.planSironoId);
        paymentPlan.Active__c = true;
        paymentPlan.Delinquent__c = true;
        insert paymentPlan;

        // Create Invoice record.
        Invoice__c invoice = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
        insert invoice;

        // Create Charge Group record.
        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 121114);
        chargeGroup.Invoice__c = invoice.Id;
        chargeGroup.Sirono_Id__c = Decimal.valueOf(RestClientConstants.CHARGE_GROUP_ID);
        chargeGroup.Payment_Plan__c = paymentPlan.Id;
        chargeGroup.Charge_Group_External_Id__c = true;
        chargeGroup.External_Guarantor_Id__c = externalGT.Id;
        insert chargeGroup;

        Charge_Group__c[] someCGs = ChargeGroupDao.getBySironoIds(new Decimal[]{chargeGroup.Sirono_Id__c});

        System.debug('>>>> Found '+someCGs.size()+' chargegroups');
        for (Charge_Group__c cg : someCGs) {
            System.debug('exgt: '+cg.External_Guarantor_ID__r.External_Guarantor_Id__c);
        }

        Service2__c svc = TestUtility.generateService(guarantorContact, 675.00);
        insert svc;

        Transaction__c txn = TestUtility.generateServiceTxn(chargeGroup, 675.00, svc);
        insert txn;
    }

    @IsTest
    public static void testAdjustmentParser() {
        AdjustmentService.AdjustmentResponseParser parser = new AdjustmentService.AdjustmentResponseParser(CREATE_ADJUSTMENT_JSON_RESPONSE);
        parser.parse();

        System.assertEquals('3151479', parser.adjSironoId);
        System.assertEquals(RestClientConstants.CHARGE_GROUP_ID, parser.cgSironoId);
        System.assertEquals('BC/BS adjustment', parser.newAdjustment.Description__c);
        System.assertEquals(1.25, parser.newAdjustment.Amount__c);
        System.assertEquals(Date.newInstance(2016, 10, 13), parser.newAdjustment.Post_Date__c);
    }

    @IsTest
    public static void testCreateAdjustment() {

        Contact gt = [SELECT Id, Profile_Pointer_Id__c FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Decimal cgSironoId = Decimal.valueOf(RestClientConstants.CHARGE_GROUP_ID);
        String adjCode = 'ADM';
        Decimal adjAmount = 1.25;

        AdjustmentService.AdjustmentRequest req = new AdjustmentService.AdjustmentRequest(gt.Id, cgSironoId, adjCode, adjAmount);

        Test.setMock(HttpCalloutMock.class, ParameterizedMockHttpResponseGenerator.ADJUSTMENT_MOCK);

        Test.startTest();
        AdjustmentService.createAdjustment(req);
        System.debug('No exception thrown creating an adjustment!');
        Test.stopTest();

        Adjustment__c[] adjs = [SELECT Id FROM Adjustment__c];
        System.assertEquals(1, adjs.size(), 'Expected 1 Adjustment__c');

        Transaction__c[] txns = [
                SELECT
                        Adjustment2__c,
                        Amount__c,
                        Id,
                        Name,
                        Payment__c,
                        Post_Date__c,
                        Service2__c,
                        Sirono_Id__c,
                        Transaction_Date__c,
                        Txn_Method__c
                FROM Transaction__c WHERE Adjustment2__c = :adjs[0].Id];

        System.assertEquals(1, txns.size(), 'Expected 1 adjustment transaction');
        System.assertEquals(-1.25, txns[0].Amount__c, 'Expected -1.25 adjustment transaction');
        System.assert(txns[0].Payment__c == null, 'Expected Payment__c to be null');
        System.assert(txns[0].Service2__c == null, 'Expected Service2__c to be null');
        System.assertEquals('10/13/2016', txns[0].Post_Date__c.format('MM/dd/yyyy'), 'Expected txn Post_Date__c to be 10/13/2016');
        System.assert(txns[0].Transaction_Date__c != null, 'Expected Tranaction_Date__c to be set');
    }
}