call-center/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Guarantor_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Guarantor record.  Set via the manual cases flow to be the first chargegroup&apos;s guarantor.</description>
        <label>Guarantor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Guarantor)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Patient record.  Set via the manual cases flow to be the first chargegroup&apos;s patient.</description>
        <label>Patient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Patient Information)</relationshipLabel>
        <relationshipName>Cases_P</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <label>Payor</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Id__c</fullName>
        <label>Subscriber ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Name__c</fullName>
        <label>Subscriber Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <businessProcess>Manual Case Creation</businessProcess>
        <description>To distinctly capture General Case types</description>
        <label>General</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Charge_Group_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Charge Group Junction</label>
    <nameField>
        <displayFormat>CCG-{000000}</displayFormat>
        <label>Case Charge Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charge Group Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if active account</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <summarizedField>Transaction__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction__c.Charge_Group__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Patient)</relationshipLabel>
        <relationshipName>Charge_Groups_Patient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group_Coverage_Junction__c.object
<CustomObject>
    <description>Junction object to create many-to-many relationship between Charge Groups and Coverages</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Charge Group Coverage Junctions</relationshipLabel>
        <relationshipName>Charge_Group_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Coverage__c</fullName>
        <label>Coverage</label>
        <referenceTo>Coverage__c</referenceTo>
        <relationshipLabel>Charge Group Coverage Junctions</relationshipLabel>
        <relationshipName>Charge_Group_Coverages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group Coverage Junction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Group Coverage Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Patient of the account or case</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Coverage__c.object
<CustomObject>
    <description>Insurance plan coverage details</description>
    <fields>
        <fullName>Date_Effective__c</fullName>
        <description>Effective date</description>
        <label>Date Effective</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipLabel>Coverages</relationshipLabel>
        <relationshipName>Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <label>Plan Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subscriber_Id__c</fullName>
        <label>Subscriber ID</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Name__c</fullName>
        <label>Subscriber Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Coverage</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payor__c.object
<CustomObject>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Payor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

call-center/src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/classes/CreateCaseManual.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Create a Manual case based on the conditions
 */
public with sharing class CreateCaseManual {
    public String guarantorRecordId { get; set; }
    public Boolean chargeGroupsSelected { get; set; }
    public String guarantorId { get; set; }
    public String guarantorName { get; set; }
    public String[] chargeGroupIds { get; set; }
    public List<ChargeGroupWrapper> chargeGroupList { get; set; }
    public Case manualCase { get; set; }
    public String caseType { get; set; }
    public Boolean caseTypeSelected { get; set; }
    public Contact gc { get; set; }
    public String caseNotes { get; set; }
    public Contact guarantorContact { get; set; }
    public Contact patientContact { get; set; }
    public Charge_Group__c chargeGroup = new Charge_Group__c();
    public String coverageJson { get; set; }
    public String transactionJson { get; set; }

    //11-23-2016: Viraj Rana - Tracker # 132104143: Pre-populate manual case fields where necessary.
    //This set is also used whenever we got Coverage record based on Charge Group's "Date Of Service Start" field.
    Set<Id> setChargeGroupId = new Set<Id>();

    /*
     * Constructor to get the guarantor and charge group details.
    */
    public CreateCaseManual(ApexPages.StandardController sc) {
        chargeGroupsSelected = false;
        chargeGroupList = new List<ChargeGroupWrapper>();
        guarantorName = '';
        manualCase = new Case();
        caseTypeSelected = false;
        patientContact = new Contact();
        guarantorContact = new Contact();
        guarantorRecordId = sc.getId();

        if (ApexPages.currentPage().getParameters().containsKey('guarantorId')) {
            guarantorRecordId = ApexPages.currentPage().getParameters().get('guarantorId');
        }
        if (guarantorRecordId != null) {
            Contact objContact = ContactService.getContactDetails(guarantorRecordId);
            if (objContact != null) {
                if (objContact.RecordType.DeveloperName == 'Guarantor') {
                    gc = GuarantorService.getGuarantorFilterCGByAcctSubStatus(guarantorRecordId, Constants.CGConstraintsForCase);
                    guarantorId = PayStaffWSUtill.fetchGuarantorId(gc);
                } else if (objContact.RecordType.DeveloperName == 'Patient') {
                    gc = PatientService.getPatientFilterCGByAcctSubStatus(guarantorRecordId, Constants.CGConstraintsForCase);
                    guarantorId = PayStaffWSUtill.fetchPatientId(gc);
                }
            }

            guarantorName = GuarantorService.buildGuarantorDetailString(gc);

            manualCase.ContactId = gc.Id;

            for (ChargeGroupWrapper cgw : PayStaffWSUtill.fetchChargeGroupList(gc, objContact.RecordType.DeveloperName)) {
                if (cgw.cg.Active__c && cgw.cg.Balance__c != 0) {
                    chargeGroupList.add(cgw);
                }
            }
            chargeGroupIds = new String[] {};
        }
    }

    /*
    * Cancel the case creation and back to the guarantor record.
    */
    public PageReference cancel() {
        return VisualforceControllerUtil.getRecordPageReference(guarantorRecordId);
    }

    /*
    * check charge group is selected or not and show the guarantor details.
    */
    public PageReference doNext() {
        chargeGroupsSelected = false;
        chargeGroupIds = ChargeGroupWrapper.getSelectedChargeGroupIds(chargeGroupList);

        if (!chargeGroupIds.isEmpty()) {
            chargeGroupsSelected = true;
        } else {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.Charge_Groups_Require));
        }
        return null;
    }

    //get the case record type
    private String getCaseRecordTypeId(String rtName) {
        Schema.DescribeSObjectResult optySobj = Schema.SObjectType.Case;
        Map<String, Schema.RecordTypeInfo> rtMapByName = optySobj.getRecordTypeInfosByName();
        return rtMapByName.get(rtName).getRecordTypeId();
    }

    //get the Patient and Guarantor information
    public void gotoCaseCreation() {
        if (String.isNotBlank(caseType)) {
            caseTypeSelected = true;
            manualCase.RecordTypeId = getCaseRecordTypeId(caseType);

            //Check Charge Group is Selected
            if (caseType != 'General') {
                doNext();
            } else {
                chargeGroupsSelected = true;
            }

            for (ChargeGroupWrapper cg : chargeGroupList) {
                if (cg.isSelected) {
                    setChargeGroupId.add(cg.cg.Id);
                }
            }

            chargeGroup = ChargeGroupService.getCGOrderByCreatedDate(setChargeGroupId);

            if (gc.RecordType.DeveloperName == 'Patient') {
                manualCase.Patient__c = gc.Id;
                if (chargeGroup != null) {
                    manualCase.Guarantor_Information__c = chargeGroup.Guarantor__c;
                }
                guarantorContact = ContactService.getContactDetails(manualCase.Guarantor_Information__c);
                patientContact = gc;
            } else if (gc.RecordType.DeveloperName == 'Guarantor') {
                manualCase.Guarantor_Information__c = gc.Id;
                if (chargeGroup != null) {
                    manualCase.Patient__c = chargeGroup.Patient__c;
                }
                patientContact = ContactService.getContactDetails(manualCase.Patient__c);
                guarantorContact = gc;
            }

        } else {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, Label.Case_Type_Require);
            ApexPages.addMessage(myMsg);
        }
    }

    //Create a new case
    public PageReference submit() {
        try {

            //Creating the DMLOptions for "Assign using active assignment rules" checkbox
            if (guarantorContact != null) {
                manualCase.ContactId = guarantorContact.Id;
            }
            manualCase.Subject = manualCase.Reason;
            // TODO: Restore this when we know what the requirements are for assignment rules
//            AssignmentRule assignmentRule = new AssignmentRule();
//            if (AssignmentRuleSecurityContext.SELECT_CONTEXT.actionAllowed()) {
//                assignmentRule = [
//                    SELECT Id
//                    FROM AssignmentRule
//                    WHERE SobjectType = 'Case' AND Active = TRUE
//                    LIMIT 1
//                ];
//            }
//
//            Database.DMLOptions dmlOpts = new Database.DMLOptions();
//            dmlOpts.AssignmentRuleHeader.assignmentRuleId = assignmentRule.Id;
//            manualCase.setOptions(dmlOpts);

            if (CaseSecurityContext.CREATE_WITH_GT_CONTEXT.actionAllowed()) {
                // TODO: This has to be an upsert because the case has already been created at this point (by the standard controller?)
                upsert manualCase;
            }

            //add selected Charge Groups to Case
            List<Case_Charge_Group_Junction__c> caseChargeGroupJunctions = new List<Case_Charge_Group_Junction__c>();
            for (ChargeGroupWrapper chargeGroupWrapper : chargeGroupList) {
                if (chargeGroupWrapper.isSelected) {
                    Case_Charge_Group_Junction__c caseChargeGroupJunction = new Case_Charge_Group_Junction__c();
                    caseChargeGroupJunction.Case__c = manualCase.Id;
                    caseChargeGroupJunction.Charge_Group__c = chargeGroupWrapper.cg.Id;
                    caseChargeGroupJunctions.add(caseChargeGroupJunction);
                }
            }
            if (CaseCGJunctionSecurityContext.CREATE_CONTEXT.actionAllowed()) {
                insert caseChargeGroupJunctions;
            }

            //create case comments
            if (String.isNotBlank(caseNotes)) {
                CaseComment caseComment = new CaseComment();
                caseComment.ParentId = manualCase.Id;
                caseComment.CommentBody = caseNotes;

                if (CaseCommentSecurityContext.CREATE_CONTEXT.actionAllowed()) {
                    insert caseComment;
                }
            }

            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Created Successfully!'));
            if (Test.isRunningTest()) {

                TestUtility.generateException();
            }
            return VisualforceControllerUtil.getRecordPageReference(guarantorRecordId);
        } catch (Exception e) {
            // Debug error response
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'ERROR: ' + e.getMessage()));
        }

        return null;
    }

    public void refresh() {
        if (ApexPages.currentPage().getParameters().containsKey('reason')) {
            manualCase.Reason = ApexPages.currentPage().getParameters().get('reason');
            
      /* 11-23-2016: Viraj Rana - Tracker # 132104143: Pre-populate manual case fields where necessary.
       * Populating coverage data using the selected Chargegroup with the oldest "Date Of Service Start" field.
       */
            Charge_Group__c cg = new Charge_Group__c();
            List<Charge_Group__c> lstChargeGroup = ChargeGroupService.getCGOrderByServiceDate(setChargeGroupId);
            if (lstChargeGroup.size() > 0) {
                cg = lstChargeGroup[0];
            }

            /* 10-19-2016: Viraj Rana - Tracker # 132104143: Pre-populate manual case fields where necessary.
             * Get Coverage detail based on Selected Charge Group.
             */
            if (CGCoverageJunctionSecurityContext.SELECT_CONTEXT.actionAllowed()) {
                List<Charge_Group_Coverage_Junction__c> coverageDetail = [
                    SELECT Coverage__c, Coverage__r.Payor__c, Coverage__r.Payor__r.Name, Coverage__r.Plan_Name__c,
                        Coverage__r.Date_Effective__c, Coverage__r.Subscriber_Name__c, Coverage__r.Subscriber_Id__c
                    FROM Charge_Group_Coverage_Junction__c
                    WHERE Charge_Group__c = :cg.Id
                    ORDER BY LastModifiedDate DESC
                    LIMIT 1
                ];
                if (coverageDetail.size() > 0) {
                    coverageJson = JSON.serialize(coverageDetail[0]);
                }
            }

            //Get Transaction detail based on Selected Charge Group.
            if (TransactionSecurityContext.CCM_SELECT_CONTEXT.actionAllowed()) {
                List<Transaction__c> transactionDetail = [
                    SELECT Sirono_Id__c, Amount__c
                    FROM Transaction__c
                    WHERE Charge_Group__c = :chargeGroup.Id
                    ORDER BY LastModifiedDate DESC
                    LIMIT 1
                ];

                if (transactionDetail.size() > 0) {
                    transactionJson = JSON.serialize(transactionDetail[0]);
                }
            }
        }
    }
    
    /*public PageReference redirect(){

      //Write your logic here and redirect
      PageReference retURL = new PageReference('/' + guarantorRecordId);
      retURL.setRedirect(true);
      return retURL;
     }*/
}