call-center/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Patient record.  Set via the manual cases flow to be the first chargegroup&apos;s patient.</description>
        <label>Patient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Patient Information)</relationshipLabel>
        <relationshipName>Cases_P</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Of_Service__c</fullName>
        <label>Date of Service</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Encounter_Substatus__c</fullName>
        <formula>IF(OR(ISPICKVAL(Status__c, &quot;In Process&quot;), ISPICKVAL(Status__c, &quot;Error&quot;)), &quot;Unavailable&quot;,
IF(ISPICKVAL(Status__c, &quot;Cancelled&quot;), &quot;Cancelled&quot;,
IF(AND(ISPICKVAL(Status__c, &quot;Ready&quot;), Billed_Charge_Group_Count__c &gt; 0), &quot;Serviced&quot;,
IF(AND(ISPICKVAL(Status__c, &quot;Ready&quot;), Balance__c &gt; 0, Billed_Charge_Group_Count__c == 0), &quot;Payment Due&quot;,
IF(AND(ISPICKVAL(Status__c, &quot;Ready&quot;), Balance__c &lt;= 0, Billed_Charge_Group_Count__c == 0), &quot;Paid&quot;, &quot;&quot;)
)
)
)
)</formula>
        <label>Encounter Substatus</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Liability__c</fullName>
        <label>Liability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Patient)</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/classes/EncounterTriggerHandler.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Handler class for EncounterTrigger
 */
public with sharing class EncounterTriggerHandler {

    /*
     * After Inserting an encounter, perform the following:
     *   Check whether or not the guarantor can be removed from a call list
     *   Create an Encounter Auto Case for the encounter
     *   Calculate the Estimate_Balance for any guarantor associated with the Encounter
     */
    public static void afterInsert(List<Encounter__c> newList) {
        checkCallListRemove(newList, null);
        CaseUtil.createEncounterAutoCase(newList);
        updateEstimateBalances(newList);
    }

    /*
     * After Updating an encounter, perform the following:
     *   Check whether or not the guarantor can be removed from a call list
     *   Close Encounter Auto Case and Remove the Campaign member from Campaign
     *   If the guarantor associated with the encounter changed, recalculate the Estimate_Balance for both
     */
    public static void afterUpdate(List<Encounter__c> newList, Map<Id, Encounter__c> oldMap) {
        checkCallListRemove(newList, oldMap);
        CaseUtil.callCloseEncounterAutoCase(newList, false);
        checkEstimateBalanceRecalc(newList, oldMap);
    }

    /*
     * After deleting an encounter, perform the following:
     *   For any guarantor formerly associated with the encounter, recalculate their Estimate_Balance
     */
    public static void afterDelete(List<Encounter__c> oldList) {
        updateEstimateBalances(oldList);
    }

    //METHOD THAT COLLECTS THE ID OF GUARANTOR 
    private static void checkCallListRemove(List<Encounter__c> newList, Map<Id, Encounter__c> oldMap) {
        Set<Id> contactIds = new Set<Id>();
        for (Encounter__c e : newList) {
            if (e.Liability__c > 100 && e.Date_of_Service__c == System.today()
                && e.Cancelled__c && e.Patient__c != null &&
                (oldMap == null || e.Liability__c != oldMap.get(e.Id).Liability__c
                    || e.Date_of_Service__c != oldMap.get(e.Id).Date_of_Service__c
                    || e.Cancelled__c != oldMap.get(e.Id).Cancelled__c
                    || e.Guarantor__c != oldMap.get(e.Id).Guarantor__c)) {
                contactIds.add(e.Guarantor__c);
            }
        }

        if (contactIds.size() > 0) {
            CallListUtilities.preServiceCallListRemoval(contactIds);
        }
    }

    /**
     * If the Guarantor associated with a given Encounter has changed, recalculate the balances
     * for the old and new Guarantors
     */
    private static void checkEstimateBalanceRecalc(List<Encounter__c> encounters, Map<Id, Encounter__c> oldMap) {
        Set<Id> contactIds = new Set<Id>();
        for (Encounter__c e : encounters) {
            if (e.Guarantor__c != null) {
                if (e.Guarantor__c != oldMap.get(e.Id).Guarantor__c) {
                    contactIds.add(e.Guarantor__c);
                    if (oldMap.get(e.Id).Guarantor__c != null) {
                        contactIds.add(oldMap.get(e.Id).Guarantor__c);
                    }
                } else {
                    if (e.Encounter_Substatus__c != oldMap.get(e.Id).Encounter_Substatus__c) {
                        contactIds.add(e.Guarantor__c);
                    }
                }
            } else {
                if (oldMap.get(e.Id).Guarantor__c != null) {
                    contactIds.add(oldMap.get(e.Id).Guarantor__c);
                }
            }
        }

        if (contactIds.size() > 0) {
            EncounterUtil.updateGTEstimateBalances(contactIds);
        }
    }

    /**
     * If a given Encounter is associated with a Guarantor, calculate the Estimate_Balance
     * for the Guarantors
     */
    private static void updateEstimateBalances(List<Encounter__c> encounters) {
        Set<Id> ids = new Set<Id>();
        for (Encounter__c encounter : encounters) {
            if (encounter.Guarantor__c != null) {
                ids.add(encounter.Guarantor__c);
            }
        }

        EncounterUtil.updateGTEstimateBalances(ids);
    }
}