call-center/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Guarantor_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Guarantor record.  Set via the manual cases flow to be the first chargegroup&apos;s guarantor.</description>
        <label>Guarantor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Guarantor)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>HMO</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>PPO</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Offset_Date__c</fullName>
        <label>Invoice Offset Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Participant is past due</description>
        <label>Delinquent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Execute_On_Day__c</fullName>
        <label>Execute on Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Error in plan</description>
        <label>Has Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NextPaymentDate__c</fullName>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Plan Number type small int</description>
        <label>Plan Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Balance__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Skip_Payment_Until__c</fullName>
        <description>Defines making payment until date</description>
        <label>Skip Payment Until</label>
        <type>Date</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/classes/PaymentPlanTriggerTest.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * This class tests the logic of PaymentPlanTriggerHandler class.
 **/
@IsTest
private class PaymentPlanTriggerTest {

    /**
     * This method tests the logic of Next Payment Plan date is populated or not.
     **/
    static testMethod void checkNextPaymentDatePopulated() {
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        guarantorContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guarantor').getRecordTypeId();
        insert guarantorContact;

        Test.startTest();
        Payment_Plan__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
        insert paymentPlan;
        paymentPlan.Active__c = true;
        update paymentPlan;
        paymentPlan.Plan_Type__c = Constants.AUTOMATIC;
        update paymentPlan;

        paymentPlan.Skip_Payment_Until__c = Date.newInstance(2016, 1, 5);
        update paymentPlan;

        guarantorContact.Invoice_Offset_Date__c = 30;
        update guarantorContact;
        update paymentPlan;

        paymentPlan.Plan_Type__c = null;
        update paymentPlan;

        paymentPlan.Plan_Type__c = Constants.AUTOMATIC;
        paymentPlan.Execute_On_Day__c = 0;
        update paymentPlan;

        paymentPlan.Execute_On_Day__c = 31;
        update paymentPlan;
        Test.stopTest();

        //TODO: verfiy value
        // We can't verify the value for NextPaymentDate__c because of its dynamic generated based on date.
        // Check system assert, Check NextPaymentDate__c should not be populated.
        List<Payment_Plan__c> paymentPlans = [
            SELECT Id, NextPaymentDate__c
            FROM Payment_Plan__c
            WHERE Guarantor__c = :guarantorContact.Id
        ];
        System.assertNotEquals(paymentPlans[0].NextPaymentDate__c, null, 'NextPaymentDate__c should be null for Payment Plan');
    }

    /**
     * This method checks number of case records created count for guarantor contact.
     **/
    @IsTest
    static void checkCaseCountForRelevantGuarantor() {
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        guarantorContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guarantor').getRecordTypeId();
        insert guarantorContact;

        Test.startTest();
        Payment_Plan__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
        paymentPlan.Active__c = false;
        paymentPlan.Plan_Type__c = Constants.AUTOMATIC;
        paymentPlan.Remaining_Balance__c = 100;
        paymentPlan.Has_Error__c = false;
        paymentPlan.Delinquent__c = true;
        insert paymentPlan;

        paymentPlan.Active__c = true;
        paymentPlan.Remaining_Balance__c = 101;
        paymentPlan.Plan_Type__c = 'Manual';
        update paymentPlan;
        Test.stopTest();

        // Check system assert, Check & verify number of Case record exists for guarantor.
        List<Case> cases = [
            SELECT Id, Reason, Guarantor_Information__c, Status, Type
            FROM Case
            WHERE Guarantor_Information__c = :guarantorContact.Id
        ];
        System.assertEquals(cases.size(), 1, 'Number of Case records created is not equals to 1');
        System.assertEquals(cases[0].Type, Constants.CASE_TYPE_PAST_DUE_PAYMENT_PLANS, 'Case record not created with ' + Constants.CASE_TYPE_PAST_DUE_PAYMENT_PLANS + ' Type');
    }

    /**
     * This method checks Next Payment Date is getting updated after Update Payment Plan.
     **/
    @IsTest
    static void checkNextPaymentDateUpdated() {
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        guarantorContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guarantor').getRecordTypeId();
        insert guarantorContact;

        Test.startTest();
        Payment_Plan__c paymentPlan1 = TestUtility.generatePaymentPlan(guarantorContact.Id);
        paymentPlan1.Active__c = true;
        paymentPlan1.Plan_Type__c = Constants.AUTOMATIC;
        paymentPlan1.Remaining_Balance__c = 100;
        paymentPlan1.Has_Error__c = false;
        paymentPlan1.Delinquent__c = true;
        insert paymentPlan1;

        paymentPlan1.Active__c = false;
        paymentPlan1.Delinquent__c = false;
        update paymentPlan1;
        Test.stopTest();

        // Check system assert, Check NextPaymentDate__c should be populated.
        List<Payment_Plan__c> paymentPlans = [
            SELECT Id, NextPaymentDate__c
            FROM Payment_Plan__c
            WHERE Guarantor__c = :guarantorContact.Id
        ];
        System.assertNotEquals(paymentPlans[0].NextPaymentDate__c, null, 'NextPaymentDate__c should not null for Payment Plan');
    }

    /**
     * This method checks Execute on day date field value is getting populated.
     **/
    @IsTest
    static void checkExecuteOnDayPopulated() {
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        guarantorContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guarantor').getRecordTypeId();
        insert guarantorContact;

        Date refDt = Date.newInstance(TestUtility.currentYear, TestUtility.currentMonth, TestUtility.currentDay);

        Test.startTest();
        Payment_Plan__c paymentPlan1 = TestUtility.generatePaymentPlan(guarantorContact.Id);
        paymentPlan1.Active__c = true;
        paymentPlan1.Plan_Type__c = Constants.AUTOMATIC;
        paymentPlan1.Remaining_Balance__c = 100;
        paymentPlan1.Has_Error__c = true;
        paymentPlan1.Skip_Payment_Until__c = refDt.addDays(10);
        insert paymentPlan1;
        Test.stopTest();

        // Check system assert, Execute_On_Day__c should be populated with '0' value.
        List<Payment_Plan__c> paymentPlans = [
            SELECT Id, Execute_On_Day__c
            FROM Payment_Plan__c
            WHERE Guarantor__c = :guarantorContact.Id
        ];
        System.assertEquals(paymentPlans[0].Execute_On_Day__c, 1, 'Execute_On_Day__c should be 1 for Payment Plan.');
    }

    /**
     * This method tests the logic of Next Payment Plan date is populated or not.
     **/
    @IsTest
    static void checkNextPaymentDatePopulatedForManualPlan() {
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        guarantorContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Guarantor').getRecordTypeId();
        insert guarantorContact;

        Test.startTest();
        Payment_Plan__c paymentPlan1 = TestUtility.generatePaymentPlan(guarantorContact.Id);
        paymentPlan1.Active__c = true;
        paymentPlan1.Plan_Type__c = Constants.MANUAL;
        paymentPlan1.Remaining_Balance__c = 200;
        paymentPlan1.Has_Error__c = false;
        insert paymentPlan1;
        Test.stopTest();

        paymentPlan1 = [
            SELECT Id, NextPaymentDate__c
            FROM Payment_Plan__c
            WHERE Guarantor__c = :guarantorContact.Id
            LIMIT 1
        ];
        System.assertNotEquals(paymentPlan1, null, 'NextPaymentDate__c should be null for Payment Plan');
    }
}