call-center/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Patient record.  Set via the manual cases flow to be the first chargegroup&apos;s patient.</description>
        <label>Patient</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Patient Information)</relationshipLabel>
        <relationshipName>Cases_P</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Charge_Group_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Charge Group Junction</label>
    <nameField>
        <displayFormat>CCG-{000000}</displayFormat>
        <label>Case Charge Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charge Group Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>ChargeGroupStatus.preinvoiced</description>
        <label>Account Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Sub_Status__c</fullName>
        <label>Account Sub Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Of_Service_Start_Date__c</fullName>
        <description>Date Of Service Start Date</description>
        <label>Date Of Service Start</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Guarantor_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>External Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>External Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (External Guarantor ID)</relationshipLabel>
        <relationshipName>Charge_Groups2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Patient)</relationshipLabel>
        <relationshipName>Charge_Groups_Patient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Collection_Sent__c</fullName>
        <description>Date pre-collections notice was sent (if applicable).</description>
        <label>Pre Collection Sent</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>External_Guarantor_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono External Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Patient)</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Guarantor)</relationshipLabel>
        <relationshipName>Guarantor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>Invoice Id External</description>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Service2__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Related Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Services (Guarantors)</relationshipLabel>
        <relationshipName>Services2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/classes/ChargeGroupDaoTest.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Test the ChargeGroupDao methods
 */
@IsTest
public with sharing class ChargeGroupDaoTest {

    @TestSetup
    public static void setup() {
        Contact gt = TestUtility.generateGuarantorContact();
        insert gt;
        System.debug('gt.Id: ' + gt.Id);

        Contact exgt = TestUtility.generateExternalGuarantor();
        insert exgt;
        System.debug('exgt.Id: ' + exgt.Id);

        Contact pt = TestUtility.generatePatientContact();
        insert pt;
        System.debug('pt.Id: ' + pt.Id);

        List<Charge_Group__c> cgToAddList = TestUtility.generateChargeGroupList(gt.Id);
        Decimal i = 1;
        for (Charge_Group__c cg : cgToAddList) {
            cg.Sirono_Id__c = i++;
            cg.External_Guarantor_Id__c = exgt.Id;
            cg.Patient__c = pt.Id;
        }

        insert cgToAddList;



        // Check system assert.
        System.assertEquals(1, cgToAddList[0].Sirono_Id__c, 'Expected Chargegroup Sirono_Id__c equals to 1 but we got ' + cgToAddList[0].Sirono_Id__c);
    }

    @IsTest
    public static void getBySironoIdsAllFoundTest() {

        List<Decimal> cgSironoIds = new Decimal[] { 1, 3, 5, 10 };

        Test.startTest();
        Charge_Group__c[] cgs = ChargeGroupDao.getBySironoIds(cgSironoIds);
        Test.stopTest();

        Map<Decimal, Charge_Group__c> cgMap = new Map<Decimal, Charge_Group__c>();
        for (Charge_Group__c cg : cgs) {
            cgMap.put(cg.Sirono_Id__c, cg);
        }

        for (Decimal sironoId : cgSironoIds) {
            System.assert(cgMap.containsKey(sironoId), 'ChargeGroup with sironoId: ' + sironoId + ' not in result set');
        }
    }


    @IsTest
    public static void getBySironoIdsNotAllFoundTest() {

        List<Decimal> cgSironoIds = new Decimal[] { 1, 3, 5, 10, 99 };

        Test.startTest();
        Charge_Group__c[] cgs = ChargeGroupDao.getBySironoIds(cgSironoIds);
        Test.stopTest();

        Map<Decimal, Charge_Group__c> cgMap = new Map<Decimal, Charge_Group__c>();
        for (Charge_Group__c cg : cgs) {
            cgMap.put(cg.Sirono_Id__c, cg);
        }

        for (Decimal sironoId : cgSironoIds) {
            if (sironoId != 99) {
                System.assert(cgMap.containsKey(sironoId), 'ChargeGroup with sironoId: ' + sironoId + ' not in result set');
            } else {
                System.assert(!cgMap.containsKey(sironoId), 'ChargeGroup with sironoId: ' + sironoId + ' was in result set');
            }
        }
    }

    @IsTest
    public static void updateChargeGroupsTest() {

        Charge_Group__c[] cgs = [SELECT Id, Name, Sirono_Id__c FROM Charge_Group__c];

        for (Charge_Group__c cg : cgs) {
            cg.Name = 'test_name_' + cg.Sirono_Id__c;
        }

        Test.startTest();
        ChargeGroupDao.updateChargeGroups(cgs);
        Test.stopTest();

        cgs = [SELECT Id, Name, Sirono_Id__c FROM Charge_Group__c];

        for (Charge_Group__c cg : cgs) {
            String newName = 'test_name_' + cg.Sirono_Id__c;
            System.assertEquals(cg.Name, newName, 'Chargegroup name expected: ' + newName + ' but is: ' + cg.Name);
        }
    }

    /**
     * This method tests the logic of getBilledCGCountByEncounterIds method positive.
     **/
    @IsTest
    public static void getBilledCGCountPositiveTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Encounter__c encounter = TestUtility.generateEncounter(guarantorContact.Id, 500, System.today());
        insert encounter;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1214);
        chargeGroup.Encounter__c = encounter.Id;
        insert chargeGroup;

        Test.startTest();
        List<AggregateResult> results = ChargeGroupDao.getBilledCGCountByEncounterIds(new Set<Id> { encounter.Id });
        Test.stopTest();

        // Check system assert.
        System.assertEquals(1, results.size(), 'Expected AggregateResult size to be 1 but we got ' + results.size());
    }

    /**
     * This method tests the logic of getBilledCGCountByEncounterIds method negative.
     **/
    @IsTest
    public static void getBilledCGCountNegativeTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Encounter__c encounter = TestUtility.generateEncounter(guarantorContact.Id, 500, System.today());
        insert encounter;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1214);
        insert chargeGroup;

        Test.startTest();
        List<AggregateResult> results = ChargeGroupDao.getBilledCGCountByEncounterIds(new Set<Id> { encounter.Id });
        Test.stopTest();

        // Check system assert.
        System.assertEquals(0, results.size(), 'AggregateResult size should have 0 but we got ' + results.size());
    }

    /**
     * This method tests the logic of getCGOrderByCreatedDate method.
     **/
    @IsTest
    public static void getCGOrderByCreatedDateTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1244);
        insert chargeGroup;
        Test.setCreatedDate(chargeGroup.Id, System.now().addDays(-5));

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1234);
        insert chargeGroup1;
        Test.setCreatedDate(chargeGroup1.Id, System.now());

        Test.startTest();
        Charge_Group__c cg = ChargeGroupDao.getCGOrderByCreatedDate(new Set<Id> { chargeGroup.Id, chargeGroup1.Id });
        Test.stopTest();

        // Check system assert.
        System.assertEquals(cg.Id, chargeGroup1.Id, 'Expected newly created Charge Group but got different Charge Group.');
    }

    /**
     * This method tests the logic of getCGOrderByCreatedDate method.
     **/
    @IsTest
    public static void getCGOrderByServiceDateTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1242);
        chargeGroup.Date_Of_Service_Start_Date__c = System.today().addDays(-5);
        insert chargeGroup;

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1241);
        chargeGroup1.Date_Of_Service_Start_Date__c = System.today();
        insert chargeGroup1;

        Test.startTest();
        List<Charge_Group__c> chargeGroups = ChargeGroupDao.getCGOrderByServiceDate(new Set<Id> { chargeGroup.Id, chargeGroup1.Id });
        Test.stopTest();

        // Check system assert.
        System.assertEquals(chargeGroups[0].Id, chargeGroup.Id, 'Expected oldest Date_Of_Service_Start_Date__c related Charge Group but got different Charge Group.');
    }

    /**
     * This method tests the logic of getCGIdsFromCaseCGJun method Positive.
     **/
    @IsTest
    public static void getCGIdsFromCaseCGJunPositiveTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Decimal cgSironoId = 123456;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, cgSironoId);
        chargeGroup.Sirono_Id__c = cgSironoId;
        insert chargeGroup;

        Case objCase = TestUtility.generateCase(RecordTypeUtil.automatedCaseRt, Constants.CASE_TYPE_OVERDUE, guarantorContact.Id);
        insert objCase;

        Case_Charge_Group_Junction__c caseCGJun = new Case_Charge_Group_Junction__c(Case__c = objCase.Id, Charge_Group__c = chargeGroup.Id);
        insert caseCGJun;

        Test.startTest();
        List<String> chargeGroupIds = ChargeGroupDao.getCGIdsFromCaseCGJun(objCase.Id);
        Test.stopTest();

        // Check system assert.
        System.assertEquals(String.valueOf(cgSironoId), chargeGroupIds[0], 'Expected ' + cgSironoId + ' but we got ' + chargeGroupIds[0]);
        System.assertEquals(1, chargeGroupIds.size(), 'Expected chargeGroupIds size to be 1 but we got ' + chargeGroupIds.size());
    }

    /**
     * This method tests the logic of getCGIdsFromCaseCGJun method negative.
     **/
    @IsTest
    public static void getCGIdsFromCaseCGJunNegativeTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Decimal cgSironoId = 123456;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, cgSironoId);
        chargeGroup.Sirono_Id__c = cgSironoId;
        insert chargeGroup;

        Case objCase = TestUtility.generateCase(RecordTypeUtil.automatedCaseRt, Constants.CASE_TYPE_OVERDUE, guarantorContact.Id);
        insert objCase;

        Test.startTest();
        List<String> chargeGroupIds = ChargeGroupDao.getCGIdsFromCaseCGJun(objCase.Id);
        Test.stopTest();

        // Check system assert.
        System.assertEquals(0, chargeGroupIds.size(), 'chargeGroupIds size should have 0 but we got ' + chargeGroupIds.size());
    }

    /**
     * This method tests the logic of getCGBasedOnGuarantorAndPreCollDate method.
     **/
    @IsTest
    public static void getCGBasedOnGuarantorAndPreCollDateTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Date preCollDate = System.today().addDays(-5);

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1242);
        chargeGroup.Pre_Collection_Sent__c = preCollDate;
        insert chargeGroup;

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1241);
        chargeGroup1.Pre_Collection_Sent__c = System.today();
        insert chargeGroup1;

        Test.startTest();
        List<Charge_Group__c> chargeGroups = ChargeGroupDao.getCGBasedOnGuarantorAndPreCollDate(new List<Contact> { guarantorContact }, preCollDate);
        Test.stopTest();

        // Check system assert.
        System.assertEquals(preCollDate, chargeGroups[0].Pre_Collection_Sent__c, 'Expected Pre_Collection_Sent__c equals to ' + preCollDate + 'but got ' + chargeGroups[0].Pre_Collection_Sent__c);
        System.assertEquals(1, chargeGroups.size(), 'Expected chargeGroups size to be 1 but we got ' + chargeGroups.size());
    }

    /**
     * This method tests the logic of getCGForInvoiceController method with Order by.
     **/
    @IsTest
    public static void getCGForInvoiceControllerWithOrderByTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1244);
        insert chargeGroup;
        Test.setCreatedDate(chargeGroup.Id, System.now());

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1234);
        insert chargeGroup1;
        Test.setCreatedDate(chargeGroup1.Id, System.now().addDays(-5));

        Test.startTest();
        List<Charge_Group__c> chargeGroups = ChargeGroupDao.getCGForInvoiceController(new Set<Id> { chargeGroup.Id, chargeGroup1.Id }, true);
        Test.stopTest();

        // Check system assert.
        System.assertEquals(chargeGroups[0].Id, chargeGroup1.Id, 'Expected Charge Group that order by created date but got different Charge Group.');
    }

    /**
     * This method tests the logic of getCGForInvoiceController method without Order by.
     **/
    @IsTest
    public static void getCGForInvoiceControllerWithoutOrderByTest() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1244);
        insert chargeGroup;
        Test.setCreatedDate(chargeGroup.Id, System.now());

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1234);
        insert chargeGroup1;
        Test.setCreatedDate(chargeGroup1.Id, System.now().addDays(-5));

        Test.startTest();
        List<Charge_Group__c> chargeGroups = ChargeGroupDao.getCGForInvoiceController(new Set<Id> { chargeGroup.Id, chargeGroup1.Id }, false);
        Test.stopTest();

        // Check system assert.
        System.assertEquals(chargeGroups[0].Id, chargeGroup.Id, 'Expected newly created Charge Group but got different Charge Group.');
    }

    /**
     * This method tests the logic of getCGBasedOnGuarantorFilterByStatus method Positive.
     **/
    @IsTest
    public static void testGetByGuarantorAndSubStatus() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1234);
        chargeGroup.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_OVERDUE;
        insert chargeGroup;

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 12345);
        chargeGroup1.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_BAD_DEBT;
        insert chargeGroup1;

        Test.startTest();
        List<Charge_Group__c> chargeGroups = ChargeGroupDao.getByGuarantorAndSubStatus(new Set<Id> { guarantorContact.Id }, new Set<String> { Constants.ACCT_SUBSTATUS_OVERDUE });
        Test.stopTest();

        // Check system assert.
        System.assertEquals(guarantorContact.Id, chargeGroups[0].Guarantor__c, 'Expected CG Guarantor__c equals to ' + guarantorContact.Id + ' but we got ' + chargeGroups[0].Guarantor__c);
        System.assertEquals(1, chargeGroups.size(), 'Expected chargeGroups size to be 1 but we got ' + chargeGroups.size());
    }

    /**
     * This method tests the logic of getCGBasedOnGuarantorFilterByStatus method negative.
     **/
    @IsTest
    public static void testGetByGuarantorAndSubStatusNegative() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 12345);
        chargeGroup.Account_Status__c = Constants.ACCT_STATUS_PENDING;
        insert chargeGroup;

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1234);
        chargeGroup1.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_BAD_DEBT;
        insert chargeGroup1;

        Test.startTest();
        List<Charge_Group__c> chargeGroups = ChargeGroupDao.getByGuarantorAndSubStatus(new Set<Id> { guarantorContact.Id }, new Set<String> { Constants.ACCT_SUBSTATUS_OVERDUE });
        Test.stopTest();

        // Check system assert.
        System.assertEquals(0, chargeGroups.size(), 'chargeGroups size should have 0 but we got ' + chargeGroups.size());
    }

    /**
     * Check all Read rights for a Chatter User using runAs.
     **/
    @IsTest
    static void checkAccessRightsForRead() {
        List<ChargeGroupSecurityContext> allContexts = new List<ChargeGroupSecurityContext> {
            ChargeGroupSecurityContext.SELECT_CONTEXT,
            ChargeGroupSecurityContext.GD_SELECT_CONTEXT,
            ChargeGroupSecurityContext.IU_SELECT_CONTEXT
        };

        System.runAs(TestUtility.generateChatterOnlyUser()) {
            for (ChargeGroupSecurityContext context : allContexts) {
                try {
                    context.actionAllowed();
                    System.assert(false, 'Expected permission to be denied for ' + context);
                } catch (SecurityUtils.SecurityException ex) {
                    System.debug('SecurityException : ' + ex);
                } catch (Exception e) {
                    System.assert(false, 'Expected SecurityUtils.SecurityException to be thrown, but got ' + e);
                }
            }
        }
    }

    @IsTest
    public static void testGetCGForPaymentPlan() {

        Contact guarantorContact = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Payment_Plan__c payPlan = TestUtility.generatePaymentPlan(guarantorContact);
        insert payPlan;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 1234);
        chargeGroup.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_OVERDUE;
        chargeGroup.Payment_Plan__c = payPlan.Id;
        insert chargeGroup;

        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, null, 12345);
        chargeGroup1.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_BAD_DEBT;
        chargeGroup1.Payment_Plan__c = payPlan.Id;
        insert chargeGroup1;

        Test.startTest();
        List<Charge_Group__c> cgs = ChargeGroupDao.getCGForPaymentPlan(payPlan.Id);
        Test.stopTest();

        System.assertEquals(2, cgs.size());
    }

    @IsTest
    public static void testGetPayableByInvoiceId() {
        Contact gt = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Contact pt = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.patientRt];

        Invoice__c invoice = TestUtility.generateInvoice(gt.Id, pt.Id);
        insert invoice;

        Charge_Group__c[] cgs = [SELECT Id FROM Charge_Group__c];
        Service2__c[] svcs = new List<Service2__c>();
        for (Integer i = 0; i < cgs.size(); i++) {
            Charge_Group__c cg = cgs[i];
            cg.Invoice__c = invoice.Id;
            if (i == cgs.size()-1) {
                cg.Active__c = false;
            } else {
                cg.Active__c = true;
            }
            cg.Account_Status__c = Constants.ACCT_STATUS_BILLED;
            cg.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_DUE_BY;
            Service2__c svc = TestUtility.generateService(gt, 200.00);
            svcs.add(svc);
        }
        insert svcs;
        update cgs;

        Transaction__c[] txns = new List<Transaction__c>();
        for (Integer i = 0; i<svcs.size(); i++) {
            Transaction__c txn = TestUtility.generateServiceTxn(cgs[i], 200.00, svcs[i]);
            txns.add(txn);
        }
        insert txns;

        Test.startTest();
        Charge_Group__c[] byInvoice = ChargeGroupDao.getPayableByInvoiceId(new Set<String>(new List<String>{invoice.Id}));
        Test.stopTest();

        System.assertEquals(cgs.size()-1, byInvoice.size(), 'Expected a difference of 1 cg');
    }
}