call-center/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Guarantor_Id__c</fullName>
        <formula>Guarantor_Information__r.Guarantor_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Guarantor Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Charge_Group__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Charge Group</label>
    <nameField>
        <displayFormat>CCG-{000000}</displayFormat>
        <label>Case Charge Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Charge_Group_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Charge Group Junction</label>
    <nameField>
        <displayFormat>CCG-{000000}</displayFormat>
        <label>Case Charge Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charge Group Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>ChargeGroupStatus.preinvoiced</description>
        <label>Account Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Sub_Status__c</fullName>
        <label>Account Sub Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>

    <fields>
        <fullName>Guarantor_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>

    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Error in plan</description>
        <label>Has Error</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Sirono_Call_Center_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration for Sirono Call Center application.</description>
    <fields>
        <fullName>Auto_Create_Payment_Plan_Error_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for payment plans with errors.</description>
        <inlineHelpText>When enabled, cases are automatically created for payment plans with errors.</inlineHelpText>
        <label>Auto Create Payment Plan Error Cases</label>
        <type>Checkbox</type>
    </fields>
    <label>Sirono Call Center Settings</label>
</CustomObject>

call-center/src/classes/PaymentPlanTriggerHandlerTest.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

@IsTest
public class PaymentPlanTriggerHandlerTest {
    private static final Integer NUM_CHARGE_GROUPS = 2;

    // NOTE: Keeping this out of setup method because it might be parameterized per-test
    private static Contact createPaymentPlanPrereqs() {
        Contact guarantor = TestUtility.generateGuarantorContact();
        guarantor.Guarantor_Id__c = 100.0;
        insert guarantor;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        List<Charge_Group__c> chargeGroups = new List<Charge_Group__c>();
        for (Integer i = 0; i < NUM_CHARGE_GROUPS; i++) {
            Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(
                guarantor.Id,
                patientContact.Id,
                200.0 + i
            );
            chargeGroup.Account_Status__c = Constants.ACCT_STATUS_BILLED;
            chargeGroup.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_PAYMENT_PLAN;
            chargeGroups.add(chargeGroup);
        }
        insert chargeGroups;

        return guarantor;
    }

    private static void verifyPaymentPlanWithErrorsResults() {
        List<Case> cases = [
            SELECT Id, Type, (
                SELECT Id, Charge_Group__r.Account_Status__c, Charge_Group__r.Account_Sub_Status__c
                FROM Case_Charge_Groups__r
            )
            FROM Case
            WHERE Subject = :Constants.CASE_SUBJECT_PAYMENT_PLAN_ERROR
        ];

        // Verify the cases
        System.assertEquals(1, cases.size());
        System.assertEquals(Constants.CASE_TYPE_PAYMENT_PLAN_ERROR, cases[0].Type);

        // Verify the case/charge groups
        List<Case_Charge_Group_Junction__c> caseChargeGroupJunctions = cases[0].Case_Charge_Groups__r;
        System.assertEquals(NUM_CHARGE_GROUPS, caseChargeGroupJunctions.size());
        for (Case_Charge_Group_Junction__c caseChargeGroupJunction : caseChargeGroupJunctions) {
            System.assertEquals(Constants.ACCT_STATUS_BILLED, caseChargeGroupJunction.Charge_Group__r.Account_Status__c);
            System.assertEquals(Constants.ACCT_SUBSTATUS_PAYMENT_PLAN, caseChargeGroupJunction.Charge_Group__r.Account_Sub_Status__c);
        }
    }

    private static void verifyPaymentPlanWithoutErrorsResults() {
        List<Case> cases = [
            SELECT Id, Type, (
                SELECT Id, Charge_Group__r.Account_Status__c, Charge_Group__r.Account_Sub_Status__c
                FROM Case_Charge_Groups__r
            )
            FROM Case
            WHERE Subject = :Constants.CASE_SUBJECT_PAYMENT_PLAN_ERROR
        ];

        // There should be no matches
        System.assert(cases.isEmpty());
    }

    @IsTest
    private static void testPaymentPlanCreatedWithErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Test.startTest();
        {
            Payment_Plan__c paymentPlan = new Payment_Plan__c(
                Guarantor__c = guarantor.Id,
                Has_Error__c = true
            );
            insert paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanCreatedWithoutErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Test.startTest();
        {
            Payment_Plan__c paymentPlan = new Payment_Plan__c(
                Guarantor__c = guarantor.Id,
                Has_Error__c = false
            );
            insert paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithoutErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanCreatedWithErrorsAndSettingDisabled() {
        // Disable payment plan errors auto-case creation
        Sirono_Call_Center_Settings__c sironoCallCenterSettings = SironoCallCenterSettingsUtil.getSironoCallCenterSettings();
        sironoCallCenterSettings.Auto_Create_Payment_Plan_Error_Cases__c = false;
        update sironoCallCenterSettings;

        Contact guarantor = createPaymentPlanPrereqs();

        Test.startTest();
        {
            Payment_Plan__c paymentPlan = new Payment_Plan__c(
                Guarantor__c = guarantor.Id,
                Has_Error__c = true
            );
            insert paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithoutErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanUpdatedToAddErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Payment_Plan__c paymentPlan = new Payment_Plan__c(
            Guarantor__c = guarantor.Id,
            Has_Error__c = false
        );
        insert paymentPlan;

        Test.startTest();
        {
            paymentPlan.Has_Error__c = true;
            update paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanUpdatedToAddErrorsWithSettingDisabled() {
        // Disable payment plan errors auto-case creation
        Sirono_Call_Center_Settings__c sironoCallCenterSettings = SironoCallCenterSettingsUtil.getSironoCallCenterSettings();
        sironoCallCenterSettings.Auto_Create_Payment_Plan_Error_Cases__c = false;
        update sironoCallCenterSettings;

        Contact guarantor = createPaymentPlanPrereqs();

        Payment_Plan__c paymentPlan = new Payment_Plan__c(
            Guarantor__c = guarantor.Id,
            Has_Error__c = false
        );
        insert paymentPlan;

        Test.startTest();
        {
            paymentPlan.Has_Error__c = true;
            update paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithoutErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanUpdatedToClearErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Payment_Plan__c paymentPlan = new Payment_Plan__c(
            Guarantor__c = guarantor.Id,
            Has_Error__c = true
        );
        insert paymentPlan;

        Test.startTest();
        {
            // And update the payment plan not to have
            paymentPlan.Has_Error__c = false;
            update paymentPlan;
        }
        Test.stopTest();

        List<Case> cases = [
            SELECT Id, Type, Status, Reason
            FROM Case
            WHERE Subject = :Constants.CASE_SUBJECT_PAYMENT_PLAN_ERROR
        ];

        // There should be one case in a closed state
        System.assertEquals(1, cases.size());
        System.assertEquals(Constants.CASE_TYPE_PAYMENT_PLAN_ERROR, cases[0].Type);
        System.assertEquals(Constants.CASE_STATUS_CLOSED, cases[0].Status);
        System.assertEquals(Constants.CASE_REASON_CLOSED_AUTOMATED, cases[0].Reason);
    }

    @IsTest
    private static void testPaymentPlanWithErrorsUpdatedBenignChange() {
        Contact guarantor = createPaymentPlanPrereqs();

        // Start with errors
        Payment_Plan__c paymentPlan = new Payment_Plan__c(
            Name = 'Before',
            Guarantor__c = guarantor.Id,
            Has_Error__c = true
        );
        insert paymentPlan;

        verifyPaymentPlanWithErrorsResults();

        Test.startTest();
        {
            // Make a change other than clearing the errors field and make sure no new case is added
            paymentPlan.Name = 'After';
            update paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanWithoutErrorsUpdatedBenignChange() {
        Contact guarantor = createPaymentPlanPrereqs();

        // Start without errors
        Payment_Plan__c paymentPlan = new Payment_Plan__c(
            Name = 'Before',
            Guarantor__c = guarantor.Id,
            Has_Error__c = false
        );
        insert paymentPlan;

        verifyPaymentPlanWithoutErrorsResults();

        Test.startTest();
        {
            // Make a change other than setting the errors field and make sure no new case is added
            paymentPlan.Name = 'After';
            update paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithoutErrorsResults();
    }
}