call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>ChargeGroupStatus.preinvoiced</description>
        <label>Account Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Sub_Status__c</fullName>
        <label>Account Sub Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <summarizedField>Transaction__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction__c.Charge_Group__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>

call-center/src/objects/Service2__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Related Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Services (Guarantors)</relationshipLabel>
        <relationshipName>Services2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service2__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/classes/PaymentRequestTest.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Test the validation logic in PaymentRequest
 */
@IsTest
public with sharing class PaymentRequestTest {

    @TestSetup
    public static void setup() {
        Contact gt = TestUtility.generateGuarantorContact();
        gt.Profile_Pointer_Id__c = Decimal.valueOf(PaymentRestClientMock.GT_SIRONO_ID);
        insert gt;

        Contact pt = TestUtility.generatePatientContact();
        insert pt;

        Charge_Group__c cg = TestUtility.generateChargeGroup(gt.Id, pt.Id, Decimal.valueOf(PaymentRestClientMock.CG_SIRONO_ID));
        cg.Account_Status__c = Constants.ACCT_STATUS_BILLED;
        cg.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_DUE_BY;
        insert cg;

        Service2__c svc = TestUtility.generateService(gt, 575.00);
        insert svc;

        Transaction__c txn = TestUtility.generateServiceTxn(cg, 575.00, svc);
        insert txn;
    }

    public static PaymentRequest buildValidRequest() {
        Contact gt = GuarantorDao.getGuarantorBySironoId(PaymentRestClientMock.GT_SIRONO_ID);
        Charge_Group__c[] cgs = [
            SELECT Id, Guarantor__c, Balance__c
            FROM Charge_Group__c
            WHERE Account_Status__c = :Constants.ACCT_STATUS_BILLED
            AND Guarantor__c = :gt.Id
        ];

        PaymentRequest pmtRequest = new PaymentRequest(gt, cgs);
        pmtRequest.chargeInfo.creditCardNumber = '4005519200000004';
        pmtRequest.chargeInfo.cardHolderName = 'Joe Schmoe';
        pmtRequest.chargeInfo.expirationYear = String.valueOf(Date.today().addYears(2).year()).substring(2);
        pmtRequest.chargeInfo.expirationMonth = String.valueOf(Date.today().month());
        pmtRequest.chargeInfo.cvv = '123';
        pmtRequest.chargeInfo.amount = '150.00';
        pmtRequest.chargeInfo.address = '1111 Cedar St';
        pmtRequest.chargeInfo.city = 'Austin';
        pmtRequest.chargeInfo.state = 'TX';
        pmtRequest.chargeInfo.zip = '78704';
        pmtRequest.guarantor = gt;
        pmtRequest.chargeGroups = new List<Charge_Group__c> { cgs[0] };
        pmtRequest.chargeInfo.amount = '500.00';
        return pmtRequest;
    }

    @IsTest
    public static void paymentRequestSuccessfulValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        List<String> errors = pmtRequest.validate();

        System.assert(errors.isEmpty(), 'Unexpected errors thrown: ' + String.join(errors, '\n'));

    }

    @IsTest
    public static void paymentRequestNoGTValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        pmtRequest.guarantor = null;
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestNoCGValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        pmtRequest.chargeGroups = new List<Charge_Group__c>();
        List<String> errors = pmtRequest.validate();

        for (String error : errors) {
            System.assert(error.contains('Zero or credit balance is not payable.') || error.contains('Amount cannot exceed balance.') ||
                error.contains('Charge Group is a required field.'), 'Unexpected error returned: ' + error);
        }
        System.assert(errors.size() == 3, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestZeroAmountValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        pmtRequest.chargeInfo.amount = '0';
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestBadExpYearValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        pmtRequest.chargeInfo.expirationYear = String.valueOf(Date.today().addYears(-1).year()).substring(2);
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestBadExpMonthValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        pmtRequest.chargeInfo.expirationYear = String.valueOf(Date.today().year()).substring(2);
        pmtRequest.chargeInfo.expirationMonth = String.valueOf(Date.today().addMonths(-1).month());
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestNoCardNumberValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        pmtRequest.chargeInfo.creditCardNumber = null;
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestNoCardholderValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        pmtRequest.chargeInfo.cardHolderName = null;
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestBadCVVValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        //Too long
        pmtRequest.chargeInfo.cvv = '12345';
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));

        //Too Short
        pmtRequest.chargeInfo.cvv = '12';
        errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));

        //Not there
        pmtRequest.chargeInfo.cvv = null;
        errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }

    @IsTest
    public static void paymentRequestZipValidationTest() {
        PaymentRequest pmtRequest = buildValidRequest();
        //Too long
        pmtRequest.chargeInfo.zip = '123456';
        List<String> errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));

        //Too Short
        pmtRequest.chargeInfo.zip = '12';
        errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));

        //Non-numeric
        pmtRequest.chargeInfo.zip = '123Ah';
        errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));

        //Not there
        pmtRequest.chargeInfo.zip = null;
        errors = pmtRequest.validate();

        System.assert(errors.size() == 1, 'Unexpected errors thrown: ' + String.join(errors, '\n'));
    }
}