call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>ChargeGroupStatus.preinvoiced</description>
        <label>Account Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Sub_Status__c</fullName>
        <label>Account Sub Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>

call-center/src/objects/Service2__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Related Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Services (Guarantors)</relationshipLabel>
        <relationshipName>Services2</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Service</label>
    <nameField>
        <displayFormat>SVC-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Sirono_Call_Center_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration for Sirono Call Center application.</description>
    <fields>
        <fullName>Auto_Create_Overdue_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for statements with overdue balances.</description>
        <inlineHelpText>When enabled, cases are automatically created for statements with overdue balances.</inlineHelpText>
        <label>Auto Create Overdue Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Create_Precollection_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for statements with delinquent balances.</description>
        <inlineHelpText>When enabled, cases are automatically created for statements with delinquent balances.</inlineHelpText>
        <label>Auto Create Precollection Cases</label>
        <type>Checkbox</type>
    </fields>
    <label>Sirono Call Center Settings</label>
</CustomObject>

call-center/src/objects/Statement__c.object
<CustomObject>
    <description>Guarantor Statement details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statement_Date__c</fullName>
        <description>Date of the statement</description>
        <label>Statement Date</label>
        <type>Date</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Service2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service2__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/classes/StatementTriggerHandlerTest.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

@IsTest
public class StatementTriggerHandlerTest {
    private static Contact createStatementPrereqs(String status, String substatus, Decimal amount) {
        Contact guarantor = TestUtility.generateGuarantorContact();
        guarantor.Profile_Pointer_Id__c = 100.0;
        insert guarantor;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(
            guarantor.Id,
            patientContact.Id,
            200.0
        );
        chargeGroup.Account_Status__c = status;
        chargeGroup.Account_Sub_Status__c = substatus;
        insert chargeGroup;

        TestUtility.createAllCampaigns();

        Service2__c service = TestUtility.generateService(guarantor, amount);
        insert service;

        Transaction__c txn = TestUtility.generateServiceTxn(chargeGroup, amount, service);
        insert txn;

        return guarantor;
    }

    @IsTest
    private static void testStatementWithOverdueBalance() {
        Contact guarantor = createStatementPrereqs(
            Constants.ACCT_STATUS_BILLED,
            Constants.ACCT_SUBSTATUS_OVERDUE,
            100.00
        );

        Test.startTest();
        {
            Statement__c statement = new Statement__c(
                Statement_Date__c = System.today(),
                Guarantor__c = guarantor.Id
            );
            insert statement;
        }
        Test.stopTest();

        List<Case> cases = [SELECT Id, Type FROM Case WHERE Subject = :Constants.CASE_SUBJECT_GUARANTOR_OVERDUE];
        System.assertEquals(1, cases.size());
        System.assertEquals(Constants.CASE_TYPE_OVERDUE, cases[0].Type);

        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember];
        System.assertEquals(2, campaignMembers.size());
    }

    @IsTest
    private static void testStatementWithNoOverdueBalance() {
        Contact guarantor = createStatementPrereqs(
            Constants.ACCT_STATUS_BILLED,
            Constants.ACCT_SUBSTATUS_OVERDUE,
            -100.00
        );

        Test.startTest();
        {
            Statement__c statement = new Statement__c(
                Statement_Date__c = System.today(),
                Guarantor__c = guarantor.Id
            );
            insert statement;
        }
        Test.stopTest();

        List<Case> cases = [SELECT Id, Type FROM Case WHERE Subject = :Constants.CASE_SUBJECT_GUARANTOR_OVERDUE];
        System.assert(cases.isEmpty());

        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember];
        System.assert(campaignMembers.isEmpty());
    }

    @IsTest
    private static void testStatementWithOverdueBalanceAndSettingDisabled() {
        // Disable overdue balance/precollections auto-case creation
        Sirono_Call_Center_Settings__c sironoCallCenterSettings = SironoCallCenterSettingsUtil.getSironoCallCenterSettings();
        sironoCallCenterSettings.Auto_Create_Overdue_Cases__c = false;
        update sironoCallCenterSettings;

        Contact guarantor = createStatementPrereqs(
            Constants.ACCT_STATUS_BILLED,
            Constants.ACCT_SUBSTATUS_OVERDUE,
            100.00
        );

        Test.startTest();
        {
            Statement__c statement = new Statement__c(
                Statement_Date__c = System.today(),
                Guarantor__c = guarantor.Id
            );
            insert statement;
        }
        Test.stopTest();

        List<Case> cases = [SELECT Id, Type FROM Case WHERE Subject = :Constants.CASE_SUBJECT_GUARANTOR_OVERDUE];
        System.assert(cases.isEmpty());

        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember];
        System.assert(campaignMembers.isEmpty());
    }

    @IsTest
    private static void testStatementWithDelinquentBalance() {
        Contact guarantor = createStatementPrereqs(
            Constants.ACCT_STATUS_BILLED,
            Constants.ACCT_SUBSTATUS_DELINQUENT,
            100.00
        );

        Test.startTest();
        {
            Statement__c statement = new Statement__c(
                Statement_Date__c = System.today(),
                Guarantor__c = guarantor.Id
            );
            insert statement;
        }
        Test.stopTest();

        List<Case> cases = [SELECT Id, Type FROM Case WHERE Subject = :Constants.CASE_SUBJECT_GUARANTOR_DELINQUENT];
        System.assertEquals(1, cases.size());
        System.assertEquals(Constants.CASE_TYPE_PRECOLLECTIONS, cases[0].Type);

        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember];
        System.assertEquals(2, campaignMembers.size());
    }

    @IsTest
    private static void testStatementWithNoDelinquentBalance() {
        Contact guarantor = createStatementPrereqs(
            Constants.ACCT_STATUS_BILLED,
            Constants.ACCT_SUBSTATUS_DELINQUENT,
            -100.00
        );

        Test.startTest();
        {
            Statement__c statement = new Statement__c(
                Statement_Date__c = System.today(),
                Guarantor__c = guarantor.Id
            );
            insert statement;
        }
        Test.stopTest();

        List<Case> cases = [SELECT Id, Type FROM Case WHERE Subject = :Constants.CASE_SUBJECT_GUARANTOR_DELINQUENT];
        System.assert(cases.isEmpty());

        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember];
        System.assert(campaignMembers.isEmpty());
    }

    @IsTest
    private static void testStatementWithDelinquentBalanceAndSettingDisabled() {
        // Disable delinquent balance/precollections auto-case creation
        Sirono_Call_Center_Settings__c sironoCallCenterSettings = SironoCallCenterSettingsUtil.getSironoCallCenterSettings();
        sironoCallCenterSettings.Auto_Create_Precollection_Cases__c = false;
        update sironoCallCenterSettings;

        Contact guarantor = createStatementPrereqs(
            Constants.ACCT_STATUS_BILLED,
            Constants.ACCT_SUBSTATUS_DELINQUENT,
            100.00
        );

        Test.startTest();
        {
            Statement__c statement = new Statement__c(
                Statement_Date__c = System.today(),
                Guarantor__c = guarantor.Id
            );
            insert statement;
        }
        Test.stopTest();

        List<Case> cases = [SELECT Id, Type FROM Case WHERE Subject = :Constants.CASE_SUBJECT_GUARANTOR_DELINQUENT];
        System.assert(cases.isEmpty());

        List<CampaignMember> campaignMembers = [SELECT Id FROM CampaignMember];
        System.assert(campaignMembers.isEmpty());
    }
}