call-center/src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if active account</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Participant is past due</description>
        <label>Delinquent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Error_Date__c</fullName>
        <description>Date of the Error</description>
        <label>Error Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Execute_On_Day__c</fullName>
        <label>Execute on Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Error in plan</description>
        <label>Has Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NextPaymentDate__c</fullName>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Balance__c</fullName>
        <description>Type of plan</description>
        <label>Plan Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Installment_Count__c</fullName>
        <description>payment installment months</description>
        <label>Original Installments</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Plan Number type small int</description>
        <label>Plan Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Balance__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Skip_Payment_Until__c</fullName>
        <description>Defines making payment until date</description>
        <label>Skip Payment Until</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/classes/PaymentPlanJSONParsing.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * JSON Parsing Class for the response which comes from Request. 
 */
public class PaymentPlanJSONParsing extends AbstractSironoJSONParser {

    public class PaymentPlanJSON {
        public String url;
        public Boolean active;
        public Integer installment_amount;
        public Integer number_installments;
        public Integer plan_value;
        public String plan_type;
        public Integer payable_amount;
        public Integer execute_on_day;
        public String guarantor;
        public String next_payment_date;
        //noinspection ApexUnusedDeclaration
        public Integer installments_paid;
        //noinspection ApexUnusedDeclaration
        public Integer installments_total;
        //noinspection ApexUnusedDeclaration
        public Credit_card credit_card;
        public Boolean has_error;
        //noinspection ApexUnusedDeclaration
        public String charges_added_since_start;
        public Date error_date;
        public List<String> chargegroups;
        public Boolean delinquent;
        //noinspection ApexUnusedDeclaration
        public Date delinquent_date;
        //noinspection ApexUnusedDeclaration
        public List<Encounters> encounters;
        //noinspection ApexUnusedDeclaration
        public Integer authorized_amount;
        public String skip_payment_until;
        public String status;
    }

    public class Encounters {
    }

    public class Credit_card {
        //noinspection ApexUnusedDeclaration
        public String card_type;
        //noinspection ApexUnusedDeclaration
        public String last_4;
    }

    public class PaymentPlanWrapper {
        public List<Charge_Group__c> chargeGroupRecords { get; set; }
        public Payment_Plan__c paymentPlanRecord { get; set; }
        public List<Encounter__c> encounterRecords { get; set; }

        public PaymentPlanWrapper() {
            chargeGroupRecords = new List<Charge_Group__c>();
            paymentPlanRecord = new Payment_Plan__c();
            encounterRecords = new List<Encounter__c>();
        }
    }

    public static PaymentPlanJSON parse(String json) {
        return (PaymentPlanJSON) System.JSON.deserialize(json, PaymentPlanJSON.class);
    }

    //TODO when do we pass in a chargegroupId? why don't we just always retrieve all that were sent back with the plan?
    public static PaymentPlanWrapper createPaymentPlanRecord(String json, String guarantorId, String chargeGroupId) {

        List<String> cgIds = new List<String>();
        Set<Decimal> cgIdSet = new Set<Decimal>();
        if (String.isNotBlank(chargeGroupId)) {
            cgIds = chargeGroupId.split(',');
            for (String str : cgIds) {
                if (str.isNumeric()) {
                    cgIdSet.add(Decimal.valueOf(str));
                }
            }
        }

        PaymentPlanWrapper objPaymentPlanWrapper = new PaymentPlanWrapper();
        PaymentPlanJSON objJson = parse(json);

        Payment_Plan__c paymentPlanObj = new Payment_Plan__c();
        paymentPlanObj.Active__c = objJson.active;
        paymentPlanObj.Installment_Amount__c = AbstractSironoJSONParser.convertToDollars(objJson.installment_amount);
        paymentPlanObj.Original_Installment_Count__c = objJson.number_installments;
        paymentPlanObj.Original_Balance__c = AbstractSironoJSONParser.convertToDollars(objJson.plan_value);

        if (Constants.PLANTYPE_AUTO.equalsIgnoreCase(objJson.plan_type)) {
            paymentPlanObj.Plan_Type__c = Constants.AUTOMATIC;
        } else if (Constants.PLANTYPE_PROMISE.equalsIgnoreCase(objJson.plan_type)) {
            paymentPlanObj.Plan_Type__c = Constants.MANUAL;
        }

        paymentPlanObj.Remaining_Balance__c = AbstractSironoJSONParser.convertToDollars(objJson.payable_amount);
        paymentPlanObj.Execute_On_Day__c = objJson.execute_on_day;
        paymentPlanObj.NextPaymentDate__c = AbstractSironoJSONParser.parseDate(objJson.next_payment_date);
        paymentPlanObj.Skip_Payment_Until__c = AbstractSironoJSONParser.parseDate(objJson.skip_payment_until);
        paymentPlanObj.Has_Error__c = objJson.has_error;
        paymentPlanObj.Error_Date__c = objJson.error_date;
        paymentPlanObj.Delinquent__c = objJson.delinquent;

        if (!String.isBlank(guarantorId)) {
            paymentPlanObj.Guarantor__c = guarantorId;
        } else {
            String gtId = AbstractSironoJSONParser.parseSironoId(objJson.guarantor, RestClientConstants.GUARANTOR_URL_RESOURCE_TYPE);
            Contact gt = GuarantorService.getGuarantorBySironoId(gtId);
            paymentPlanObj.Guarantor__c = gt.Id;
        }

        paymentPlanObj.Status__c = objJson.status;
        if (!String.isBlank(objJson.url)) {
            String planSironoIdStr = AbstractSironoJSONParser.parseSironoId(objJson.url, RestClientConstants.PPLAN_URL_RESOURCE_TYPE);

            if (!String.isBlank(planSironoIdStr)) {
                Decimal planSironoId = Decimal.valueOf(planSironoIdStr);
                paymentPlanObj.Sirono_ID__c = planSironoId;
                // TODO remove when name is turned into an autonumber field
                paymentPlanObj.Name = String.valueOf(paymentPlanObj.Sirono_ID__c);
                Payment_Plan__c paymentPlan = PaymentPlanDao.getPaymentPlanBySironoId(planSironoId);
                if (paymentPlan != null) {
                    paymentPlanObj.Id = paymentPlan.Id ;
                }
            }
        }

        //Get chargeGroup id from SF.
        System.debug('chargeGroupId' + chargeGroupId);
        if (String.isBlank(chargeGroupId)) {
            System.debug('objJson.chargegroups' + objJson.chargegroups);
            for (String str : objJson.chargegroups) {
                String strChargeGroupID = AbstractSironoJSONParser.parseSironoId(str, 'chargegroups');
                if (strChargeGroupID.isNumeric()) {
                    cgIdSet.add(Decimal.valueOf(strChargeGroupID));
                }
            }
        }

        System.debug('cgIdSet' + cgIdSet);
        if (!cgIdSet.isEmpty()) {
            List<Charge_Group__c> chargeGroups = ChargeGroupService.getBySironoIds(new List<Decimal>(cgIdSet));
            for (Charge_Group__c objCG: chargeGroups) {
                objCG.Payment_Plan__c = paymentPlanObj.Id;
            }
            objPaymentPlanWrapper.chargeGroupRecords = chargeGroups;
        }

        objPaymentPlanWrapper.paymentPlanRecord = paymentPlanObj;
        return objPaymentPlanWrapper;
    }

    private static String testGuarantorSironoId = '23232323';

    /**
     *  Test response for the test class and testing.
     */
    public static String testResponse() {

        String responseBody = '{' +
            '   "url": "' + TestUtility.url + '",' +
            '   "active": true,' +
            '   "installment_amount": 5000,' +
            '   "number_installments": 7,' +
            '   "plan_value": 32772,' +
            '   "plan_type": "' + TestUtility.planType + '",' +
            '   "payable_amount": 32772,' +
            '   "execute_on_day": 13,' +
            '   "guarantor": "http://127.0.0.1:8000/paystaff/api/guarantors/' + testGuarantorSironoId + '/",' +
            '   "next_payment_date": "2016-05-13",' +
            '   "installments_paid": 0,' +
            '   "installments_total": 7,' +
            '   "credit_card": {' +
            '       "card_type": "Visa",' +
            '       "last_4": "1881"' +
            '   },' +
            '   "has_error": false,' +
            '   "charges_added_since_start": null,' +
            '   "error_date": "' + TestUtility.errorDate + '",' +
            '   "chargegroups": ["http://127.0.0.1:8000/paystaff/api/chargegroups/1321212/", "http://127.0.0.1:8000/paystaff/api/chargegroups/10283475/"],' +
            '   "delinquent": false,' +
            '   "delinquent_date": "' + TestUtility.delinquentDate + '",' +
            '   "encounters": [],' +
            '   "authorized_amount": 0,' +
            '   "skip_payment_until":"2016-12-01",' +
            '   "status":"started"' +
            '}';
        return responseBody;
    }
    
    
    /*
    * 08-17-2016: Sirono - Tracker # 127940071
    *  Test response for the test class and testing.
    */
    public static String testResponse1() {

        String responseBody = '{' +
            '   "url": "' + TestUtility.url + '",' +
            '   "active": true,' +
            '   "installment_amount": 5000,' +
            '   "number_installments": 7,' +
            '   "plan_value": 32772,' +
            '   "plan_type": "' + TestUtility.planType + '",' +
            '   "payable_amount": 32772,' +
            '   "execute_on_day": 13,' +
            '   "guarantor": "http://127.0.0.1:8000/paystaff/api/guarantors/23232323/",' +
            '   "next_payment_date": "2016-05-13",' +
            '   "installments_paid": 0,' +
            '   "installments_total": 7,' +
            '   "credit_card": {' +
            '       "card_type": "Visa",' +
            '       "last_4": "1881"' +
            '   },' +
            '   "has_error": false,' +
            '   "charges_added_since_start": null,' +
            '   "error_date": null, ' +
            '   "chargegroups": ["http://127.0.0.1:8000/paystaff/api/chargegroups/1321212/", "http://127.0.0.1:8000/paystaff/api/chargegroups/10283475/"],' +
            '   "delinquent": false,' +
            '   "delinquent_date": null, ' +
            '   "encounters": [],' +
            '   "authorized_amount": 0,' +
            '   "skip_payment_until":"2016-12-01",' +
            '   "status":"started"' +
            '}';

        return responseBody;
    }
}