call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Method__c.object
<CustomObject>
    <description>Details about a method of payment: credit card, ACH, check, or cash.</description>
    <fields>
        <fullName>Card_Type__c</fullName>
        <description>Type of Credit card used</description>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>MasterCard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>American Express</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <formula>TEXT(Type__c) &amp;
CASE(Type__c,
&quot;Credit Card&quot;,  &quot; &quot; &amp; TEXT(Card_Type__c) &amp; &quot;-&quot; &amp;  Last_4__c,
&quot;ACH&quot;, &quot; &quot; &amp; TEXT(Account_Number__c),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Execute_On_Day__c</fullName>
        <label>Execute on Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Installments_Completed__c</fullName>
        <formula>Original_Installment_Count__c -  Remaining_Installment_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installments Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NextPaymentDate__c</fullName>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Installment_Count__c</fullName>
        <description>payment installment months</description>
        <label>Original Installments</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Standing__c</fullName>
        <description>PPS is the status of the ACTIVE payment plan.

            Options: Past Due, In Error, Good Standing</description>
        <formula>IF(Active__c=FALSE,&quot;&quot;,IF(Delinquent__c = TRUE, &quot;Past Due&quot;, IF(Has_Error__c = TRUE, &quot;In Error&quot;, &quot;Good Standing&quot;)))</formula>
        <label>Payment Plan Standing</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Plan Number type small int</description>
        <label>Plan Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remaining_Balance__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Remaining_Installment_Count__c</fullName>
        <formula>ABS(CEILING(Remaining_Balance__c / Installment_Amount__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Remaining Installments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/classes/PaymentPlanDao.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * DB functionality for PaymentPlans
 * TODO eventually all the PPlan SOQl & DML should be here & then the PaymentPlanSecurityContext can become in innerclass here
 */
public with sharing class PaymentPlanDao extends AbstractDao {

    /**
      * Return the active payment plan for the given guarantorId, null if there is none
      * @param - String guarantorId  The guarantorId of the plan.
      * @return - Payment_Plan__c The active plan.
     */
    public static Payment_Plan__c getActivePaymentPlan(String guarantorId) {

        if (PaymentPlanSecurityContext.SELECT_CONTEXT.actionAllowed()) {
            List<Payment_Plan__c> plans = [
                SELECT Id, Sirono_ID__c, Active__c, Payment_Plan_Standing__c, Plan_Type__c, NextPaymentDate__c, Installment_Amount__c,
                    Installments_Completed__c, Original_Installment_Count__c
                FROM Payment_Plan__c
                WHERE Active__c = TRUE
                AND Sirono_ID__c != NULL
                AND Guarantor__c = :guarantorId
                LIMIT 1
            ];

            if (plans.size() > 0) {
                return plans.get(0);
            }
        }

        return null;
    }

    /**
     * Return the Payment_Plan__c with the given Sirono_ID__c
     * @param - String sirionoId The sironoId of the plan
     * @return Payment_Plan__c The requested plan
     */
    public static Payment_Plan__c getPaymentPlanBySironoId(String sironoId) {
        return getPaymentPlanBySironoId(Decimal.valueOf(sironoId));
    }

    /**
     * Return the Payment_Plan__c with the given Sirono_ID__c
     * @param - Decimal sironoId The sironoId of the plan
     * @return Payment_Plan__c The requested plan
     */
    public static Payment_Plan__c getPaymentPlanBySironoId(Decimal sironoId) {

        if (PaymentPlanSecurityContext.SELECT_CONTEXT.actionAllowed()) {
            List<Payment_Plan__c> plans = [
                SELECT Id, Sirono_ID__c, Active__c
                FROM Payment_Plan__c
                WHERE Sirono_ID__c = :sironoId
                LIMIT 1
            ];

            if (plans.size() > 0) {
                return plans.get(0);
            }
        }

        return null;
    }

    /**
     * Upsert the given list of Payment_Plan__c objects
     * @param - Payment_Plan__c the plans to be upserted
     */
    public static void upsertPlans(List<Payment_Plan__c> paymentPlans) {
        if (PaymentPlanSecurityContext.UPSERT_CONTEXT.actionAllowed()) {
            upsert paymentPlans;
        }
    }

    /**
     * Upsert a single payment plan.
     *
     * @param Payment_Plan__c plan - The plan to upsert.
     */
    public static void upsertPlan(Payment_Plan__c plan) {
        upsertPlans(new List<Payment_Plan__c> { plan });
    }

    /**
     * Get Active Payment Plans.
     *
     * @param Id guarantorId - The contact guarantor id associated with the plan.
     * @return List<Payment_Plan__c> - The List containing Active Paymen_Plan__c objects.
     */
    public static List<Payment_Plan__c> getActivePaymentPlanWithMethod(Id guarantorId) {
        List<Payment_Plan__c> plans = new List<Payment_Plan__c>();

        if (PaymentPlanSecurityContext.GUARANTOR_SELECT.actionAllowed() && PaymentMethodSecurityContext.GUARANTOR_SELECT.actionAllowed()) {
            plans = [
                SELECT Id, Name, Original_Installment_Count__c, Remaining_Balance__c, Installment_Amount__c, CreatedDate,
                    NextPaymentDate__c, Plan_Type__c, Remaining_Installment_Count__c, Execute_On_Day__c, Sirono_ID__c,
                    Payment_Method__c, Payment_Method__r.Sirono_ID__c, Payment_Method__r.Display_Name__c,
                    Payment_Method__r.Card_Type__c, Payment_Method__r.Last_4__c
                FROM Payment_Plan__c
                WHERE Guarantor__c = :guarantorId AND Active__c = TRUE
            ];
        }

        return plans;
    }

    /**
     * Get a PaymentPlay by id.
     *
     * @param Id planId - The payment plan Id.
     * @return List<Payment_Plan__c> - The List containing the single payment plan if it was found.
     */
    public static List<Payment_Plan__c> getPaymentPlan(Id planId) {
        List<Payment_Plan__c> plans = new List<Payment_Plan__c>();

        if (PaymentPlanSecurityContext.GUARANTOR_SELECT.actionAllowed() && PaymentMethodSecurityContext.GUARANTOR_SELECT.actionAllowed()) {
            plans = [
                SELECT Id, Name, Original_Installment_Count__c, Remaining_Balance__c, Installment_Amount__c, CreatedDate,
                    NextPaymentDate__c, Plan_Type__c, Remaining_Installment_Count__c, Execute_On_Day__c, Sirono_ID__c, Guarantor__c,
                    Payment_Method__c, Payment_Method__r.Sirono_ID__c, Payment_Method__r.Display_Name__c,
                    Payment_Method__r.Card_Type__c, Payment_Method__r.Last_4__c
                FROM Payment_Plan__c
                WHERE Id = :planId
            ];
        }
        return plans;
    }

    public static void updateAll(List<Payment_Plan__c> plans) {
        if (PaymentPlanSecurityContext.UPDATE_CONTEXT.actionAllowed()) {
            update plans;
        }
    }
}