call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deposit_Date__c</fullName>
        <description>Date of deposit</description>
        <label>Deposit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer of the account</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <description>Either Sirono ID or composite key: Sirono ID, Guarantor, Post Date, Code, Payor</description>
        <externalId>true</externalId>
        <label>ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Id__c</fullName>
        <displayFormat>{0000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor_Transaction_Id__c</fullName>
        <description>Id of the processor</description>
        <label>Processor Transaction ID</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>Id number</description>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment__c.object
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>

src/objects/Payment__c.object
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>

call-center/src/objects/Payment_Method__c.object
<CustomObject>
    <description>Details about a method of payment: credit card, ACH, check, or cash.</description>
    <fields>
        <fullName>Card_Type__c</fullName>
        <description>Type of Credit card used</description>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>MasterCard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>American Express</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/classes/PaymentDao.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Payment DAO for Payment object SOQL/DML operations
 * TODO fix our sharing model
 */
public with sharing class PaymentDao {
	/**
	 * This method is used to Insert Payment record.
	 * @param List<Payment__c> payments - List of payment record for insert
	 **/
    public static void insertPayment(List<Payment__c> payments) {
        if (PaymentSecurityContext.CREATE_CONTEXT.actionAllowed()) {
            insert payments;
        }
    }

    public static void insertPaymentAndTransactions(List<SObject> paymentsAndTransactions) {
        if (PaymentSecurityContext.CREATE_CONTEXT.actionAllowed()) {
            // Create the Payment and associated Transactions
            // TODO: Why is this using Database.insert() instead of insert? Because it's heterogenerous?
            Database.insert(paymentsAndTransactions);
        }
    }

    /**
     * This method returns payment record by Id.
     * @param Id paymentId - id of payment record
     **/
    public static Payment__c getPayment(Id paymentId) {
        if (PaymentSecurityContext.DAO_SELECT_CONTEXT.actionAllowed()) {
            try {
                Payment__c payment = [
                    SELECT Id,
                        Amount__c,
                        Deposit_Date__c,
                        Encounter__c,
                        Guarantor__c,
                        Method__c,
                        Name,
                        Payment_Id__c,
                        Sirono_Id__c,
                        Id__c

                    FROM Payment__c
                    WHERE Id = :paymentId
                ];
                return payment;
            } catch (QueryException ex) {
                System.debug('PaymentDao.getPayment: ' + ex.getStackTraceString());
                return null;
            }
        }

        return null;
    }

    /**
     * This method returns payment record by Id.
     * @param Id paymentId - id of payment record
     **/
    public static Payment__c getPaymentBySironoId(Decimal sironoId) {
        if (PaymentSecurityContext.DAO_SELECT_CONTEXT.actionAllowed()) {
            try {
                Payment__c payment = [
                    SELECT Id,
                        Amount__c,
                        Deposit_Date__c,
                        Encounter__c,
                        Guarantor__c,
                        Method__c,
                        Name,
                        Payment_Id__c,
                        Sirono_Id__c,
                        Id__c

                    FROM Payment__c
                    WHERE Sirono_Id__c = :sironoId
                ];
                return payment;
            } catch (QueryException ex) {
                System.debug('PaymentDao.getPaymentBySironoId: ' + ex.getStackTraceString());
                return null;
            }
        }

        return null;
    }

    /**
     * Get the payments for a contact.
     *
     * @param Id contactId
     * @return List<Payment__c> - The list of payments.
     */
    public static List<Payment__c> getPayments(Id contactId) {
        List<Payment__c> payments = new List<Payment__c>();
        if (PaymentSecurityContext.DAO_SELECT_CONTEXT.actionAllowed() &&
            PaymentMethodSecurityContext.GUARANTOR_SELECT.actionAllowed()) {
            payments = [
                SELECT
                    Id,
                    Method__c,
                    Name,
                    Deposit_Date__c,
                    Payment_Id__c,
                    Payment_Method__r.Last_4__c,
                    Payment_Method__r.Card_Type__c,
                    Processor_Transaction_Id__c,
                    Amount__c
                FROM Payment__c
                WHERE Guarantor__c = :contactId
                ORDER BY Name DESC
                LIMIT 50000
            ];
        }

        return payments;
    }

}