call-center/src/objects/Contact.object
<CustomObject>


    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <description>Patient medical Record number</description>
        <label>Medical Record Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Social_Security_Number__c</fullName>
        <description>Social Security number of guarantor</description>
        <label>Social Security Number</label>
        <length>11</length>
        <maskChar>X</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>

call-center/src/classes/ContactDao.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Access Contact Data.
 * This class is use to get Contact related details (Not based on record types).
 **/
public with sharing class ContactDao extends AbstractDao {

    /**
     * Get Contact details filtered by Id.
     *
     * @param String contactId - That contains Contact Id.
     * @returns Contact ob - That contains Contact details.
     **/
    public static Contact getContactDetails(String contactId) {
        Contact ob = null;
        if (ContactSecurityContext.SELECT_CONTEXT.actionAllowed()) {
            for (Contact c : [
                SELECT Id, FirstName, MiddleName, LastName, Name, Suffix, Birthdate, Social_Security_Number__c,
                    Medical_Record_Number__c, RecordType.DeveloperName, HomePhone, MobilePhone, OtherPhone, Salutation,
                    MailingCity, MailingCountry, MailingPostalCode, MailingState, MailingStreet,
                    Profile_Pointer_ID__c
                FROM Contact
                WHERE Id = :contactId
            ]) {
                ob = c;
            }
        }
        return ob;
    }
}