call-center/src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deposit_Date__c</fullName>
        <description>Date of deposit</description>
        <label>Deposit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer of the account</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <description>Either Sirono ID or composite key: Sirono ID, Guarantor, Post Date, Code, Payor</description>
        <externalId>true</externalId>
        <label>ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Mastercard</fullName>
                </value>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>Amex</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_Id__c</fullName>
        <displayFormat>{0000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Posted_Amount__c</fullName>
        <label>Posted Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Processor_Transaction_Id__c</fullName>
        <description>Id of the processor</description>
        <label>Processor Transaction ID</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <description>Id number</description>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment__c.object
    <fields>
        <fullName>Charge_Date__c</fullName>
        <description>Date of transaction</description>
        <label>Charge Date</label>
        <type>DateTime</type>
    </fields>

src/objects/Payment__c.object
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>

call-center/src/classes/PaymentSecurityContext.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * This class is use for Security Context of Payment object
 **/
public with sharing class PaymentSecurityContext extends SecurityContext {

    // Field constants for Payment__c object.
    private static final String AMOUNT = 'Amount__c';
    private static final String CHARGE_DATE = 'Charge_Date__c';
    private static final String DEPOSIT_DATE = 'Deposit_Date__c';
    private static final String ENCOUNTER = 'Encounter__c';
    private static final String GUARANTOR = 'Guarantor__c';
    private static final String ID_C = 'Id__c';
    private static final String LAST_4 = 'Last_4__c';
    private static final String METHOD = 'Method__c';
    private static final String NAME = 'Name';
    private static final String PAYMENT_ID = 'Payment_Id__c';
    private static final String POSTED_AMOUNT = 'Posted_Amount__c';
    private static final String PROCESSOR_TRANSACTION_ID = 'Processor_Transaction_Id__c';
    private static final String SIRONO_ID = 'Sirono_Id__c';

    // Below field(s) are use for Select/Read permission.
    private static final String ID = 'Id';

    // The fields for inserting a Payment in PayEstimate
    private static final Set<String> CREATE_FIELDS = new Set<String> {
        AMOUNT, DEPOSIT_DATE, ENCOUNTER, GUARANTOR
    };

    // The fields for inserting a Payment in PayStaffWSUtill
    private static final Set<String> PSWU_CREATE_FIELDS = new Set<String> {
        GUARANTOR, CHARGE_DATE, METHOD, LAST_4, PROCESSOR_TRANSACTION_ID, AMOUNT, SIRONO_ID, DEPOSIT_DATE
    };

    // The fields for updating a Payment__c in TxnAggregationUtils
    private static final Set<String> UPDATE_FIELDS = new Set<String> {
        AMOUNT, POSTED_AMOUNT
    };

    // The fields for selecting a Payment__c in TxnAggregationUtils
    private static final Set<String> SELECT_FIELDS = new Set<String> {
        ID, SIRONO_ID
    };

    // The fields for selecting a Payment__c in PaymentDao
    private static final Set<String> DAO_SELECT_FIELDS = new Set<String> {
        ID, AMOUNT, DEPOSIT_DATE, ENCOUNTER, GUARANTOR, METHOD, PAYMENT_ID, SIRONO_ID, ID_C
    };


    // The fields for selecting a Payment__c in EncounterUtil
    private static final Set<String> EU_SELECT_FIELDS = new Set<String> {
        ENCOUNTER, AMOUNT
    };

    /**
     * Constructor of class that assign variables based on parameters
     *
     * @param Set<String> fields - That contains Object's Fields
     * @param ACTION actionToPerform - That contains Action Name (Create/Update/Delete/Undelete)
     **/
    private PaymentSecurityContext(Set<String> fields, ACTION actionToPerform) {
        this.fieldsToCheck = fields;
        this.objectAction = actionToPerform;
    }

    /**
     * The create context for Payment__c in PayEstimate
     **/
    public static final PaymentSecurityContext CREATE_CONTEXT = new PaymentSecurityContext(CREATE_FIELDS, ACTION.OBJ_CREATE);
    
    /**
     * The create context for Payment__c in PayStaffWSUtill
     **/
    public static final PaymentSecurityContext PSWU_CREATE_CONTEXT = new PaymentSecurityContext(PSWU_CREATE_FIELDS, ACTION.OBJ_CREATE);
    
    /**
     * The update context for Payment__c in TxnAggregationUtils
     **/
    public static final PaymentSecurityContext UPDATE_CONTEXT = new PaymentSecurityContext(UPDATE_FIELDS, ACTION.OBJ_UPDATE);

    /**
     * The select context for Payment__c in TxnAggregationUtils
     **/
    public static final PaymentSecurityContext SELECT_CONTEXT = new PaymentSecurityContext(SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * The select context for Payment__c in EncounterUtil
     **/
    public static final PaymentSecurityContext EU_SELECT_CONTEXT = new PaymentSecurityContext(EU_SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * The select context for Payment__c in PaymentDao
     **/
    public static final PaymentSecurityContext DAO_SELECT_CONTEXT = new PaymentSecurityContext(DAO_SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * Override getObjectType method of SecurityContext class
     **/
    public override System.Type getObjectType() {
        return Payment__c.class;
    }
}