call-center/src/objects/Payment_Method__c.object
<CustomObject>
    <description>Details about a method of payment: credit card, ACH, check, or cash.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Bank account number</description>
        <label>Account Number</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <description>Name of the card Holder</description>
        <label>Card Holder Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <description>Type of Credit card used</description>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Visa</fullName>
                </value>
                <value>
                    <fullName>MasterCard</fullName>
                </value>
                <value>
                    <fullName>Discover</fullName>
                </value>
                <value>
                    <fullName>American Express</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <formula>TEXT(Type__c) &amp;
CASE(Type__c,
&quot;Credit Card&quot;,  &quot; &quot; &amp; TEXT(Card_Type__c) &amp; &quot;-&quot; &amp;  Last_4__c,
&quot;ACH&quot;, &quot; &quot; &amp; TEXT(Account_Number__c),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>MM/YY (i.e. 02/16)</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method_Token__c</fullName>
        <label>Payment Method Token</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Routing_Number__c</fullName>
        <description>The MICR routing number consists of 9 digits: &quot;XXXXYYYYC&quot;  where XXXX is Federal Reserve Routing Symbol, YYYY is ABA Institution Identifier, and C is the Check Digit.</description>
        <inlineHelpText>for ACH</inlineHelpText>
        <label>Routing Number</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sirono_Id__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>ACH</fullName>
                </value>
                <value>
                    <fullName>Check</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/classes/PaymentMethodSecurityContext.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

public with sharing class PaymentMethodSecurityContext extends SecurityContext {

    // Field constants for Payment_Method__c object.
    private static final String ACCOUNT_NUMBER = 'Account_Number__c';
    private static final String CARD_HOLDER_NAME = 'Card_Holder_Name__c';
    private static final String CARD_TYPE = 'Card_Type__c';
    private static final String DISPLAY_NAME = 'Display_Name__c';
    private static final String EXPIRATION_DATE = 'Expiration_Date__c';
    private static final String GUARANTOR = 'Guarantor__c';
    private static final String ID = 'Id';
    private static final String ID_C = 'ID__c';
    private static final String LAST_4 = 'Last_4__c';
    private static final String ROUTING_NUMBER = 'Routing_Number__c';
    private static final String SIRONO_ID = 'Sirono_ID__c';
    private static final String TOKEN = 'Payment_Method_Token__c';
    private static final String TYPE = 'Type__c';

    // Guarantor Select fields
    private static final Set<String> GUARANTOR_SELECT_FIELDS = new Set<String> {
        ID, ACCOUNT_NUMBER, CARD_HOLDER_NAME, CARD_TYPE, DISPLAY_NAME, EXPIRATION_DATE, ID_C, LAST_4,
        TOKEN, ROUTING_NUMBER, SIRONO_ID, TYPE, GUARANTOR
    };

    /**
     * Constructor of class that assign variables based on parameters
     *
     * @param Set<String> fields - That contains Object's Fields
     * @param ACTION actionToPerform - That contains Action Name (Create/Update/Delete/Undelete)
     **/
    private PaymentMethodSecurityContext(Set<String> fields, ACTION actionToPerform) {
        this.fieldsToCheck = fields;
        this.objectAction = actionToPerform;
    }

    /**
     * The select context for Guarantors.
     **/
    public static final PaymentMethodSecurityContext GUARANTOR_SELECT = new PaymentMethodSecurityContext(GUARANTOR_SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * Override getObjectType method of SecurityContext class
     **/
    public override System.Type getObjectType() {
        return Payment_Method__c.class;
    }
}