src/objects/Adjustment__c.object
<CustomObject>
    <description>Metadata about Adjustments</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>Payment_Adjustments__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionTriggerHandler.cls
/*
*
* When Transactions are inserted, updated or deleted,
* calculate the rollup Amount on their related Service or Adjustment
*/
public with sharing class TransactionTriggerHandler {

    public static void afterInsert(List<Transaction__c> newList) {
        processInsertsAndDeletes(newList);
    }

    public static void afterDelete(List<Transaction__c> oldList) {
        processInsertsAndDeletes(oldList);
    }

    private static void processInsertsAndDeletes(List<Transaction__c> txnList) {
        Set<Id> serviceIds = new Set<Id>();
        Set<Id> adjIds = new Set<Id>();

        for (Transaction__c txn : txnList) {
            if (txn.Service__c != null) {
                serviceIds.add(txn.Service__c);
            }

            if (txn.Adjustment__c != null) {
                adjIds.add(txn.Adjustment__c);
            }
        }

        TxnAggregationUtils.aggregateServiceTxns(serviceIds);
        TxnAggregationUtils.aggregateAdjTxns(adjIds);
    }

    /*
     *  When a transaction is updated, only calculate rollups if the amount or related object changed
     */
    public static void afterUpdate(List<Transaction__c> newList, Map<Id, Transaction__c> oldMap) {

        Set<Id> serviceIds = new Set<Id>();
        Set<Id> adjIds = new Set<Id>();

        for (Transaction__c newTxn : newList) {
            Transaction__c oldTxn = oldMap.get(newTxn.Id);

            if (newTxn.Service__c != null) {
                // It should be possibile to improve the performance of this by
                // updating only when (newTxn.Amount__c != oldTxn.Amount__c)
                // Perform unconditionally until we iron out all the kinks in the
                // data relationships & informatica jobs
                serviceIds.add(newTxn.Service__c);

                // Probably overly cautious with this - I think this case is highly unlikely
                if (newTxn.Service__c != oldTxn.Service__c){
                    serviceIds.add(newTxn.Service__c);
                    serviceIds.add(oldTxn.Service__c);
                }
            }

            if (newTxn.Adjustment__c != null) {
                // It should be possibile to improve the performance of this by
                // updating only when (newTxn.Amount__c != oldTxn.Amount__c)
                // Perform unconditionally until we iron out all the kinks in the
                // data relationships & informatica jobs
                adjIds.add(newTxn.Adjustment__c);

                // Probably overly cautious with this - I think this case is highly unlikely
                if (newTxn.Adjustment__c != oldTxn.Adjustment__c){
                    adjIds.add(newTxn.Adjustment__c);
                    adjIds.add(newTxn.Adjustment__c);
                }
            }
        }

        TxnAggregationUtils.aggregateServiceTxns(serviceIds);
        TxnAggregationUtils.aggregateAdjTxns(adjIds);
    }
}