src/objects/Adjustment__c.object
<CustomObject>
    <description>Metadata about Adjustments</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>Payment_Adjustments__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TxnAdjustmentAggregationTest.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

@IsTest
public with sharing class TxnAdjustmentAggregationTest {

    private static Decimal CG_EXT_ID = 456;

    @TestSetup
    public static void setupData() {
        Contact gt = TestUtility.generateGuarantorContact();
        Contact pt = TestUtility.generatePatientContact();

        insert new Contact[] { gt, pt };

        Charge_Group__c cg = TestUtility.generateChargeGroup(gt.Id, pt.Id, CG_EXT_ID);
        insert  cg;

    }

    /*
     *  When a sirono payment's transactions are saved, the payment's posted_amount should be the absolute value
     *  of the sum of all the transactions' amounts. The Payment amount shouldn't change
     */
    @IsTest
    public static void testAdjustmentAmountAggregation() {
        Contact gt = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Charge_Group__c cg = [SELECT Id FROM Charge_Group__c];

        Adjustment__c adj = TestUtility.generateAdjustment(gt.Id, 'Some:Fake:Key', null);
        insert adj;

        Test.startTest();

        Transaction__c[] txns = new List<Transaction__c>();
        txns.add(TestUtility.generateAdjTxn(cg, 300.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 150.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 50.00, adj));

        insert txns;

        Test.stopTest();

        adj = [SELECT Id, Amount__c FROM Adjustment__c];

        System.assertEquals(-500.00 , adj.Amount__c, 'Expected adjustment amount to be -500.00, but was: ' + adj.Amount__c);
    }

    @IsTest
    public static void testAdjustmentTxnUpdated() {
        Contact gt = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Charge_Group__c cg = [SELECT Id FROM Charge_Group__c];

        Adjustment__c adj = TestUtility.generateAdjustment(gt.Id, 'Some:Fake:Key', null);
        insert adj;

        Transaction__c[] txns = new List<Transaction__c>();
        txns.add(TestUtility.generateAdjTxn(cg, 300.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 150.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 50.00, adj));

        insert txns;

        Test.startTest();
        adj = [SELECT Id, Amount__c FROM Adjustment__c];

        System.assertEquals(-500.00 , adj.Amount__c, 'Expected adjustment amount to be -500.00, but was: ' + adj.Amount__c);

        for (Transaction__c txn : txns) {
            txn.Amount__c = txn.Amount__c - 20.00;
        }

        update txns;

        Test.stopTest();

        adj = [SELECT Id, Amount__c FROM Adjustment__c];

        System.assertEquals(-440.00 , adj.Amount__c, 'Expected adjustment amount to be -440.00, but was: ' + adj.Amount__c);
    }

    @IsTest
    public static void testAdjustmentTxnDeleted() {
        Contact gt = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Charge_Group__c cg = [SELECT Id FROM Charge_Group__c];

        Adjustment__c adj = TestUtility.generateAdjustment(gt.Id, 'Some:Fake:Key', null);
        insert adj;

        Transaction__c[] txns = new List<Transaction__c>();
        txns.add(TestUtility.generateAdjTxn(cg, 300.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 150.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 50.00, adj));

        insert txns;

        Test.startTest();
        adj = [SELECT Id, Amount__c FROM Adjustment__c];

        System.assertEquals(-500.00 , adj.Amount__c, 'Expected adjustment amount to be -500.00, but was: ' + adj.Amount__c);

        DELETE txns[2];

        Test.stopTest();

        adj = [SELECT Id, Amount__c FROM Adjustment__c];

        System.assertEquals(-450.00 , adj.Amount__c, 'Expected adjustment amount to be -450.00, but was: ' + adj.Amount__c);
    }

    @IsTest
    public static void testAdjustmentTxnAdded() {
        Contact gt = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Charge_Group__c cg = [SELECT Id FROM Charge_Group__c];

        Adjustment__c adj = TestUtility.generateAdjustment(gt.Id, 'Some:Fake:Key', null);
        insert adj;

        Transaction__c[] txns = new List<Transaction__c>();
        txns.add(TestUtility.generateAdjTxn(cg, 300.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 150.00, adj));

        insert txns;

        Test.startTest();
        adj = [SELECT Id, Amount__c FROM Adjustment__c];
        System.assertEquals(-450.00 , adj.Amount__c, 'Expected adjustment amount to be -450.00, but was: ' + adj.Amount__c);

        Transaction__c newTxn = TestUtility.generateAdjTxn(cg, 50.00, adj);
        insert newTxn;
        Test.stopTest();

        adj = [SELECT Id, Amount__c FROM Adjustment__c];

        System.assertEquals(-500.00 , adj.Amount__c, 'Expected adjustment amount to be -500.00, but was: ' + adj.Amount__c);
    }

    @IsTest
    public static void testAdjustmentTxnDeleteAll() {
        Contact gt = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];
        Charge_Group__c cg = [SELECT Id FROM Charge_Group__c];

        Adjustment__c adj = TestUtility.generateAdjustment(gt.Id, 'Some:Fake:Key', null);
        insert adj;

        Transaction__c[] txns = new List<Transaction__c>();
        txns.add(TestUtility.generateAdjTxn(cg, 300.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 150.00, adj));
        txns.add(TestUtility.generateAdjTxn(cg, 50.00, adj));
        insert txns;

        Test.startTest();
        adj = [SELECT Id, Amount__c FROM Adjustment__c];
        System.assertEquals(-500.00 , adj.Amount__c, 'Expected adjustment amount to be -500.00, but was: ' + adj.Amount__c);

        delete txns;
        Test.stopTest();

        adj = [SELECT Id, Amount__c FROM Adjustment__c];

        System.assertEquals(0 , adj.Amount__c, 'Expected adjustment amount to be 0.00, but was: ' + adj.Amount__c);
    }
}