src/objects/Adjustment__c.object
<CustomObject>
    <description>Metadata about Adjustments</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Adjustments__c.object
<CustomObject>
    <description>Meta data about Adjustment and Payment Transactions</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipName>Payment_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment / Adjustment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments / Adjustments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Adjustment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Adjustment</label>
        <referenceTo>Payment_Adjustments__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TxnAggregationUtils.cls
/**
 * Utility methods for aggregating transactions for Services, Adjustments & Payments
 */

public with sharing class TxnAggregationUtils {

    private static String TOTAL = 'Total';
    private static String OBJ = 'obj';

    /**
     * update each of the given services with the sum of its tranaction's amounts
     */
    public static void aggregateServiceTxns(Set<Id> serviceIds) {

        if (serviceIds.size() > 0) {

            // Get the SUM of the associated transaction amounts
            AggregateResult[] results = [
                    SELECT Service__c obj, SUM(Amount__c) Total
                    FROM Transaction__c
                    WHERE Service__c IN :serviceIds
                    GROUP BY Service__c
            ];

            if (results.size() > 0) {
                updateServices(results);
            }
        }
    }

    private static void updateServices(AggregateResult[] results) {
        List<Service__c> services = new List<Service__c>();

        for (AggregateResult ar : results) {
            System.debug('svcId: ' + ar.get(OBJ));
            System.debug('serviceTotal: ' + ar.get(TOTAL));
            Service__c svc = new Service__c(Id=(Id) ar.get(OBJ));
            svc.Amount__c = (Decimal) ar.get(TOTAL);
            services.add(svc);
        }

        // Update the database
        if (services.size() > 0) {
            update services;
        }
    }

    public static void aggregateAdjTxns(Set<Id> adjIds) {

        if (adjIds.size() > 0) {

            // Get the SUM of the associated transaction amounts
            AggregateResult[] results = [
                    SELECT Adjustment__c obj, SUM(Amount__c) Total
                    FROM Transaction__c
                    WHERE Adjustment__c IN :adjIds
                    GROUP BY Adjustment__c
            ];

            if (results.size() > 0) {
                updateAdjustments(results);
            }
        }
    }

    private static void updateAdjustments(AggregateResult[] results) {
        List<Payment_Adjustments__c> adjs = new List<Payment_Adjustments__c>();

        for (AggregateResult ar : results) {
            System.debug('adjId: ' + ar.get(OBJ));
            System.debug('adjTotal: ' + ar.get(TOTAL));
            Payment_Adjustments__c adj = new Payment_Adjustments__c(Id=(Id) ar.get(OBJ));
            adj.Amount__c = (Decimal) ar.get(TOTAL);
            adjs.add(adj);
        }

        // Update the database
        if (adjs.size() > 0) {
            update adjs;
        }
    }
}