src/objects/Campaign_Member_History__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Member Histories</relationshipLabel>
        <relationshipName>Campaign_Member_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Member Histories</relationshipLabel>
        <relationshipName>Campaign_Member_Histories</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_Removed__c</fullName>
        <label>Date Removed</label>
        <type>Date</type>
    </fields>
    <label>Campaign Member History</label>
    <nameField>
        <displayFormat>H-{00000000}</displayFormat>
        <label>Campaign Member History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Member Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CMHSecurityContext.cls
/**
 * This class is use for Security Context of Campaign Member History object
 **/

public with sharing class CMHSecurityContext extends SecurityContext {

    // Field constants for Campaign_Member_History__c object
    private static final String CAMPAIGN = 'Campaign__c';
    private static final String CASE_ID = 'Case_ID__c';
    private static final String CONTACT = 'Contact__c';
    private static final String DATE_REMOVED = 'Date_Removed__c';

    // Below field(s) are use for Select/Read permission.
    private static final String CREATEDDATE = 'CreatedDate';
    private static final String ID = 'Id';
    private static final String NAME = 'Name';

    // The fields for inserting a CampaignMemberHistory in Campaign Member Trigger Handler
    private static final Set<String> CREATE_FIELDS = new Set<String>{
    	CAMPAIGN, CASE_ID, CONTACT
    };
    
    // The fields for updating a CampaignMemberHistory in Campaign Member Trigger Handler
    private static final Set<String> UPDATE_FIELDS = new Set<String>{
        DATE_REMOVED
    };

    // The fields for selecting a CampaignMemberHistory in CampaignMemberTriggerHandler
    private static final Set<String> SELECT_FIELDS = new Set<String>{
        CAMPAIGN, CONTACT, CREATEDDATE, DATE_REMOVED, ID, NAME
    };

    // The fields for selecting a CampaignMemberHistory in TaskTriggerHandler
    private static final Set<String> TTH_SELECT_FIELDS = new Set<String>{
        CAMPAIGN, CASE_ID, CONTACT, ID
    };

    /**
     * Constructor of class that assign variables based on parameters
     *
     * @param Set<String> fields - That contains Object's Fields
     * @param ACTION actionToPerform - That contains Action Name (Create/Update/Delete/Undelete)
     **/
    private CMHSecurityContext(Set<String> fields, ACTION actionToPerform) {
        this.fieldsToCheck = fields;
        this.objectAction = actionToPerform;
    }

    /**
     * The create context for CampaignMemberHistory in CampaignMemberTriggerHandler & CaseUtil
     **/
    public static final CMHSecurityContext CREATE_CONTEXT = new CMHSecurityContext(CREATE_FIELDS, ACTION.OBJ_CREATE);

    /**
     * The update context for CampaignMemberHistory in CampaignMemberTriggerHandler
     **/
    public static final CMHSecurityContext UPDATE_CONTEXT = new CMHSecurityContext(UPDATE_FIELDS, ACTION.OBJ_UPDATE);

    /**
     * The delete context for CampaignMemberHistory in CampaignMemberTriggerHandler
     **/
    public static final CMHSecurityContext DELETE_CONTEXT = new CMHSecurityContext(null, ACTION.OBJ_DELETE);

    /**
     * The select context for CampaignMemberHistory in CampaignMemberTriggerHandler
     **/
    public static final CMHSecurityContext SELECT_CONTEXT = new CMHSecurityContext(SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * The select context for CampaignMemberHistory in TaskTriggerHandler
     **/
    public static final CMHSecurityContext TTH_SELECT_CONTEXT = new CMHSecurityContext(TTH_SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * Override getObjectType method of SecurityContext class
     **/
    public override System.Type getObjectType() {
        return Campaign_Member_History__c.class;
    }
}