src/objects/Case_Charge_Group__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Charge Group</label>
    <nameField>
        <displayFormat>CCG-{000000}</displayFormat>
        <label>Case Charge Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case_Charge_Group_Junction__c.object
<CustomObject>
    <fields>
        <fullName>Case__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Case Charge Groups</relationshipLabel>
        <relationshipName>Case_Charge_Groups</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Case Charge Group Junction</label>
    <nameField>
        <displayFormat>CCG-{000000}</displayFormat>
        <label>Case Charge Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Charge Group Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>ChargeGroupStatus.preinvoiced</description>
        <label>Account Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Sub_Status__c</fullName>
        <label>Account Sub Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Has_Error__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Error in plan</description>
        <label>Has Error</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Sirono_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Sirono Settings New</label>
</CustomObject>

src/classes/PaymentPlanProcessBuilderFlowTest.cls
/**
 * Created by swells on 6/26/2017.
 */

@IsTest
public class PaymentPlanProcessBuilderFlowTest {
    private static final Integer NUM_CHARGE_GROUPS = 2;

    @TestSetup
    private static void setup() {
        SironoSettingsUtil.setProcessBuilderIds(Sirono_Settings__c.getInstance());
    }

    private static Contact createPaymentPlanPrereqs() {
        Contact guarantor = TestUtility.generateGuarantorContact();
        guarantor.Profile_Pointer_ID__c = 100.0;
        insert guarantor;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        List<Charge_Group__c> chargeGroups = new List<Charge_Group__c>();
        for (Integer i = 0; i < NUM_CHARGE_GROUPS; i++) {
            Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(
                guarantor.Id,
                patientContact.Id,
                200.0
            );
            chargeGroup.Account_Status__c = Constants.ACCT_STATUS_BILLED;
            chargeGroup.Account_Sub_Status__c = Constants.ACCT_SUBSTATUS_PAYMENT_PLAN;
            chargeGroups.add(chargeGroup);
        }
        insert chargeGroups;

        return guarantor;
    }

    private static void verifyPaymentPlanWithErrorsResults() {
        List<Case> cases = [
            SELECT Id, Type, (
                SELECT Id, Charge_Group__r.Account_Status__c, Charge_Group__r.Account_Sub_Status__c
                FROM Case_Charge_Groups__r
            )
            FROM Case
            WHERE Subject = 'Payment Plan Error'
        ];

        // Verify the cases
        System.assertEquals(1, cases.size());
        System.assertEquals(Constants.CASE_TYPE_PAYMENT_PLAN_ERROR, cases[0].Type);

        // Verify the case/charge groups
        List<Case_Charge_Group_Junction__c> caseChargeGroupJunctions = cases[0].Case_Charge_Groups__r;
        System.assertEquals(NUM_CHARGE_GROUPS, caseChargeGroupJunctions.size());
        for (Case_Charge_Group_Junction__c caseChargeGroupJunction : caseChargeGroupJunctions) {
            System.assertEquals(Constants.ACCT_STATUS_BILLED, caseChargeGroupJunction.Charge_Group__r.Account_Status__c);
            System.assertEquals(Constants.ACCT_SUBSTATUS_PAYMENT_PLAN, caseChargeGroupJunction.Charge_Group__r.Account_Sub_Status__c);
        }
    }

    private static void verifyPaymentPlanNoErrorsResults() {
        List<Case> cases = [
            SELECT Id, Type, (
                SELECT Id, Charge_Group__r.Account_Status__c, Charge_Group__r.Account_Sub_Status__c
                FROM Case_Charge_Groups__r
            )
            FROM Case
            WHERE Subject = 'Payment Plan Error'
        ];

        // There should be no matches
        System.assert(cases.isEmpty());
    }

    @IsTest
    private static void testPaymentPlanCreatedWithErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Test.startTest();
        {
            Payment_Plan__c paymentPlan = new Payment_Plan__c(
                Guarantor__c = guarantor.Id,
                Has_Error__c = true
            );
            insert paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanCreatedNoErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Test.startTest();
        {
            Payment_Plan__c paymentPlan = new Payment_Plan__c(
                Guarantor__c = guarantor.Id,
                Has_Error__c = false
            );
            insert paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanNoErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanUpdatedWithErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Payment_Plan__c paymentPlan = new Payment_Plan__c(
            Guarantor__c = guarantor.Id,
            Has_Error__c = false
        );
        insert paymentPlan;

        Test.startTest();
        {
            paymentPlan.Has_Error__c = true;
            update paymentPlan;
        }
        Test.stopTest();

        verifyPaymentPlanWithErrorsResults();
    }

    @IsTest
    private static void testPaymentPlanUpdatedNoErrors() {
        Contact guarantor = createPaymentPlanPrereqs();

        Payment_Plan__c paymentPlan = new Payment_Plan__c(
            Guarantor__c = guarantor.Id,
            Has_Error__c = true
        );
        insert paymentPlan;

        // TODO: Delete the case that was created above to simulate case closure
        List<Case> cases = [SELECT Id, Type FROM Case WHERE Subject = 'Payment Plan Error'];
        System.assertEquals(1, cases.size());
        System.assertEquals(Constants.CASE_TYPE_PAYMENT_PLAN_ERROR, cases[0].Type);
        delete cases;

        Test.startTest();
        {
            // And update the payment plan not to have
            paymentPlan.Has_Error__c = false;
            update paymentPlan;
        }
        Test.stopTest();

        // TODO: Case closure should have removed the case above when the errors were cleared
        verifyPaymentPlanNoErrorsResults();
    }
}