src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Service__c</fullName>
        <label>Date of Service</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_Portion__c</fullName>
        <formula>Total_Charges__c - Insurance_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Patient Portion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Arrangement__c.object
<CustomObject>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payment Arrangements</relationshipLabel>
        <relationshipName>Payment_Arrangements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Arrangement</label>
    <nameField>
        <displayFormat>pa-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Arrangements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentArrangementTriggerHandler.cls
//Mohan Kumar 2016-08-18: On Create of Payment Arrangement auto close any open Encounter Case existing
public with sharing class PaymentArrangementTriggerHandler {

    public static void closeEncounterCaseFromPaymentArrangement(List<Payment_Arrangement__c> newList) {
        Set<Id> encounterIds = new Set<Id>();
        for (Payment_Arrangement__c pa : newList) {
            if (pa.Encounter__c != null) encounterIds.add(pa.Encounter__c);
        }
        List<Encounter__c> encounterList = [
                Select Id, Cancelled__c, Date_of_Service__c, Patient_Portion__c, Guarantor__c
                From Encounter__c
                Where Id IN :encounterIds
        ];
        CaseUtil.CallCloseEncounterAutoCase(encounterList, true);
    }
}