src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Guarantor_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Guarantor record.  Set via the manual cases flow to be the first chargegroup&apos;s guarantor.</description>
        <label>Guarantor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Cases (Guarantor)</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Delinquent_Balance__c</fullName>
        <label>Delinquent Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Delinquent_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overdue_Balance__c</fullName>
        <label>Overdue Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Overdue_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sirono_Call_Center_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration for Sirono Call Center application.</description>
    <fields>
        <fullName>Auto_Create_Overdue_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for statements with overdue balances.</description>
        <inlineHelpText>When enabled, cases are automatically created for statements with overdue balances.</inlineHelpText>
        <label>Auto Create Overdue Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Create_Precollection_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for statements with delinquent balances.</description>
        <inlineHelpText>When enabled, cases are automatically created for statements with delinquent balances.</inlineHelpText>
        <label>Auto Create Precollection Cases</label>
        <type>Checkbox</type>
    </fields>
    <label>Sirono Call Center Settings</label>
</CustomObject>

src/objects/Statement__c.object
<CustomObject>
    <description>Guarantor Statement details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/StatementTriggerHandler.cls
/**
 * Created by swells on 6/26/2017.
 */

public with sharing class StatementTriggerHandler {
    public static void afterInsert(List<Statement__c> statements) {
        checkOverdueBalance(statements);
        checkDelinquentBalance(statements);
    }

    private static void checkOverdueBalance(List<Statement__c> statements) {
        // Only if we're configured to auto-create overdue cases
        Sirono_Call_Center_Settings__c sironoCallCenterSettings = SironoCallCenterSettingsUtil.getSironoCallCenterSettings();
        if (!sironoCallCenterSettings.Auto_Create_Overdue_Cases__c) {
            return;
        }

        // Group for efficiency
        Set<Id> guarantorIds = new Set<Id>();
        for (Statement__c statement : statements) {
            guarantorIds.add(statement.Guarantor__c);
        }

        if (!guarantorIds.isEmpty()) {
            if (ContactSecurityContext.SELECT_CONTEXT.actionAllowed()) {
                List<Contact> guarantors = [
                    SELECT Id, Overdue_Balance__c
                    FROM Contact
                    WHERE Id IN :guarantorIds
                    AND Overdue_Balance__c > 0.0
                ];

                List<Case> overdueBalanceCases = new List<Case>();
                for (Contact guarantor : guarantors) {
                    Case overdueBalanceCase = new Case(
                        ContactId = guarantor.Id,
                        Guarantor_Information__c = guarantor.Id,
                        RecordTypeId = RecordTypeUtil.automatedCaseRt,
                        Status = Constants.CASE_STATUS_NEW,
                        Subject = Constants.CASE_SUBJECT_GUARANTOR_OVERDUE,
                        Type = Constants.CASE_TYPE_OVERDUE
                    );
                    overdueBalanceCases.add(overdueBalanceCase);
                }

                if (CaseSecurityContext.CREATE_CONTEXT.actionAllowed()) {
                    if (!overdueBalanceCases.isEmpty()) {
                        insert overdueBalanceCases;
                    }
                }
            }
        }
    }

    private static void checkDelinquentBalance(List<Statement__c> statements) {
        // Only if we're configured to auto-create delinquent cases
        Sirono_Call_Center_Settings__c sironoCallCenterSettings = SironoCallCenterSettingsUtil.getSironoCallCenterSettings();
        if (!sironoCallCenterSettings.Auto_Create_Precollection_Cases__c) {
            return;
        }

        // Group for efficiency
        Set<Id> guarantorIds = new Set<Id>();
        for (Statement__c statement : statements) {
            guarantorIds.add(statement.Guarantor__c);
        }

        if (!guarantorIds.isEmpty()) {
            if (ContactSecurityContext.SELECT_CONTEXT.actionAllowed()) {
                List<Contact> guarantors = [
                    SELECT Id, Delinquent_Balance__c
                    FROM Contact
                    WHERE Id IN :guarantorIds
                    AND Delinquent_Balance__c > 0.0
                ];

                List<Case> delinquentBalanceCases = new List<Case>();
                for (Contact guarantor : guarantors) {
                    Case delinquentBalanceCase = new Case(
                        ContactId = guarantor.Id,
                        Guarantor_Information__c = guarantor.Id,
                        RecordTypeId = RecordTypeUtil.automatedCaseRt,
                        Status = Constants.CASE_STATUS_NEW,
                        Subject = Constants.CASE_SUBJECT_GUARANTOR_DELINQUENT,
                        Type = Constants.CASE_TYPE_PRECOLLECTIONS
                    );
                    delinquentBalanceCases.add(delinquentBalanceCase);
                }

                if (CaseSecurityContext.CREATE_CONTEXT.actionAllowed()) {
                    if (!delinquentBalanceCases.isEmpty()) {
                        insert delinquentBalanceCases;
                    }
                }
            }
        }
    }
}