src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <description>Equals Sirono Ticket number</description>
        <externalId>true</externalId>
        <label>ID</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Account_Status__c</fullName>
        <description>ChargeGroupStatus.preinvoiced</description>
        <label>Account Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Sub_Status__c</fullName>
        <label>Account Sub Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Charge_Group_External_ID__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used for integration</description>
        <label>Charge Group External ID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>cannot delete</description>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Reported_Selfpay_Balance__c</fullName>
        <label>Reported Selfpay Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>external notes from Sirono</description>
        <label>Notes</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <label>Credit Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Credit_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor_Name__c</fullName>
        <formula>Patient__r.Guarantor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Guarantor Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient_Portion__c</fullName>
        <formula>Total_Charges__c - Insurance_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Patient Portion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Arrangement__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payment Arrangements</relationshipLabel>
        <relationshipName>Payment_Arrangements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Arrangement</label>
    <nameField>
        <displayFormat>pa-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Arrangements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Statement__c.object
<CustomObject>
    <description>Guarantor Statement details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statement_Date__c</fullName>
        <description>Date of the statement</description>
        <label>Statement Date</label>
        <type>Date</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Balance (Deprecated)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Export_Date__c</fullName>
        <label>Export Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fail_Date__c</fullName>
        <description>Fail Date</description>
        <label>Fail Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method (Deprecated)</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes (Deprecated)</label>
        <type>TextArea</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestClassUtil.cls
/*
Test class for Auto Case functionality
*/
@isTest
public class TestClassUtil {
    Public Static Set<String> SetContact = new Set<String>();
    Public Static List<Statement__c> lstStatement = new List<Statement__c>();
    @testSetup static void setupData() {
        Map<String, Id> rtMap = new Map<String, Id>();
        for (RecordType rt : [Select Id, Name From RecordType Where sObjectType = 'Contact']) {
            rtMap.put(rt.Name, rt.Id);
        }


        Contact g = new Contact();
        g.RecordTypeId = rtMap.get('Guarantor');
        g.LastName = 'G Test';
        g.Profile_Pointer_Id__c = 12345;
        g.HomePhone = '111';
        g.MobilePhone = '111';
        insert g;

        Contact g1 = new Contact();
        g1.RecordTypeId = rtMap.get('Guarantor');
        g1.LastName = 'G Test1';
        g1.Profile_Pointer_Id__c = 123451;
        g1.HomePhone = '1111';
        g1.MobilePhone = '1111';
        insert g1;

        SetContact.Add(g1.Id);

        Statement__c stmt = new Statement__c();
        stmt.Statement_Date__c = System.Today();
        stmt.Guarantor__c = g.Id;
        insert stmt;

        stmt = new Statement__c();
        stmt.Statement_Date__c = System.Today();
        stmt.Guarantor__c = g.Id;
        lstStatement.add(stmt);


        stmt = new Statement__c();
        stmt.Statement_Date__c = System.Today();
        stmt.Guarantor__c = g1.Id;
        lstStatement.add(stmt);
        insert lstStatement;

        List<Campaign> lst = new List<Campaign>();
        Campaign objCampaign = New Campaign();
        objCampaign.Name = 'Early Out';
        objCampaign.IsActive = True;
        lst.add(objCampaign);

        objCampaign = New Campaign();
        objCampaign.Name = 'Early Out - Mobile';
        objCampaign.IsActive = True;
        lst.add(objCampaign);

        objCampaign = New Campaign();
        objCampaign.Name = 'Pre-collections';
        objCampaign.IsActive = True;
        lst.add(objCampaign);

        objCampaign = New Campaign();
        objCampaign.Name = 'Pre-collections - Mobile';
        objCampaign.IsActive = True;
        lst.add(objCampaign);

        objCampaign = New Campaign();
        objCampaign.Name = 'Pre-Service';
        objCampaign.IsActive = True;
        lst.add(objCampaign);

        objCampaign = New Campaign();
        objCampaign.Name = 'Pre-Service - Mobile';
        objCampaign.IsActive = True;
        lst.add(objCampaign);

        insert lst;

        Charge_Group__c cg = new Charge_Group__c();
        cg.Guarantor_Name__c = g.Id;
        cg.Charge_Group_ID__c = 123;
        cg.Charge_Group_External_ID__c = true;
        cg.Reported_Selfpay_Balance__c = 10;
        cg.Account_Status__c = 'Billed';
        cg.Account_Sub_Status__c = 'Overdue';
        insert cg;

        Transaction__c t = new Transaction__c();
        t.Amount__c = -100;
        t.Charge_Group__c = cg.Id;
        t.Credit_Balance__c = false;
        t.Export_Date__c = System.today();
        t.Fail_Date__c = null;
        t.Id__c = 123;
        t.Method__c = 'Service';
        t.Notes__c = 'Test';
        insert t;

        cg = new Charge_Group__c();
        cg.Guarantor_Name__c = g1.Id;
        cg.Charge_Group_ID__c = 1232323;
        cg.Charge_Group_External_ID__c = true;
        cg.Reported_Selfpay_Balance__c = 10;
        cg.Account_Status__c = 'Billed';
        cg.Account_Sub_Status__c = 'Overdue';
        insert cg;

        Encounter__c e1 = TestUtility.createEncounter(g.Id, -10, Date.today());
        insert e1;

        Encounter__c e2 = TestUtility.createEncounter(g.Id, -10, Date.today());
        insert e2;

        e1.Patient_Portion__c = 0;
        update e1;

        Payment_Arrangement__c pa = TestUtility.createPaymentArrangement(e2.Id);
        insert pa;

        //Test coverage for Auto case to manually closing the case [CaseTriggerHandler.removeCampaignMembers method]
        CaseUtil.ExecuteRemoveCampaignTrigger = true;
        Map<String, Id> caseRTMap = new Map<String, Id>();
        for (RecordType rt : [Select Id, Name From RecordType Where sObjectType = 'Case']) {
            caseRTMap.put(rt.Name, rt.Id);
        }

        List<Case> caseList = new List<Case>();
        Case c = TestUtility.createCase(caseRTMap.get('Automated Cases'), 'Early Out', g.Id);
        caseList.add(c);
        c = TestUtility.createCase(caseRTMap.get('Automated Cases'), 'Precollections', g.Id);
        caseList.add(c);
        c = TestUtility.createCase(caseRTMap.get('Automated Cases'), 'Encounter', g.Id);
        caseList.add(c);
        insert caseList;

        for (Case obj : caseList) {
            obj.Status = 'Closed';
        }
        update caseList;
    }
    @isTest public static void testCallEarlyOutAutoCase() {
        CaseUtil.CallEarlyOutAutoCase();
        CaseUtil.CallEarlyOutAutoCaseCloser();
        CaseUtil.CallCloseEarlyOutAutoCase(lstStatement);
    }

    @isTest public static void testCallPrecollectionsAutoCase() {
        CaseUtil.CallPrecollectionsAutoCaseCloser();
        CaseUtil.CallPrecollectionsAutoCase();

    }
    @isTest public static void testCloseEarlyOutAutoCase() {

        CaseUtil.CloseEarlyOutAutoCase(SetContact);

    }
}