src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Plan Number type small int</description>
        <label>Plan Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Value_Modified_Date__c</fullName>
        <description>time stamp of plan modification</description>
        <label>Plan Value Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChargeGroupServiceTest.cls
@isTest
public with sharing class ChargeGroupServiceTest {

    @isTest
    public static void testRetrieveBySironoId() {

    }

    @isTest
    public static void testGetSironoIds() {
        Decimal cgOneSironoId = 54321;
        Decimal cgTwoSironoId = 12345;

        Contact gt = TestUtility.generateGuarantorContact();
        gt.Profile_Pointer_ID__c = 23232323;
        INSERT gt;

        Contact pt = TestUtility.generatePatientContact();
        INSERT pt;

        Datetime createdDT = Datetime.now().addDays(-3);

        Payment_Plan__c pp = TestUtility.generatePaymentPlan(gt);
        pp.Plan_Type__c = Constants.AUTOMATIC;
        pp.Sirono_ID__c = 33556677;
        pp.Plan_Value_Modified_Date__c = createdDT;
        INSERT pp;
        Test.setCreatedDate(pp.Id, createdDT);

        List<Charge_Group__c> cgs = new List<Charge_Group__c>();
        cgs.add(TestUtility.generateChargeGroup(gt.Id, pt.Id, cgOneSironoId, pp.id));
        cgs.get(0).Sirono_ID__c = cgOneSironoId;
        cgs.add(TestUtility.generateChargeGroup(gt.Id, pt.Id, cgTwoSironoId, pp.id));
        cgs.get(1).Sirono_ID__c = cgTwoSironoId;

        INSERT cgs;

        Test.startTest();
        List<Decimal> sironoIds = ChargeGroupService.getSironoIds(cgs);
        Test.stopTest();

        System.assertEquals(2, sironoIds.size(), 'Should have the two ids.');
        Set<Decimal> sironoIdSet = new Set<Decimal>(sironoIds);
        System.assert(sironoIdSet.contains(cgOneSironoId), 'Should have the first cgSironoId.');
        System.assert(sironoIdSet.contains(cgTwoSironoId), 'Should have the second cgSironoId.');

    }

}