src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Pre_Collection_Sent__c</fullName>
        <description>Date pre-collections notice was sent (if applicable).</description>
        <label>Pre Collection Sent</label>
        <type>Date</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Guarantor_Name__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payable_Amount__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChargeGroupTriggerTest.cls
/*
 * @author Sirono
 * @version 1.0.1
 * @Date: 09-02-2016
 * Test class for the ChargeGroupTriggerHandler
 */

@isTest
public class ChargeGroupTriggerTest {

    public static @isTest void main() {
    Contact con = TestUtility.generatePatientContact();
    insert con;
    Contact cont = TestUtility.generateGuarantorContact();
    insert cont;
    Contact c = new Contact(LastName = 'Matc');
    insert c;
    test__c pp = TestUtility.generatePaymentPlan(c.Id);
    insert pp;
    Charge_Group__c cg = TestUtility.generateChargeGroup(cont.Id, con.Id, 100.0, pp.id);
    insert cg;

    Charge_Group__c cg1 = [Select id from Charge_Group__c where name = 'Sirono'];
    cg1.name = 'Sir';
    Update cg1;
    System.assertEquals('Sir', cg1.Name);
    delete cg1;
    undelete cg1;

    ChargeGroupTriggerHandler.getIsTriggerProcessed();
ChargeGroupTriggerHandler.setIsTriggerProcessed(true);

List<ApexPages.Message> msgList = ApexPages.getMessages();
System.assertEquals(0, msgList.size());
}

public static @isTest void afterUpdate() {
Contact con = TestUtility.generatePatientContact();
insert con;

Contact cont = TestUtility.generateGuarantorContact();
insert cont;

Contact c = new Contact(LastName='Matc');
insert c;

test__c pp = TestUtility.generatePaymentPlan(c.Id);
insert pp;

Charge_Group__c cg = TestUtility.generateChargeGroup(cont.Id, con.Id, 100.0,pp.id);
insert cg;
cg.Pre_Collection_Sent__c = null;
cg.Guarantor_Name__c =c.Id;

List<test__c> lst = [Select id, Payable_Amount__c from test__c where id =: pp.Id];
System.assertEquals(0, lst[0].Payable_Amount__c) ;

Transaction__c transactionObj = TestUtility.generateTransaction(cg, 100, 'Automatic');
insert transactionObj ;

Update cg;

lst = [Select id, Payable_Amount__c from test__c where id =: pp.Id];
System.assertEquals(100, lst[0].Payable_Amount__c) ;

}

}