src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if active account</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Charge_Group_External_ID__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used for integration</description>
        <label>Charge Group External ID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Participant is past due</description>
        <label>Delinquent</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Participant is past due</description>
        <label>Delinquent</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateAdjustmentTest.cls
/*
* @author Sirono
* @version 1.0.1
* @Date: 05-12-2016
* @ Unit class  for the CreateAdjustment class.     
* Do the code coverage for the CreateAdjustment class with TestUtil method.
*/

@isTest
private class CreateAdjustmentTest {

//    static testMethod void myUnitTest() {
//        TestUtility objUtility = new TestUtility();
//
//        Contact guarantorContact = TestUtility.generateGuarantorContact();
//        insert guarantorContact;
//
//        Contact patientContact = TestUtility.generatePatientContact();
//        insert patientContact;
//
//        test__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.id);
//        paymentPlan.active__c = true;
//        paymentPlan.Delinquent__c = true;
//        insert paymentPlan;
//
//        CreateAdjustment objCreateAdjustment = new CreateAdjustment(new ApexPages.StandardController(guarantorContact));
//        objCreateAdjustment.submit();
//
//        Invoice__c invoice = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
//        insert invoice;
//
//        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 121114);
//        chargeGroup.Invoice__c = invoice.id;
//        chargeGroup.Payment_Plan__c = paymentPlan.Id;
//        chargeGroup.Charge_Group_External_ID__c = true;
//        insert chargeGroup;
//
//        chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 121114);
//        chargeGroup.Invoice__c = invoice.id;
//        chargeGroup.Payment_Plan__c = paymentPlan.Id;
//        chargeGroup.Charge_Group_ID__c = 124;
//        chargeGroup.Charge_Group_External_ID__c = true;
//        insert chargeGroup;
//
//        objCreateAdjustment = new CreateAdjustment(new ApexPages.StandardController(guarantorContact));
//        for (ChargeGroupWrapper objChargeGroupWrapper : objCreateAdjustment.chrageGroupList) {
//            objChargeGroupWrapper.isSelected = true;
//        }
//        objCreateAdjustment.doNext();
//        objCreateAdjustment.adjustmentTypeSelected = 'DIS';
//        objCreateAdjustment.submit();
//
//        List<ApexPages.Message> msgList = ApexPages.getMessages();
//        System.assertEquals(2, msgList.size());
//    }
//
//    //Coverage the code for the Endpoint Request method.
//    static testMethod void callEndpointRequestMethod() {
//        TestUtility objUtility = new TestUtility();
//
//        Contact guarantorContact = TestUtility.generateGuarantorContact();
//        insert guarantorContact;
//
//        Contact patientContact = TestUtility.generatePatientContact();
//        insert patientContact;
//
//        test__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.id);
//        paymentPlan.active__c = true;
//        paymentPlan.Delinquent__c = true;
//        insert paymentPlan;
//
//        CreateAdjustment objCreateAdjustment = new CreateAdjustment(new ApexPages.StandardController(guarantorContact));
//
//        Invoice__c invoice = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
//        insert invoice;
//
//        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 121114);
//        chargeGroup.Invoice__c = invoice.id;
//        chargeGroup.Payment_Plan__c = paymentPlan.Id;
//        chargeGroup.Charge_Group_External_ID__c = true;
//        insert chargeGroup;
//
//        chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, null, 121114);
//        chargeGroup.Invoice__c = invoice.id;
//        chargeGroup.Payment_Plan__c = paymentPlan.Id;
//        chargeGroup.Charge_Group_ID__c = 124;
//        chargeGroup.Charge_Group_External_ID__c = true;
//        insert chargeGroup;
//
//        objCreateAdjustment = new CreateAdjustment(new ApexPages.StandardController(guarantorContact));
//        for (ChargeGroupWrapper objChargeGroupWrapper : objCreateAdjustment.chrageGroupList) {
//            objChargeGroupWrapper.isSelected = true;
//            objCreateAdjustment.chargegroupId = objChargeGroupWrapper.cg.ID;
//        }
//        objCreateAdjustment.amount = '10';
//        objCreateAdjustment.adjustmentTypeSelected = 'Auto';
//        objCreateAdjustment.doNext();
//        objCreateAdjustment.adjustmentTypeSelected = 'DIS';
//        objCreateAdjustment.submit();
//        List<ApexPages.Message> msgList = ApexPages.getMessages();
//        System.assertEquals(2, msgList.size());
//    }
//
//    //Coverage the code for the Endpoint Request method.
//    static testMethod void submit() {
//        TestUtility objTestUtility = new TestUtility();
//
//        Contact g = TestUtility.generateguarantorContact();
//        insert g;
//
//        Contact p = TestUtility.generatePatientContact();
//        insert p;
//
//        test__c t = TestUtility.generatePaymentPlan(g.Id);
//        t.Active__c = true;
//        insert t;
//
//        Apexpages.currentPage().getParameters().put('guarantorId', g.Id);
//        Apexpages.currentPage().getParameters().put('paymentPlanExtId', '121212');
//        CreateAdjustment objCreateAdjustment = new CreateAdjustment(new ApexPages.StandardController(g));
//        objCreateAdjustment.submit();
//
//        Invoice__c i = TestUtility.generateInvoice(g.Id, p.Id);
//        insert i;
//
//        Charge_Group__c cg = TestUtility.generateChargeGroup(g.Id, null, 121114);
//        cg.Invoice__c = i.id;
//        cg.Payment_Plan__c = t.Id;
//        cg.Charge_Group_External_ID__c = true;
//        insert cg;
//
//        Transaction__c transactionObj = TestUtility.generateTransaction(cg, 100, 'Automatic');
//        insert transactionObj;
//
//        cg = TestUtility.generateChargeGroup(g.Id, null, 121114);
//        cg.Invoice__c = i.id;
//        cg.Payment_Plan__c = t.Id;
//        cg.Charge_Group_ID__c = 124;
//        cg.Charge_Group_External_ID__c = true;
//        insert cg;
//
//
//        transactionObj = TestUtility.generateTransaction(cg, 100, 'Automatic');
//        insert transactionObj;
//
//        Apexpages.currentPage().getParameters().put('guarantorId', g.Id);
//        Apexpages.currentPage().getParameters().put('paymentPlanExtId', '121212');
//        objCreateAdjustment = new CreateAdjustment(new ApexPages.StandardController(g));
//        for (ChargeGroupWrapper cgw : objCreateAdjustment.chrageGroupList) {
//            cgw.isSelected = true;
//        }
//        objCreateAdjustment.doNext();
//
//        Test.startTest();
//        TestUtility.status = 'CREATED';
//        TestUtility.statusCode = 201;
//        objCreateAdjustment.amount = '10';
//        objCreateAdjustment.adjustmentTypeSelected = 'DIS';
//        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorTest());
//        objCreateAdjustment.submit();
//        List<ApexPages.Message> msgList = ApexPages.getMessages();
//        System.assertEquals(3, msgList.size());
//
//        Test.stopTest();
//    }
//
//    public static testMethod void testRunAs() {
//        // Setup test data
//        // This code runs as the system user
//        Profile p = [SELECT Id FROM Profile WHERE Name = 'Standard User'];
//        User u = new User(Alias = 'standt', Email = 'standarduser@testorg.com',
//                EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
//                LocaleSidKey = 'en_US', ProfileId = p.Id,
//                TimeZoneSidKey = 'America/Los_Angeles', UserName = 'standarduser@testorg1212.com');
//
//        System.runAs(u) {
//            Contact g = TestUtility.generateguarantorContact();
//            insert g;
//
//            CreateAdjustment objCreateAdjustment = new CreateAdjustment(new ApexPages.StandardController(g));
//        }
//    }
}