src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if active account</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <summarizedField>Transaction__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction__c.Charge_Group__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Age__c</fullName>
        <formula>If(ISBLANK(Invoice__c),-1,Invoice__r.Invoice_Age__c)</formula>
        <label>Invoice Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Patient)</relationshipLabel>
        <relationshipName>Charge_Groups_Patient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Add_to_Payment_Plan__c</fullName>
        <formula>AND(Payment_Plan_Balance__c &gt; 0, Payment_Plan_Balance__c &lt;&gt; Invoiced_Balance__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Add to Payment Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent_Balance__c</fullName>
        <label>Delinquent Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Delinquent_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Due_Balance__c</fullName>
        <label>Due Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Due_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoiced_Balance__c</fullName>
        <label>Invoiced Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Invoiced_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <description>Patient medical Record number</description>
        <label>Medical Record Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overdue_Balance__c</fullName>
        <label>Overdue Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Overdue_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Balance__c</fullName>
        <label>Payment Plan Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Payment_Plan_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Pre_Invoiced_Balance__c</fullName>
        <label>Pre-Invoiced Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Pre_Invoiced_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Patient of the account or case</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Guarantor)</relationshipLabel>
        <relationshipName>Guarantor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Age__c</fullName>
        <formula>TODAY() - Invoice_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <description>Invoice Date</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Partial_Payment_Plan__c</fullName>
        <formula>And(Invoice_Status_Index__c &lt;&gt; 4,CONTAINS(All_Substatus__c,&quot;Payment&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partial Payment Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>Invoice ID External</description>
        <externalId>true</externalId>
        <label>Invoice ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Invoice__c.object
    <fields>
        <fullName>Balance__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

call-center/src/objects/Invoice__c.object
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(AND(Balance__c &lt;&gt; NULL, Balance__c ==0), &quot;Paid&quot;,
CASE(Status_Index__c,
9, &quot;Delinquent&quot;,
8, &quot;Overdue&quot;,
7, &quot;Due&quot;,
6, &quot;On Payment Plan&quot;,
5, &quot;Credit&quot;,
4, &quot;Paid&quot;,
3, &quot;Paid&quot;,
2, &quot;Unknown&quot;,
1, &quot;Invoice Voided&quot;,
0, &quot;Invoice Voided&quot;,
&quot;Error&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>NextPaymentDate__c</fullName>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceDao.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Invoice DAO
 * TODO sharing model
 */
public with sharing class InvoiceDao extends AbstractDao {

  /**
   * Get an Invoice__c returned as a List with a partical status.
   *
   * @return List<Invoice__c> - A list containing the most recent Invoice if found.
   */
    public static List<Invoice__c> getByStatus(Id guarantorId, String status) {
        if (InvoiceSecurityContext.SELECT_CONTEXT.actionAllowed()) {
            return [
                SELECT
                    Id,
                    Due_Date__c
                FROM Invoice__c
                WHERE Guarantor__c = :guarantorId
                AND Status__c = :status
                ORDER BY CreatedDate
                LIMIT 1
            ];
        }
        return null;
    }

    /**
     * Get the list of Invoice__c objects for a particular invoice id.
     *
     * @param Id contanctId - The guarantor id.
     * @param String invoiceId - The invoice Id.
     * @returns List<Invoice__c> - The list of Invoice__c objects.
     */
    public static List<Invoice__c> getById(Id contactId, String invoiceId) {

        if (InvoiceSecurityContext.DETAIL_CONTEXT.actionAllowed() && ChargeGroupSecurityContext.SELECT_CONTEXT.actionAllowed()) {
            return [
                SELECT Id, Name, Balance__c, Sirono_ID__c, Invoice_Date__c, Invoice_Age__c, Status__c,
                    Due_Date__c, Partial_Payment_Plan__c,Patient__r.Name, Patient__r.Medical_Record_Number__c,
                    Guarantor__r.Overdue_Balance__c, Guarantor__r.Invoiced_Balance__c, Guarantor__r.Due_Balance__c,
                    Guarantor__r.Delinquent_Balance__c,Guarantor__r.Payment_Plan_Balance__c,
                    Guarantor__r.Add_to_Payment_Plan__c, Guarantor__r.Pre_Invoiced_Balance__c, (
                    SELECT Id, Payment_Plan__c, Payment_Plan__r.Active__c, Payment_Plan__r.Installment_Amount__c,
                        Payment_Plan__r.NextPaymentDate__c
                    FROM Charge_Groups__r
                )
                FROM Invoice__c
                WHERE Guarantor__c = :contactId AND Id = :invoiceId
            ];
        }
        return null;
    }

    /**
     * Get the list of Invoice__c object for a particular user.
     *
     * @param Id userId - The Guarantor id associated with the invoices.
     * @param Set<String> statuses - An optional set of invoice statuses to filter the result.
     * @param List<String> patients - An optional list of Patient ids used to limit the query.
     * @returns List<Invoice__C> - The list of invoices.
     */
    public static List<Invoice__c> getInvoicesForUser(Id userId, Set<String> statuses, List<String> patients) {
        // TODO FLS/CRUD
        String query = 'SELECT Id, Name, Balance__c, Patient__r.Name, Patient__r.Medical_Record_Number__c, Sirono_ID__c, Invoice_Date__c, Invoice_Age__c, Status__c, ' +
            'Due_Date__c, Guarantor__r.Overdue_Balance__c, Guarantor__r.Add_to_Payment_Plan__c, Guarantor__r.Invoiced_Balance__c, ' +
            'Guarantor__r.Due_Balance__c, Guarantor__r.Delinquent_Balance__c, Partial_Payment_Plan__c, ' +
            'Guarantor__r.Payment_Plan_Balance__c, Guarantor__r.Pre_Invoiced_Balance__c, ' +
            '(SELECT Id, Payment_Plan__c, Payment_Plan__r.Active__c, Payment_Plan__r.Installment_Amount__c, ' +
            'Payment_Plan__r.NextPaymentDate__c FROM Charge_Groups__r) ' +
            'FROM Invoice__c WHERE Guarantor__c = :userId';

        if (patients != null && patients.size() > 0) {
            query += ' AND Patient__c IN :patients';
        }

        if (statuses != null && statuses.size() != 0) {
            query += ' AND Status__c in :statuses';
        }

        // Add order by clause
        query += ' ORDER BY Invoice_Date__c DESC';

        return Database.query(query);
    }

    /**
     * Get the list of Invoices with patient information for a user.
     *
     * @param Id userId - The user id.
     * @returns List<Invoice__c> The list of invoices for the user.
     */
    public static List<Invoice__c> getPatientInvoices(Id userId) {
        // TODO: FLS CRUD
        return [
            SELECT
                Patient__r.Medical_Record_Number__c,
                Patient__r.Name
            FROM Invoice__c
            WHERE Guarantor__c = :userId
            LIMIT 50000
        ];
    }

}