src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AddDiscountTest.cls
/*
* @author Sirono
* @version 1.0.1
* @Date: 05-16-2016
* @AddDiscount Test Class for the Code Covrege of Add Discount Class.
*/

@isTest
private class AddDiscountTest {

    static testMethod void myUnitTest() {
        TestUtility objTestUtility = new TestUtility();

        Contact guarantorContact = TestUtility.generateguarantorContact();
        insert guarantorContact ;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        test__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
        insert paymentPlan;

        AddDiscount objAddDiscount = new AddDiscount(new ApexPages.StandardController(guarantorContact));
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        Invoice__c invoice = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
        insert invoice;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 123);
        chargeGroup.Charge_Group_ID__c = 123;
        insert chargeGroup;

        Transaction__c transactionObj = TestUtility.generateTransaction(chargeGroup, 100, 'Automatic');
        insert transactionObj;

        chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 124);
        chargeGroup.Charge_Group_ID__c = 124;
        insert chargeGroup;

        objAddDiscount = new AddDiscount(new ApexPages.StandardController(guarantorContact));
        for (ChargeGroupWrapper cgw :objAddDiscount.chargeGroupList) {
            cgw.isSelected = true;
        }
        objAddDiscount.doNext();
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorTest());
        objAddDiscount.submit();
        msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size());
        Test.stopTest();
    }

    static testMethod void submit() {
        TestUtility objTestUtility = new TestUtility();

        Contact guarantorContact = TestUtility.generateguarantorContact();
        insert guarantorContact ;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        test__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
        insert paymentPlan;

        AddDiscount objAddDiscount = new AddDiscount(new ApexPages.StandardController(guarantorContact));
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorTest());
        objAddDiscount.submit();
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(2, msgList.size());
        Test.stopTest();
    }

    static testMethod void exception() {
        TestUtility objTestUtility = new TestUtility();

        Contact guarantorContact = TestUtility.generateguarantorContact();
        insert guarantorContact ;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        test__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
        insert paymentPlan;

        AddDiscount objAddDiscount = new AddDiscount(new ApexPages.StandardController(guarantorContact));
        objAddDiscount.submit();
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(2, msgList.size());


        Invoice__c invoice = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
        insert invoice;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 123);
        chargeGroup.Charge_Group_ID__c = 123;
        insert chargeGroup;

        Transaction__c transactionObj = TestUtility.generateTransaction(chargeGroup, 100, 'Automatic');
        insert transactionObj;

        chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 124);
        chargeGroup.Charge_Group_ID__c = 124;
        insert chargeGroup;

        objAddDiscount = new AddDiscount(new ApexPages.StandardController(guarantorContact));
        for (ChargeGroupWrapper cgw :objAddDiscount.chargeGroupList) {
            cgw.isSelected = true;
        }
        objAddDiscount.doNext();
        objAddDiscount.submit();
        msgList = ApexPages.getMessages();
        System.assertEquals(4, msgList.size());
    }

    static testMethod void webServiceCallout() {
        TestUtility objTestUtility = new TestUtility();

        Contact guarantorContact = TestUtility.generateguarantorContact();
        insert guarantorContact ;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        test__c paymentPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
        insert paymentPlan;

        AddDiscount objAddDiscount = new AddDiscount(new ApexPages.StandardController(guarantorContact));
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        Invoice__c invoice = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
        insert invoice;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 123);
        chargeGroup.Charge_Group_ID__c = 123;
        insert chargeGroup;

        Transaction__c transactionObj = TestUtility.generateTransaction(chargeGroup, 100, 'Automatic');
        insert transactionObj;

        chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 124);
        chargeGroup.Charge_Group_ID__c = 124;
        insert chargeGroup;

        objAddDiscount = new AddDiscount(new ApexPages.StandardController(guarantorContact));
        for (ChargeGroupWrapper cgw :objAddDiscount.chargeGroupList) {
            cgw.isSelected = true;
        }
        objAddDiscount.doNext();
        Test.startTest();
        TestUtility.status = 'CREATED';
        TestUtility.statusCode = 201;

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorTest());
        objAddDiscount.submit();
        msgList = ApexPages.getMessages();
        System.assertEquals(1, msgList.size());
        Test.stopTest();
    }
}