src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <summarizedField>Transaction__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction__c.Charge_Group__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <formula>IF( Has_Chargegroup__c, 0, Patient_Portion__c - Total_Payments__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Has_Chargegroup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Are there are any related Charge_Group__c ?</description>
        <label>Has Chargegroup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_Portion__c</fullName>
        <formula>Total_Charges__c - Insurance_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Patient Portion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

src/classes/EncounterBalanceTest.cls
/**
 * Tests for calculating an Encounter's Balance
 */
@isTest
public with sharing class EncounterBalanceTest {

    @testSetup
    public static void setupData() {
        Encounter__c encounter = new Encounter__c();
        encounter.Patient_Portion__c = 3000.00;
        encounter.Department__c = 'Test Dept';
        INSERT encounter;
    }

    @isTest
    public static void testEncounterBalancePartialPayment() {
        Encounter__c encounter = [SELECT Id, Patient_Portion__c FROM Encounter__c WHERE Department__c = 'Test Dept'];

        Test.startTest();
        Payment__c pmt1 = new Payment__c();
        pmt1.Amount__c = 600.00;
        pmt1.Encounter__c = encounter.Id;

        Payment__c pmt2 = new Payment__c();
        pmt2.Amount__c = 400.00;
        pmt2.Encounter__c = encounter.Id;

        INSERT new Payment__c[]{pmt1, pmt2};
        Test.stopTest();

        encounter = [SELECT Id, Balance__c, Has_Chargegroup__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        System.assert(!encounter.Has_Chargegroup__c, 'Expected Has_Chargegroup__c to be false');
        System.assert(encounter.Balance__c == 2000.00, 'Expected Balance__c to be 2000.00, but was: '+encounter.Balance__c);
    }

    @isTest
    public static void testEncounterZeroBalanceChargeGroup() {
        Encounter__c encounter = [SELECT Id, Patient_Portion__c FROM Encounter__c WHERE Department__c = 'Test Dept'];

        Test.startTest();
        Contact gt = TestUtility.generateGuarantorContact();
        INSERT gt;

        Contact pt = TestUtility.generatePatientContact();
        INSERT pt;

        Charge_Group__c cg = TestUtility.generateChargeGroupWithExternalId(gt.Id, pt.Id, 12345);
        cg.Encounter__c = encounter.Id;
        INSERT cg;

        Test.stopTest();

        encounter = [SELECT Id, Balance__c, Has_Chargegroup__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        System.assert(encounter.Has_Chargegroup__c, 'Expected Has_Chargegroup__c to be true');
        System.assert(encounter.Balance__c == 0.00, 'Expected Balance__c to be 0, but was: '+encounter.Balance__c);
    }


    @isTest
    public static void testEncounterBalanceAfterDeleteChargeGroup() {
        Encounter__c encounter = [SELECT Id, Patient_Portion__c FROM Encounter__c WHERE Department__c = 'Test Dept'];

        Test.startTest();
        Contact gt = TestUtility.generateGuarantorContact();
        INSERT gt;

        Contact pt = TestUtility.generatePatientContact();
        INSERT pt;

        Charge_Group__c cg = TestUtility.generateChargeGroupWithExternalId(gt.Id, pt.Id, 12345);
        cg.Encounter__c = encounter.Id;
        INSERT cg;
        List<Charge_Group__c> cgs = [SELECT Id FROM Charge_Group__c WHERE Encounter__c = :encounter.Id];
        DELETE cgs;
        Test.stopTest();

        encounter = [SELECT Id, Balance__c, Has_Chargegroup__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        System.assert(!encounter.Has_Chargegroup__c, 'Expected Has_Chargegroup__c to be false');
        System.assert(encounter.Balance__c == 3000.00, 'Expected Balance__c to be 2000, but was: '+encounter.Balance__c);
    }
}