src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <summarizedField>Transaction__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction__c.Charge_Group__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Payable_Amount__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentPlanUtil.cls
/* 
 * @author Sirono
 * @version 1.0.1
 * @date: 09-01-2016
*/
public with sharing class PaymentPlanUtil {
	
	public PaymentPlanUtil() {
    
    }
	/*
    public static void updateBalances(Set<Id> planIds) {

        if (planIds.size() > 0) {
            //update the paymentplan with the sum of its chargegroup balances
            // Get the SUM of the associated chargegroup balances
            AggregateResult[] results = [
                    SELECT Payment_Plan__c pp, SUM(Balance__c) planBalance
                    FROM Charge_Group__c
                    WHERE Payment_Plan__c IN :planIds
                    GROUP BY Payment_Plan__c
            ];
            if (results.size() > 0) {
                updatePlans(results);
            } else {
                System.debug('No AggregateResults returned');
            }
        } else {
            System.debug('Empty planIds');
        }
    }

    private static void updatePlans(AggregateResult[] results) {
        List<test__c> pps = new List<test__c>();

        for (AggregateResult ar : results) {
            System.debug('ppId: ' + ar.get('pp'));
            System.debug('planBalance: ' + ar.get('planBalance'));
            test__c pp = new test__c();
            pp.Id = (Id) ar.get('pp');
            pp.Payable_Amount__c = (Decimal) ar.get('planBalance');
            pps.add(pp);
        }

        // Update the database
        if (pps.size() > 0) {
            update pps;
        }
    }*/
}