src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
    <fields>
        <fullName>Estimate_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of all Estimates for the guarantor</description>
        <label>Estimate Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Has_Chargegroup__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Are there are any related Charge_Group__c ?</description>
        <label>Has Chargegroup</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patient_Portion__c</fullName>
        <formula>Total_Charges__c - Insurance_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Patient Portion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

call-center/src/objects/Encounter__c.object
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Process</fullName>
                    <default>true</default>
                    <label>In Process</label>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Ready</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer of the account</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

src/classes/GuarantorEstimateBalanceTest.cls
/**
 * Test the calculation of the Estimate_Balance on the guarantor. It is the sum of all of the Encounters the
 * Guarantor is associated with.
 **/

@isTest
public with sharing class GuarantorEstimateBalanceTest {

    /**
     * This method is used to setup preliminary data to let's all testmethods to execute as expected.
     **/
    @testSetup
    public static void setupData() {
        Test.startTest();
        Encounter__c encounter = new Encounter__c();
        encounter.Patient_Portion__c = 3000.00;
        encounter.Department__c = 'Test Dept';
        encounter.Status__c = 'Ready';
        INSERT encounter;

        Contact gt1 = TestUtility.generateGuarantorContact();
        gt1.LastName = 'GT1';

        Contact gt2 = TestUtility.generateGuarantorContact();
        gt2.LastName = 'GT2';
        INSERT new Contact[]{gt1, gt2};
        Test.stopTest();

        // Check system assert, Encounter record should must be created/exist.
        System.assertNotEquals(encounter.Id, null, 'Encounter record does not exists/created.');
    }

    /**
     * This method tests the logic for estimate balance of Guarantor contact.
     **/
    @isTest
    public static void testGTEstimateBalance() {
        Encounter__c encounter = [SELECT Id, Patient_Portion__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        Contact gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE LastName = 'GT1'];

        encounter.Guarantor__c = gt.Id;
        UPDATE encounter;

        Test.startTest();

        Payment__c pmt1 = new Payment__c();
        pmt1.Amount__c = 600.00;
        pmt1.Encounter__c = encounter.Id;

        Payment__c pmt2 = new Payment__c();
        pmt2.Amount__c = 400.00;
        pmt2.Encounter__c = encounter.Id;

        INSERT new Payment__c[]{pmt1, pmt2};

        Test.stopTest();

        // Check system assert.
	gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt.Id];
        System.assert(gt.Estimate_Balance__c == 2000.00,
                'Expected Estimate_Balance__c to be 2000.00, but was: '+gt.Estimate_Balance__c);
    }

    /**
     * This method tests the logic for estimate balance of Guarantor contact negative.
     * Set Encounter status equals to "In Process" so Encounter Substatus set with "Unavailable" and Guarantor's estimate balance becomes 0.
     **/
    @isTest
    public static void testGTEstimateBalanceNegative() {
        Encounter__c encounter = [SELECT Id, Patient_Portion__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        Contact gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE LastName = 'GT1'];

        encounter.Guarantor__c = gt.Id;
        UPDATE encounter;

        // Check system assert.
        gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt.Id];
        System.assert(gt.Estimate_Balance__c == 3000.00,
                'Expected Estimate_Balance__c to be 3000.00, but was: '+gt.Estimate_Balance__c);

        Test.startTest();

        // Update Encounter with "In Process" Status.
        encounter = [SELECT Id, Patient_Portion__c, Status__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        encounter.Status__c = 'In Process';
        UPDATE encounter;

        Test.stopTest();

        // Check system assert.
        gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt.Id];
        System.assert(gt.Estimate_Balance__c == 0,
                'Expected Estimate_Balance__c to be 0, but was: '+gt.Estimate_Balance__c);
    }

    /**
     * This method checks contact's Estimate Balance after update encounter's guarantor with another contact.
     **/
    @isTest
    public static void testGTEstimateBalanceChangeEncounterGuarantor() {
        Encounter__c encounter = [SELECT Id, Patient_Portion__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        Contact gt1 = [SELECT Id, Estimate_Balance__c FROM Contact WHERE LastName = 'GT1'];
        Contact gt2 = [SELECT Id, Estimate_Balance__c FROM Contact WHERE LastName = 'GT2'];

        encounter.Guarantor__c = gt1.Id;
        UPDATE encounter;

         // Check system assert.
	gt1 = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt1.Id];
        System.assert(gt1.Estimate_Balance__c == 3000.00,
                'Expected Estimate_Balance__c to be 3000, but was: '+gt1.Estimate_Balance__c);

        Test.startTest();

        encounter = [SELECT Id FROM Encounter__c WHERE Department__c = 'Test Dept'];
        encounter.Guarantor__c = gt2.Id;
        UPDATE encounter;

        Test.stopTest();

	// Check system assert.
        gt1 = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt1.Id];
        gt2 = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt2.Id];

        System.assert(gt1.Estimate_Balance__c == 0,
                'Expected Estimate_Balance__c to be 0, but was: '+gt1.Estimate_Balance__c);

        System.assert(gt2.Estimate_Balance__c == 3000.00,
                'Expected Estimate_Balance__c to be 3000, but was: '+gt2.Estimate_Balance__c);
    }

    /**
     * This method validates guarantor's Estimate Balance for zero amount.
     **/
    @isTest
    public static void testGTEstimateZeroBalance() {
        Encounter__c encounter = [SELECT Id FROM Encounter__c WHERE Department__c = 'Test Dept'];
        Contact gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE LastName = 'GT1'];
        encounter.Guarantor__c = gt.Id;
        UPDATE encounter;

        // Check system assert.
	gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt.Id];
        System.assert(gt.Estimate_Balance__c == 3000.00,
                'Expected Estimate_Balance__c to be 3000, but was: '+gt.Estimate_Balance__c);

        Test.startTest();

        Contact pt = TestUtility.generatePatientContact();
        INSERT pt;

        Charge_Group__c cg = TestUtility.generateChargeGroupWithExternalId(gt.Id, pt.Id, 12345);
        cg.Encounter__c = encounter.Id;
        INSERT cg;

        Test.stopTest();

	// Check system assert.
        encounter = [SELECT Id, Has_Chargegroup__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        System.assert(encounter.Has_Chargegroup__c, 'Expected Encounter Has_Chargegroup__c to be true');

        gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt.Id];
        System.assert(gt.Estimate_Balance__c == 0,
                'Expected Estimate_Balance__c to be 0 for gt: '+gt.Id+', but was: '+gt.Estimate_Balance__c);
    }

    /**
     * This method checks validates Estimate Balance after Encounter record gets deleted.
     **/
    @isTest
    public static void testGTEstimateBalanceAfterEncounterDeleted() {
        Encounter__c encounter = [SELECT Id, Patient_Portion__c FROM Encounter__c WHERE Department__c = 'Test Dept'];
        Contact gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE LastName = 'GT1'];

        encounter.Guarantor__c = gt.Id;
        UPDATE encounter;
        
	// Check system assert.
	gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt.Id];
        System.assert(gt.Estimate_Balance__c == 3000.00,
                'Expected Estimate_Balance__c to be 3000.00, but was: '+gt.Estimate_Balance__c);

        Test.startTest();

        DELETE encounter;

        Test.stopTest();

	// Check system assert.
        gt = [SELECT Id, Estimate_Balance__c FROM Contact WHERE Id = :gt.Id];
        System.assert(gt.Estimate_Balance__c == 0.00,
                'Expected Estimate_Balance__c to be 0.00, but was: '+gt.Estimate_Balance__c);
    }
}