src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Patient)</relationshipLabel>
        <relationshipName>Charge_Groups_Patient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Charge_Group_Coverage_Junction__c.object
<CustomObject>
    <description>Junction object to create many-to-many relationship between Charge Groups and Coverages</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Charge Group Coverage Junctions</relationshipLabel>
        <relationshipName>Charge_Group_Coverages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Coverage__c</fullName>
        <label>Coverage</label>
        <referenceTo>Coverage__c</referenceTo>
        <relationshipLabel>Charge Group Coverage Junctions</relationshipLabel>
        <relationshipName>Charge_Group_Coverages</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Charge Group Coverage Junction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Group Coverage Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <description>Patient medical Record number</description>
        <label>Medical Record Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Coverage__c.object
<CustomObject>
    <description>Insurance plan coverage details</description>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Coverages</relationshipLabel>
        <relationshipName>Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipLabel>Coverages</relationshipLabel>
        <relationshipName>Coverages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Coverage</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Coverages</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Coverage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The coverage associated with this Encounter</description>
        <label>Coverage</label>
        <referenceTo>Coverage__c</referenceTo>
        <relationshipLabel>Encounters</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Discount__c</fullName>
        <label>Insurance Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Insurance_Portion__c</fullName>
        <label>Insurance Portion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Patient)</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Payments__c</fullName>
        <label>Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Invoice_Status_Index__c</fullName>
        <label>Invoice Status Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Payment_Adjustments__c.object
<CustomObject>
    <description>Meta data about Adjustment and Payment Transactions</description>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipName>Payment_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payor</label>
        <referenceTo>Payor__c</referenceTo>
        <relationshipLabel>Payments / Adjustments</relationshipLabel>
        <relationshipName>Payments_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipName>Payment_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment / Adjustment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments / Adjustments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payor__c.object
<CustomObject>
    <label>Payor</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Tranaction_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/WorkWithInvoicesControllerTest.cls
@isTest
private class WorkWithInvoicesControllerTest {
	@isTest static void invoicesTest() {
		Contact guarantorContact;
		Contact patientContact;
		User internalUser;
		Invoice__c invoice1;

		UserRole usrRole = [
            SELECT Id
            FROM UserRole 
            WHERE Name = 'CEO'
        ];

        Profile testProfile = [
            SELECT Id, Name
            FROM Profile 
            WHERE Name = 'System Administrator'
        ];

		User testUser = new User (
            LastName = 'test user 1', 
            Username = String.valueOf(System.now().millisecond()) + 'test.user.invoice@example.com', 
            Email = 'test.1@example.com', 
            Alias = 'testu1', 
            TimeZoneSidKey = 'GMT', 
            LocaleSidKey = 'en_GB', 
            EmailEncodingKey = 'ISO-8859-1', 
            ProfileId = testProfile.Id, 
            UserRoleId = usrRole.Id,
            LanguageLocaleKey = 'en_US'
        ); 
        insert testUser;   

		System.runAs(testUser) {
			Profile profile = [
	            SELECT Id, Name
	            FROM Profile 
	            WHERE Name = 'Guarantor'
	        ];

	        Account testAcc = new Account (
	        	Name = 'Test Account Name'
	        );
  			insert testAcc;

	      	guarantorContact = TestUtility.generateGuarantorContact();
	      	guarantorContact.AccountId = testAcc.Id;
	        insert guarantorContact;

	        patientContact = TestUtility.generatePatientContact();
	      	patientContact.AccountId = testAcc.Id;
	      	patientContact.Medical_Record_Number__c = '1234512345';
	        insert patientContact;

	        internalUser = new User (
	        	Username = profile.Id + String.valueOf(System.now().millisecond()) + '@example.com',
	            ProfileId = profile.Id,
	            ContactId = guarantorContact.Id,
	            Alias = 'user' + System.now().millisecond(),
	            Email = profile.Id + '@example.com',
	            EmailEncodingKey = 'UTF-8',
	            LastName = 'Test',
	            CommunityNickname = profile.Id,
	            TimeZoneSidKey = 'America/Los_Angeles',
	            LocaleSidKey = 'en_US',
	            LanguageLocaleKey = 'en_US'
	        );
	  		insert internalUser;

	  		Payment_Plan__c pPlan = TestUtility.generatePaymentPlan(guarantorContact.Id);
	  		insert pPlan;

	  		List<Invoice__c> lstInvoice = new List<Invoice__c>();
	  		invoice1 = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
	        lstInvoice.add(invoice1);

	        Invoice__c invoice2 = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
	        lstInvoice.add(invoice2);

	        Invoice__c invoice3 = TestUtility.generateInvoice(guarantorContact.Id, patientContact.Id);
	        invoice3.Invoice_Status_Index__c = 2;
	        lstInvoice.add(invoice3);

	        insert lstInvoice;

	        List<Charge_Group__c> lstChrgGroup = new List<Charge_Group__c>();
	        Charge_Group__c chargeGroup1 = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 1234, pPlan.Id);
	        chargeGroup1.Invoice__c = invoice1.Id;
	        lstChrgGroup.add(chargeGroup1);

	        Charge_Group__c chargeGroup2 = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 1234, pPlan.Id);
	        chargeGroup2.Invoice__c = invoice2.Id;
	        lstChrgGroup.add(chargeGroup2);
	        insert lstChrgGroup;

	        Payor__c payorTest = new Payor__c(
	        	Name = 'payotTest'
	        );
	        insert payorTest;

	        Coverage__c objcoverage = new Coverage__c(
	        	Name = 'Test',
	        	Payor__c = payorTest.Id 
	        );
	        insert objcoverage;
	        
	        Charge_Group_Coverage_Junction__c objCGCoverage = new Charge_Group_Coverage_Junction__c();
	        objCGCoverage.Name = 'Test';
	        objCGCoverage.Charge_Group__c = chargeGroup1.Id;
	        objCGCoverage.Coverage__c = objcoverage.Id;
	        insert objCGCoverage;

	        Service__c serviceTest = new Service__c(
	        	Name = 'serviceTest',
	        	Charge_Group__c	= chargeGroup2.Id
	        );
	        insert serviceTest;

	        Payment_Adjustments__c paymentAdjTest = new Payment_Adjustments__c(
	        	Name = 'paymentAdjTest',
	        	Charge_Group__c = chargeGroup2.Id
	        );
	        insert paymentAdjTest;

	        Payment__c payment1 = TestUtility.generateSironoPayment(guarantorContact.Id, 1234, 12);
	        Payment__c payment2 = TestUtility.generateSironoPayment(guarantorContact.Id, 1235, 25);
	        List<Payment__c> lstPayment = new List<Payment__c>{payment1, payment2};
	        insert lstPayment;

	        List<Transaction__c> lstTransaction = new List<Transaction__c>();
	        Transaction__c transaction1 = TestUtility.generatePaymentTxn(chargeGroup1, 20, payment1);
	        lstTransaction.add(transaction1);

	        Transaction__c transaction2 = TestUtility.generatePaymentTxn(chargeGroup1, 200, payment2);
	        lstTransaction.add(transaction2);

	        Transaction__c transaction3 = TestUtility.generateServiceTxn(chargeGroup2, 20, serviceTest);
	        lstTransaction.add(transaction3);

	        Transaction__c transaction4 = TestUtility.generateServiceTxn(chargeGroup2, 200, serviceTest);
	        lstTransaction.add(transaction4);

	        Transaction__c transaction5 = TestUtility.generateAdjTxn(chargeGroup2, 200, paymentAdjTest);
	        lstTransaction.add(transaction5);
	        insert lstTransaction;

	        invoice1.Invoice_Status_Index__c = 9;
	        invoice2.Invoice_Status_Index__c = 4;
	        List<Invoice__c> lstInvoiceUpdate = new List<Invoice__c>{invoice1, invoice2};
	        update lstInvoiceUpdate;
		}

		List<WorkWithInvoicesController.PatientWrapper> patientList = WorkWithInvoicesController.getPatientList();
		System.assertEquals(patientList.size(), 0);	

		System.runAs(internalUser) {
        	Test.startTest();

        	List<WorkWithInvoicesController.InvoicesWrapper> invoiceList = WorkWithInvoicesController.getAllInvoices('Unpaid', patientContact.Id);
        	System.assertEquals(invoiceList.size(), 1);
        	invoiceList = WorkWithInvoicesController.getAllInvoices('Paid', patientContact.Id);
        	System.assertEquals(invoiceList.size(), 1);
        	invoiceList = WorkWithInvoicesController.getAllInvoices('Unknown', patientContact.Id);
        	System.assertEquals(invoiceList.size(), 1);
        	invoiceList = WorkWithInvoicesController.getAllInvoices('Unknown', 'null');
        	System.assertEquals(invoiceList.size(), 0);
        	invoiceList = WorkWithInvoicesController.getInvoice(invoice1.Id);
        	System.assertEquals(invoiceList.size(), 1);

        	patientList = WorkWithInvoicesController.getPatientList();
        	System.assertEquals(patientList.size(), 3);

        	Test.stopTest();
        }
	}

	@isTest static void estimatesTest() {
		Contact guarantorContact;
		Contact patientContact;
		User internalUser;
		Encounter__c encounter1;

		UserRole usrRole = [
            SELECT Id
            FROM UserRole 
            WHERE Name = 'CEO'
        ];

        Profile testProfile = [
            SELECT Id, Name
            FROM Profile 
            WHERE Name = 'System Administrator'
        ];

		User testUser = new User (
            LastName = 'test user 1', 
            Username = String.valueOf(System.now().millisecond()) + 'test.user.invoice2@example.com', 
            Email = 'test.1@example.com', 
            Alias = 'testu1', 
            TimeZoneSidKey = 'GMT', 
            LocaleSidKey = 'en_GB', 
            EmailEncodingKey = 'ISO-8859-1', 
            ProfileId = testProfile.Id, 
            UserRoleId = usrRole.Id,
            LanguageLocaleKey = 'en_US'
        ); 
        insert testUser;   

		System.runAs(testUser) {
			Profile profile = [
	            SELECT Id, Name
	            FROM Profile 
	            WHERE name = 'Guarantor'
	        ];

	        Account testAcc = new Account (
	        	Name = 'Test Account Name'
	        );
  			insert testAcc;

	      	guarantorContact = TestUtility.generateGuarantorContact();
	      	guarantorContact.AccountId = testAcc.Id;
	        insert guarantorContact;

	        patientContact = TestUtility.generatePatientContact();
	      	patientContact.AccountId = testAcc.Id;
	      	patientContact.Medical_Record_Number__c = '1234512345';
	        insert patientContact;

	        internalUser = new User (
	        	Username = profile.Id + String.valueOf(System.now().millisecond()) + '@example.com',
	            ProfileId = profile.Id,
	            ContactId = guarantorContact.Id,
	            Alias = 'user' + System.now().millisecond(),
	            Email = profile.Id + '@example.com',
	            EmailEncodingKey = 'UTF-8',
	            LastName = 'Test',
	            CommunityNickname = profile.Id,
	            TimeZoneSidKey = 'America/Los_Angeles',
	            LocaleSidKey = 'en_US',
	            LanguageLocaleKey = 'en_US'
	        );
	  		insert internalUser;

	  		List<Encounter__c> lstEncounter = new List<Encounter__c>();
	  		encounter1 = TestUtility.generateEncounter(guarantorContact.Id, 10, Date.today());
	  		encounter1.Patient__c = patientContact.Id;
	  		encounter1.Insurance_Discount__c = 2;
	        encounter1.Insurance_Portion__c = 2;
	        lstEncounter.add(encounter1);
	        Encounter__c encounter2 = TestUtility.generateEncounter(guarantorContact.Id, 10, Date.today());
	        encounter2.Total_Payments__c = 5;
	        encounter2.Patient__c = patientContact.Id;
	        encounter2.Insurance_Discount__c = 3;
	        encounter2.Insurance_Portion__c = 2;
	        lstEncounter.add(encounter2);

	        insert lstEncounter;

	        Attachment testAttach = new Attachment (
	        	Body = Blob.valueOf('Test string'),
	        	Name = 'test attach',
	        	ParentId = encounter1.Id
	        );
	        insert testAttach;
		}

        System.runAs(internalUser) {
        	Test.startTest();

        	List<WorkWithEstimatesController.EstimateWrapper> estimateList = WorkWithInvoicesController.getAllEstimates('Unpaid', patientContact.Id);
        	System.assertEquals(estimateList.size(), 1);
        	estimateList = WorkWithInvoicesController.getAllEstimates('Paid', 'null');
        	System.assertEquals(estimateList.size(), 0);
        	estimateList = WorkWithInvoicesController.getEstimate(encounter1.Id);
        	System.assertEquals(estimateList.size(), 1);

        	Test.stopTest();
        }
	}
}