src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Balance__c</fullName>
        <label>Balance</label>
        <summarizedField>Transaction__c.Amount__c</summarizedField>
        <summaryForeignKey>Transaction__c.Charge_Group__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Patient of the account or case</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <description>Credit card details</description>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Charges_Added_Since_Start__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Charges Added Since Start</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Original_Balance__c</fullName>
        <description>Type of plan</description>
        <label>Plan Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Value_Modified_Date__c</fullName>
        <description>time stamp of plan modification</description>
        <label>Plan Value Modified Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Remaining_Balance__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Service__c.object
<CustomObject>
    <description>Meta data about Charge Transactions</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>Post Date</description>
        <label>Post Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Tranaction_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>Date and Time stamp</description>
        <label>Post Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentPlanBalanceTest.cls
@isTest
public class PaymentPlanBalanceTest {

    /*
     * Setup test data to be used in the following test methods.
     */

    @testSetup
    static void setupTestRecords() {
        // Use a modified CreatedDate so we can test transactions added in the future
        Datetime newCreateDate = system.now().addDays(-5);

        // Generate and insert initial Transaction, Charge Group, Guarantor, and Patient
        Contact patient = TestUtility.generatePatientContact();
        patient.CreatedDate = Date.valueOf(newCreateDate);
        insert patient;


        Contact guarantor = TestUtility.generateGuarantorContact();
        guarantor.CreatedDate = Date.valueOf(newCreateDate);
        insert guarantor;


        Map<String, String> recordTypeMap = new Map<String, String>();
        for (RecordType recordType : [
                Select Id, Name
                From RecordType
                Where sObjectType = 'Payment_Method__c'
        ]) {
            recordTypeMap.put(recordType.Name, recordType.Id);
        }

        Payment_Method__c testPM = TestUtility.generatePaymentMethod(guarantor.Id, recordTypeMap.get('Credit Card'));
        testPM.CreatedDate = Date.valueOf(newCreateDate);
        insert testPM;

        Payment_Plan__c testPP = TestUtility.generatePaymentPlan(guarantor);
        testPP.CreatedDate = newCreateDate;
        testPP.Plan_Value_Modified_Date__c = newCreateDate;
        testPP.Original_Balance__c = TestUtility.generateRandomCurrency();
        insert testPP;

        Charge_Group__c testCG = TestUtility.generateChargeGroup(guarantor.Id, patient.Id, 887887, testPP.Id);
        testCG.CreatedDate = Date.valueOf(newCreateDate);
        insert testCG;

        Service__c testService = TestUtility.generateService(testCG, TestUtility.generateRandomCurrency());
        testService.Post_Date__c = Date.valueOf(newCreateDate);
        insert testService;

        Transaction__c testTransaction = TestUtility.generateServiceTxn(testCG, testService.Amount__c, testService);
        testTransaction.Post_Date__c = Date.valueOf(newCreateDate);
        testTransaction.Transaction_Date__c = Date.valueOf(testPP.Plan_Value_Modified_Date__c);
        insert testTransaction;
    }

    /*
     * Upon initial insert of charge group and related data, make sure Charges_Added_Since_Start__c = 0 or null
     */
    @isTest
    static void initialCGInsertTest() {
        Test.startTest();

        List<Payment_Plan__c> ppResults = [
                SELECT Id, Charges_Added_Since_Start__c
                FROM Payment_Plan__c
        ];

        Test.stopTest();

        for(Payment_Plan__c pp : ppResults){
            system.debug('Charges added since plan start: ' + pp.Charges_Added_Since_Start__c);
            system.assert(pp.Charges_Added_Since_Start__c == 0.00 || pp.Charges_Added_Since_Start__c == null,
                    'Charges Added Should be 0 or null on initial insert.');
        }
    }

    /*
     * Add a new transaction to the charge group, Charges_Added_Since_Start__c should equal transaction amount
     */
    @isTest
    static void addNewTransactionTest() {
        Test.startTest();

        Charge_Group__c testCG = [SELECT Id, Balance__c from Charge_Group__c LIMIT 1];

        Service__c newService = TestUtility.generateService(testCG, TestUtility.generateRandomCurrency());
        insert newService;

        Transaction__c newServiceTransaction = TestUtility.generateServiceTxn(testCG, newService.Amount__c, newService);
        newServiceTransaction.Post_Date__c = Date.valueOf(newService.Post_Date__c);
        newServiceTransaction.Transaction_Date__c =  Date.valueOf(newServiceTransaction.Post_Date__c);
        insert newServiceTransaction;

        Payment_Plan__c ppResults = [
                SELECT Id, Charges_Added_Since_Start__c
                FROM Payment_Plan__c
                LIMIT 1
        ];

        Test.stopTest();

        system.assertEquals(newServiceTransaction.Amount__c, ppResults.Charges_Added_Since_Start__c,
                'Charges added since plan start should equal the inserted transaction amount.');
    }

    /*
     * Add a new transaction and then modify the payment plan's value modified date
     * Assert that Charges_Added_Since_Start__c equals 0
     */
    @isTest
    static void changePPValueModifiedDateTest() {
        Test.startTest();

        Charge_Group__c testCG = [SELECT Id, Balance__c from Charge_Group__c LIMIT 1];

        Service__c newService = TestUtility.generateService(testCG, TestUtility.generateRandomCurrency());
        insert newService;

        Transaction__c secondTestTransaction = TestUtility.generateServiceTxn(testCG, newService.Amount__c, newService);
        secondTestTransaction.Transaction_Date__c = system.today().addDays(-3);
        insert secondTestTransaction;

        Payment_Plan__c updatedPPResults = [
                SELECT Id, Charges_Added_Since_Start__c, Remaining_Balance__c, Plan_Value_Modified_Date__c
                FROM Payment_Plan__c
                LIMIT 1
        ];

        // Modify PP value modified date and recalculate
        updatedPPResults.Plan_Value_Modified_Date__c = date.today();
        update updatedPPResults;

        Payment_Plan__c finalPPResults = [
                SELECT Id, Charges_Added_Since_Start__c, Remaining_Balance__c, Plan_Value_Modified_Date__c
                FROM Payment_Plan__c
                LIMIT 1
        ];

        Test.stopTest();

        system.assertEquals(0, finalPPResults.Charges_Added_Since_Start__c,
                'Value date was updated, charges added should be 0.');
    }

    /*
     * Insert a payment transaction and
     * Assert that the added charges field isn't updated
     * Charges_Added_Since_Start__c sums only service transactions
     */
    @isTest
    static void insertPaymentTransactionTest() {
        Test.startTest();

        Charge_Group__c testCG = [SELECT Id, Balance__c from Charge_Group__c LIMIT 1];
        Contact guarantor = [SELECT Id FROM Contact WHERE RecordTypeId = :RecordTypeUtil.guarantorRt];

        Payment__c pmt = TestUtility.generateSironoPayment(guarantor.Id, Decimal.valueOf(Math.random()), TestUtility.generateRandomCurrency());
        insert pmt;

        Transaction__c secondTestTransaction = TestUtility.generatePaymentTxn(testCG, pmt.Amount__c, pmt);
        secondTestTransaction.Transaction_Date__c = Date.valueOf(secondTestTransaction.Post_Date__c);
        insert secondTestTransaction;

        Payment_Plan__c ppResults = [
                SELECT Id, Charges_Added_Since_Start__c
                FROM Payment_Plan__c
                LIMIT 1
        ];

        Test.stopTest();

        system.assertEquals(0, ppResults.Charges_Added_Since_Start__c,
                'Transaction was payment type; charges added should not have been updated.');
    }
}