src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Account_Sub_Status__c</fullName>
        <label>Account Sub Status</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>cannot delete</description>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Balance (Deprecated)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Export_Date__c</fullName>
        <label>Export Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fail_Date__c</fullName>
        <description>Fail Date</description>
        <label>Fail Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes (Deprecated)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>Date and Time stamp</description>
        <label>Post Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionJSONParsing.cls
/*
* @author: Sirono
* @version 1.0.1
* @Date: 10-17-2016
* JSON Parsing Class for the response which comes from Transaction Request.
*/

public class TransactionJSONParsing {

    public string url;
    public integer amount;
    public string post_date;
    public string fail_date;
    public string export_date;
    public string created_at;
    public string modified_at;
    public string method;
    public string notes;
    public boolean credit_balance;
    public string payment;
    public string chargegroup;

    public class TransactionWrapper{
        public List<Transaction__c> transactionRecords {get;set;}
        public List<Charge_Group__c> chargeGroupRecords {get;set;}

        public TransactionWrapper(){
            transactionRecords = new List<Transaction__c>();
            chargeGroupRecords = new List<Charge_Group__c>();
        }
    }

    public static TransactionWrapper parse(String json) {
        if(!json.contains('[')){
            json = '[' + json + ']';
        }
        
        TransactionWrapper objTransactionWrapper = new TransactionWrapper();
        List<Transaction__c> lstTransaction = new List<Transaction__c>();
        List<Charge_Group__c> lstChargeGroup = new List<Charge_Group__c>();

        List<TransactionJSONParsing> lstTransactionJson =
            (List<TransactionJSONParsing>) System.JSON.deserialize(json.replace('_credit_balance','credit_balance'), List<TransactionJSONParsing>.class);

        if (lstTransactionJson.size() > 0) {
            List<Charge_Group__c> unallocatedChargeGroup = [SELECT Id FROM Charge_Group__c where name = 'Unallocated'];
            map<string, decimal> mapTransactionChargeGroup = new map<string, decimal>();

            for (TransactionJSONParsing objJson : lstTransactionJson) {
                Transaction__c objTransaction = new Transaction__c();
                string transactionExternalId = getExternalID(String.valueof(objJson.url),'transaction');

                objTransaction.Sirono_ID__c = Integer.valueof(transactionExternalId);
                objTransaction.Name = objJson.method + '-' + transactionExternalId;
                objTransaction.Amount__c = PayStaffWSUtill.convertToDollarsWithNegative(objJson.amount);
                if (!String.Isblank(objJson.post_date)) {
                    objTransaction.Post_Date__c = Date.valueof(objJson.post_date);
                }
                if (!String.Isblank(objJson.fail_date)) {
                    objTransaction.Fail_Date__c = Date.valueof(objJson.fail_date);
                }
                if (!String.Isblank(objJson.export_date)) {
                    objTransaction.Export_Date__c = Date.valueof(objJson.export_date);
                }
                objTransaction.Notes__c = objJson.notes;
                objTransaction.Credit_Balance__c = objJson.credit_balance;

                if (objJson.chargegroup == null) {
                    if(unallocatedChargeGroup.size() > 0){
                        objTransaction.Charge_Group__c = unallocatedChargeGroup[0].Id;
                    }
                } else {
                    decimal chargegroup = Decimal.Valueof(getExternalID(String.valueof(objJson.chargegroup),'chargegroups'));
                    mapTransactionChargeGroup.put(transactionExternalId, chargegroup);
                }

                lstTransaction.add(objTransaction);
            }

            if (mapTransactionChargeGroup.size() > 0) {

                lstChargeGroup = [SELECT Id, Sirono_ID__c, Account_Sub_Status__c,
                        Payment_Plan__c, Payment_Plan__r.Sirono_ID__c, Payment_Plan__r.Guarantor__c
                        FROM Charge_Group__c
                        where Sirono_ID__c in: mapTransactionChargeGroup.values()];

                map<decimal, string> mapChargeGroup = new map<decimal, string>();
                for(Charge_Group__c cg : lstChargeGroup){
                    mapChargeGroup.put(cg.Sirono_ID__c, cg.Id);
                }

                for(Transaction__c tran : lstTransaction) {
                    if(tran.Charge_Group__c == null){
                        decimal cId = mapTransactionChargeGroup.get(string.valueof(tran.Sirono_ID__c));
                        tran.Charge_Group__c = mapChargeGroup.get(cId);
                    }
                }
            }

            if(lstTransaction.size() > 0){
                objTransactionWrapper.transactionRecords = lstTransaction;
            }
            if(lstChargeGroup.size() > 0){
                objTransactionWrapper.chargeGroupRecords = lstChargeGroup;
            }
        }
        return objTransactionWrapper;
    }

    public Static String getExternalID(String url,string splitWith){
        String[] externalID = url.split(splitWith);
        return externalID[externalID.Size() - 1].replaceAll('/','');
    }
    
    Public Static String  testResponse() {
    
        String responseBody =        '{'+
        '   "url":"https://toledo.stage.sirono.com/paystaff/api/transaction/22923843/", ' +
        '   "amount":100,'+
        '   "post_date":"2016-10-17T00:00:00",'+
        '   "fail_date":"2016-10-17T00:00:00",'+
        '   "export_date":"2016-10-17T00:00:00",'+
        '   "created_at":"2016-10-17T12:41:22.562824",'+
        '   "modified_at":"2016-10-17T12:41:22.562843",' +
        '   "method":"adjustment",' +
        '   "notes":null,' +
        '   "credit_balance":false,' +
        '   "payment":null,' +
        '   "chargegroup":"https://toledo.stage.sirono.com/paystaff/api/chargegroups/124/" ' +
        '}';
        
        return responseBody;
    }
}