src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Charge_Group_External_ID__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used for integration</description>
        <label>Charge Group External ID</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Patient)</relationshipLabel>
        <relationshipName>Charge_Groups_Patient</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Patient</fullName>
        <active>true</active>
        <description>Patient of the account or case</description>
        <label>Patient</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <description>Invoice Date</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Patient</description>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Guarantor_Name__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestProcessPayment.cls
@isTest
private class TestProcessPayment {

    static testMethod void myUnitTest() {
    	Map<String, Id> rtMap = new Map<String, Id>();
    	for(RecordType rt : [Select Id, Name From RecordType Where sObjectType = 'Contact']){
    		rtMap.put(rt.Name, rt.Id);
    	}
    	Contact g = new Contact();
    	g.RecordTypeId = rtMap.get('Guarantor');
    	g.LastName = 'G Test';
    	g.Profile_Pointer_Id__c = 123;
    	insert g;
    	
    	Contact p = new Contact();
    	p.RecordTypeId = rtMap.get('Patient');
    	p.LastName = 'G Test';
    	insert p;
    	
    	test__c t = new test__c();
    	t.Guarantor_Name__c = g.Id;
    	insert t;
    	
    	ProcessPayment ppCon = new ProcessPayment(new ApexPages.StandardController(g));
    	ppCon.submit();
       	
    	Invoice__c i = new Invoice__c();
    	i.Guarantor_Name__c = g.Id;
    	i.Due_Date__c = System.today();
    	i.Invoice_Date__c = System.today();
    	i.Invoice_ID__c = 123;
    	i.Patient__c = p.Id;
    	insert i;
    	
    	Charge_Group__c cg = new Charge_Group__c();
    	cg.Invoice__c = i.id;
    	cg.Payment_Plan__c = t.Id;
    	cg.Patient_Name__c = p.Id;
    	cg.Guarantor_Name__c = g.Id;
    	cg.Charge_Group_ID__c = 123;
    	cg.Charge_Group_External_ID__c = true;
    	insert cg;
    	cg = new Charge_Group__c();
    	cg.Invoice__c = i.id;
    	cg.Payment_Plan__c = t.Id;
    	cg.Patient_Name__c = p.Id;
    	cg.Guarantor_Name__c = g.Id;
    	cg.Charge_Group_ID__c = 124;
    	cg.Charge_Group_External_ID__c = true;
    	insert cg;
       	
       	ppCon = new ProcessPayment(new ApexPages.StandardController(g));
       	for(ChargeGroupWrapper cgw :ppCon.chrageGroupList){
       		cgw.isSelected = true;
       	}
       	ppCon.doNext();
       	ppCon.creditCardNumber = '123';
       	ppCon.cardholderName = '123';
       	ppCon.expirationYear = '123';
       	ppCon.expirationMonth = '123';
       	ppCon.CVV = '123';
       	ppCon.amount = '123';
       	ppCon.address = '123';
       	ppCon.city = '123';
       	ppCon.state = '123';
       	ppCon.zip = '123';
    	ppCon.submit();
    }
}