src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Patient)</relationshipLabel>
        <relationshipName>Charge_Groups_Patient</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Service__c</fullName>
        <label>Date of Service</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Liability__c</fullName>
        <label>Liability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Patient)</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EncounterTriggerTest.cls
/*
 * @author Sirono
 * @version 1.0.1
 * @Date: 06-06-2016
 * @EncounterTriggerTest Test Class for the Code Covrege of EncounterTriggerHandler Class.
 */

@isTest
private class EncounterTriggerTest {

    static testMethod void myUnitTest() {
        TestUtility objUtility = new TestUtility();

        Contact guarantorContact = TestUtility.generateGuarantorContact();
        insert guarantorContact;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        Contact guarantorContact2 = TestUtility.generateGuarantorContact();
        guarantorContact2.LastName = 'G Test';
        guarantorContact2.Profile_Pointer_Id__c = 1234;
        guarantorContact2.Guarantor__c = guarantorContact.Id;
        insert guarantorContact2;

        Encounter__c encounter = TestUtility.generateEncounter(guarantorContact.id, 100, System.Today());
        encounter.Patient__c = patientContact.Id;
        encounter.Liability__c = 200;
        encounter.Cancelled__c = true;
        insert encounter;

        encounter.Liability__c = 300;
        update encounter;

        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(0, msgList.size());
    }

    static testMethod void myUnitTest1() {
        TestUtility objUtility = new TestUtility();

        Contact guarantorContact = TestUtility.generateGuarantorContact();
        insert guarantorContact;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        Contact guarantorContact2 = TestUtility.generateGuarantorContact();
        guarantorContact2.LastName = 'G Test';
        guarantorContact2.Profile_Pointer_Id__c = 1234;
        guarantorContact2.Guarantor__c = guarantorContact.Id;
        insert guarantorContact2;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 100);
        insert chargeGroup;

        Encounter__c encounter = TestUtility.generateEncounter(guarantorContact.id, 100, System.Today());
        encounter.Patient__c = patientContact.Id;
        encounter.Liability__c = 200;
        encounter.Cancelled__c = true;
        insert encounter;

        encounter.Liability__c = 500;
        encounter.Cancelled__c = true;
        encounter.Date_of_Service__c = System.Today() - 3;
        encounter.Guarantor__c = guarantorContact2.Id;
        update encounter;

        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(0, msgList.size());
    }

    //Viraj Rana 09-15-2016 : Improve the code coverage of EncounterTriggerHandler
    static testMethod void myUnitTest2() {
        TestUtility objUtility = new TestUtility();


        Contact guarantorContact = TestUtility.generateGuarantorContact();
        insert guarantorContact;

        List<Contact> lstContact = [Select Id from Contact];
        System.assertEquals(1, lstContact.size());

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        Encounter__c encounter = TestUtility.generateEncounter(guarantorContact.id, 100, System.Today());
        encounter.Patient__c = patientContact.Id;
        encounter.Liability__c = 200;
        encounter.Cancelled__c = true;
        insert encounter;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 100);
        insert chargeGroup;

        lstContact = [Select Id from Contact];
        System.assertEquals(2, lstContact.size());
        encounter.Liability__c = 300;
        encounter.Guarantor__c = null ;
        update encounter;

        lstContact = [Select Id from Contact];
        System.assertEquals(2, lstContact.size());
    }

    //Viraj Rana 09-15-2016 : Improve the code coverage of EncounterTriggerHandler
    static testMethod void checkCallListRemove() {
        TestUtility objUtility = new TestUtility();

        Contact guarantorContact = TestUtility.generateGuarantorContact();
        insert guarantorContact;

        Contact patientContact = TestUtility.generatePatientContact();
        insert patientContact;

        Contact guarantorContact2 = TestUtility.generateGuarantorContact();
        guarantorContact2.LastName = 'G Test';
        guarantorContact2.Profile_Pointer_Id__c = 1234;
        guarantorContact2.Guarantor__c = guarantorContact.Id;
        insert guarantorContact2;

        Encounter__c encounter = TestUtility.generateEncounter(guarantorContact.id, 100, System.Today());
        encounter.Patient__c = patientContact.Id;
        encounter.Liability__c = 200;
        encounter.Cancelled__c = true;
        insert encounter;

        Charge_Group__c chargeGroup = TestUtility.generateChargeGroup(guarantorContact.Id, patientContact.Id, 100);
        insert chargeGroup;

        encounter.Guarantor__c = guarantorContact2.Id;
        update encounter;

        List<CampaignMember> lstCamp = [
                Select Id, ContactId, CampaignId
                From CampaignMember
                Where ContactId = :guarantorContact2.Id
        ];
        List<ApexPages.Message> msgList = ApexPages.getMessages();
        System.assertEquals(0, lstCamp.size());
    }
    
    /**
     * Check all access rights for a read only User using runAs.
     **/
    @isTest
    static void checkAccessRights() {
        List<EncounterSecurityContext> allContexts = new List<EncounterSecurityContext>{EncounterSecurityContext.UPDATE_CONTEXT,
        	EncounterSecurityContext.UPDATE_HAS_CHARGEGROUP_CONTEXT
        };

        System.runAs(TestUtility.generateReadOnlyUser()) {
            for (EncounterSecurityContext context: allContexts) {
                try {
                    context.actionAllowed();
                    System.assert(false, 'Expected permission to be denied for ' + context);
                } catch (SecurityUtils.SecurityException ex) {
                    System.debug('SecurityException : ' + ex);
                } catch (Exception e) {
                    System.assert(false, 'Expected SecurityUtils.SecurityException to be thrown, but got ' + e);
                }
            }
        }
    }
}