src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Notes__c</fullName>
        <description>cannot delete</description>
        <label>Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>Id number</description>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Balance (Deprecated)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Export_Date__c</fullName>
        <label>Export Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fail_Date__c</fullName>
        <description>Fail Date</description>
        <label>Fail Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes (Deprecated)</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Payment</description>
        <label>Payment</label>
        <referenceTo>Payment__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Tranaction_Types</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>Date and Time stamp</description>
        <label>Post Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionSecurityContext.cls
/**
 * This class is use for Security Context of Transaction object
 **/
 
public with sharing class TransactionSecurityContext extends SecurityContext {
	
    // Field constants for Transaction object.
    private static final String AMOUNT = 'Amount__c';
    private static final String CHARGE_GROUP = 'Charge_Group__c';
    private static final String CREDIT_BALANCE = 'Credit_Balance__c';
    private static final String EXPORT_DATE = 'Export_Date__c';
    private static final String FAIL_DATE = 'Fail_Date__c';
    private static final String NAME = 'Name';
    private static final String NOTES = 'Notes__c';
    private static final String PAYMENT = 'Payment__c';
    private static final String POST_DATE = 'Post_Date__c';
    private static final String SIRONO_ID = 'Sirono_ID__c';
	
    // The fields for inserting Transaction in PayStaffWSUtill
    private static final Set<String> CREATE_FIELDS = new Set<String>{
    	SIRONO_ID, NAME, AMOUNT, POST_DATE, FAIL_DATE, EXPORT_DATE, NOTES, CREDIT_BALANCE, CHARGE_GROUP
    };
    
    // The fields for inserting Transaction with Payment in PayStaffWSUtill
    private static final Set<String> CREATE_WITH_PAYMENT_FIELDS = new Set<String>{
    	SIRONO_ID, NAME, AMOUNT, POST_DATE, FAIL_DATE, EXPORT_DATE, NOTES, CREDIT_BALANCE, CHARGE_GROUP, PAYMENT
    };
    
    /**
     * Constructor of class that assign variables based on parameters
     *
     * @param Set<String> fields - That contains Object's Fields
     * @param ACTION actionToPerform - That contains Action Name (Create/Update/Delete/Undelete)
     **/
    private TransactionSecurityContext(Set<String> fields, ACTION actionToPerform) {
        this.fieldsToCheck = fields;
        this.objectAction = actionToPerform;
    }
    
    /**
     * The context used to create a Transaction in the PayStaffWSUtill
     **/
    public static final TransactionSecurityContext CREATE_CONTEXT = new TransactionSecurityContext(CREATE_FIELDS, ACTION.OBJ_CREATE);
    
    /**
     * The context used to create a Transaction with Payment in the PayStaffWSUtill
     **/
    public static final TransactionSecurityContext CREATE_WITH_PAYMENT_CONTEXT = new TransactionSecurityContext(CREATE_WITH_PAYMENT_FIELDS, ACTION.OBJ_CREATE);
    
    /**
     * Override getObjectType method of SecurityContext class
     **/
    public override System.Type getObjectType() {
        return Transaction__c.class;
    }
}