src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ChargeGroupDao.cls
/**
 *
 * Database actions for Charge_Group__c objects
 *
 */

public with sharing class ChargeGroupDao extends AbstractDao {

    /**
     * Return the list of Charge_Group__c objects associated with the given sironoIds
     */
    public static List<Charge_Group__c> getBySironoIds(List<Decimal> sironoIds) {
        return [
                SELECT Id, Sirono_ID__c
                FROM Charge_Group__c
                WHERE Sirono_ID__c IN :sironoIds
        ];
    }

    public static void updateChargeGroups(List<Charge_Group__c> chargeGroups) {
        if (ChargeGroupSecurityContext.UPDATE_CONTEXT.actionAllowed()) {
            UPDATE chargeGroups;
        }
    }
}