src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Remaining_Balance__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentPlanTriggerBalanceCalcTest.cls
/*
 * @author Sirono
 * @version 1.0.1
 * @Date: 09-01-2016
 */

@isTest
public class PaymentPlanTriggerBalanceCalcTest {

    private static Contact g;
    private static Charge_Group__c cg1;
    private static Charge_Group__c cg2;
    private static Transaction__c txn;

    static void init() {

        g = TestUtility.GenerateGuarantorContact();
        insert g;
        System.debug('G id: ' + g.Id);

        cg1 = TestUtility.generateChargeGroup(g.Id, null, 1214);
        insert cg1;

        txn = TestUtility.generateTransaction(cg1, 2300, 'Service');
        insert txn;
    }

    @isTest
    static void testCreatePlan() {

        init();

        System.debug('G id: ' + g.Id);
        //Create a payment plan
        Payment_Plan__c pp = TestUtility.generatePaymentPlan(g);
        insert pp;

        Test.startTest();
        //with one chargegroup
        cg1.Payment_Plan__c = pp.Id;
        update cg1;
        Test.stopTest();

        pp = [SELECT Id, Remaining_Balance__c FROM Payment_Plan__c WHERE Id = :pp.Id];
        System.debug('pp.Payable_Amount__c: ' + pp.Payable_Amount__c);
        System.debug('txnAmount: ' + txn.Amount__c);
        //confirm the payable amount is what we expect
        System.assert(pp.Remaining_Balance__c == txn.Amount__c, 'PaymentPlan value is incorrect');
    }

    @isTest
    static void testAddPayment() {
        init();

        //Create a payment plan
        Payment_Plan__c pp = TestUtility.generatePaymentPlan(g);
        insert pp;

        cg1.Payment_Plan__c = pp.Id;
        update cg1;

        //Start Test Context, to reset all Governor limits
        Test.startTest();
        //Add a $50 credit to the cg
        Transaction__c txn2 = TestUtility.generateTransaction(cg1, -50, 'Credit');
        insert txn2;
        //Finish Test
        Test.stopTest();

        //Get the db values to compare
        Transaction__c[] txns = new Transaction__c[]{
                txn, txn2
        };
        AggregateResult[] sums = [SELECT SUM(Amount__c)tot FROM Transaction__c WHERE Id IN :txns];
        pp = [SELECT Id, Remaining_Balance__c FROM Payment_Plan__c WHERE Id = :pp.Id];
        Decimal txnTotal = (Decimal) sums[0].get('tot');

        System.assert(pp.Remaining_Balance__c == txnTotal, 'PaymentPlan value is incorrect');
    }
}