src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Pre_Collection_Sent__c</fullName>
        <description>Date pre-collections notice was sent (if applicable).</description>
        <label>Pre Collection Sent</label>
        <type>Date</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Delinquent_Balance__c</fullName>
        <label>Delinquent Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Delinquent_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Overdue_Balance__c</fullName>
        <label>Overdue Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Overdue_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PreCollectionSchedulerBatch.cls
/*
 * @author Sirono
 * @version 1.0.1
 * @Date: 05-30-2016
  
ADDITION: any {Charge Group}.{Pre Collection Sent} = Today and
{Guarantor}.{Overdue Balance} + {Guarantor}.{Delinquent Balance} <= -100 and
{Guarantor}.{Overdue Balance} + {Guarantor}.{Delinquent Balance} > -5000

Sirono : 08-30-2016 - #128375287 Update Salesforce Campaign Names

*/
public with sharing class PreCollectionSchedulerBatch implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    public Campaign callList;
    public Set<Id> existingMembers;

    public void execute(SchedulableContext bc) {
        Database.executeBatch(new PreCollectionSchedulerBatch(), 200);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        //Sirono : 08-30-2016 - #128375287 Update Salesforce Campaign Names
        Map<String, String> mapCampaignMapping = CaseUtil.campaignMapping(new Set<String>{
                'PreCollections'
        });
        string preCollection = mapCampaignMapping.get('PreCollections');

        for (Campaign cl : [Select Id, Name From Campaign Where Name = :preCollection and isActive = true]) {
            callList = cl;
        }
        if (callList != null) {
            existingMembers = new Set<Id>();
            for (CampaignMember cm : [Select Id, ContactId From CampaignMember Where CampaignId = :callList.Id AND ContactId != null]) {
                existingMembers.add(cm.ContactId);
            }

            return Database.getQueryLocator([Select Id, FirstName From Contact Where RecordType.Name = 'Guarantor' AND ID NOT IN :existingMembers]);
        } else {
            return Database.getQueryLocator([Select Id, FirstName From Contact Where RecordType.Name = 'Guarantor-DO-NOT-EXIST']);
        }
    }

    //adding new campaign members
    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<Contact> guarantors = (List<Contact>) scope;
        Date dt = System.today();
        if (callList != null) {
            List<CampaignMember> memberList = new List<CampaignMember>();
            for (Charge_Group__c cg : [
                    Select Id, Name, Guarantor_Name__c, Pre_Collection_Sent__c, Guarantor_Name__r.Overdue_Balance__c, Guarantor_Name__r.Delinquent_Balance__c
                    From Charge_Group__c
                    WHERE Guarantor_Name__c IN :guarantors AND Pre_Collection_Sent__c = :dt
            ]) {
                Double bal = cg.Guarantor_Name__r.Overdue_Balance__c + cg.Guarantor_Name__r.Delinquent_Balance__c;
                System.debug('bal' + bal);
                if (bal <= -100 && bal > -5000 && !existingMembers.contains(cg.Guarantor_Name__c)) {
                    existingMembers.add(cg.Guarantor_Name__c);
                    memberList.add(new CampaignMember(CampaignId = callList.Id, ContactId = cg.Guarantor_Name__c, Status = 'Sent'));
                }
            }

            if (memberList.size() > 0) {
                insert memberList;
            }
        }
    }

    public void finish(Database.BatchableContext bc) {

    }
}