src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>This is the external Charge Group iD</description>
        <externalId>true</externalId>
        <label>ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <description>Financial transaction details</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount of case or payment</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Group__c</fullName>
        <description>Charge Group</description>
        <label>Charge Group</label>
        <referenceTo>Charge_Group__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Credit_Balance__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Balance (Deprecated)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Export_Date__c</fullName>
        <label>Export Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Fail_Date__c</fullName>
        <description>Fail Date</description>
        <label>Fail Date (Deprecated)</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Post_Date__c</fullName>
        <description>Date and Time stamp</description>
        <label>Post Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <externalId>true</externalId>
        <label>Sirono ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Transaction</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TransactionJSONParser.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

public with sharing class TransactionJSONParser extends AbstractSironoJSONParser {

    @TestVisible
    private class TransactionJSON {
        public String url;
        public Integer amount;
        public String post_date;
        public String fail_date;
        public String export_date;
        //noinspection ApexUnusedDeclaration
        public String created_at;
        //noinspection ApexUnusedDeclaration
        public String modified_at;
        public String method;
        public String notes;
        public Boolean credit_balance;
        public String payment;
        public String chargegroup;
    }

    private String jsonString;

    public TransactionJSONParser(String jsonString) {
        this.jsonString = jsonString;
        this.jsonString = this.jsonString.replace('_credit_balance', 'credit_balance');
        this.jsonString = ensureJsonList(this.jsonString);
        System.debug('TransactionJSON jsonString: ' + this.jsonString);
    }

    private Datetime parseDatetime(String str) {

        if (!String.isBlank(str)) {
            String[] parts = str.split('T');
            String[] timeParts = parts[1].replace('.', ':').split(':');

            return Datetime.newInstance(
                    Date.valueOf(parts[0]),
                    Time.newInstance(
                            Integer.valueOf(timeParts[0]),
                            Integer.valueOf(timeParts[1]),
                            Integer.valueOf(timeParts[2]),
							//There are no milliseconds when the time is 00:00:00
                            timeParts.size() == 4 ? Integer.valueOf(timeParts[3]) : 0));
        }
        return null;
    }

    public List<Transaction__c> parse() {

        List<Transaction__c> txns = new List<Transaction__c>();

        List<TransactionJSON> txnJsons =
                (List<TransactionJSON>) System.JSON.deserialize(jsonString, List<TransactionJSON>.class);

        for (TransactionJSON txnJson : txnJsons) {
            Transaction__c txn = new Transaction__c();
            String txnSironoId = parseSironoId(txnJson.url, RestClientConstants.TRANSACTION_URL_RESOURCE_TYPE);

            txn.Sirono_ID__c = Decimal.valueOf(txnSironoId);
            txn.Name = txnJson.method + '-' + txnSironoId;
            txn.Amount__c = convertToDollarsNegative(txnJson.amount);
            txn.Post_Date__c = parseDatetime(txnJson.post_date);
            txn.Fail_Date__c = parseDatetime(txnJson.fail_date);
            txn.Export_Date__c = parseDatetime(txnJson.export_date);
            txn.Credit_Balance__c = txnJson.credit_balance;

            if (txnJson.chargegroup != null) {
                String cgSironoId = parseSironoId(txnJson.chargegroup, RestClientConstants.CHARGE_GROUP_URL_RESOURCE_TYPE);
                txn.Charge_Group__r = new Charge_Group__c(Sirono_ID__c = Decimal.valueOf(cgSironoId));
            }

            txns.add(txn);
        }

        return txns;
    }
}