src/objects/Charge_Group__c.object
<CustomObject>
    <description>Charge Group details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if active account</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Charge Groups (Guarantor)</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Paymentplan ID</description>
        <label>Payment Plan</label>
        <referenceTo>Payment_Plan__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pre_Collection_Sent__c</fullName>
        <description>Date pre-collections notice was sent (if applicable).</description>
        <label>Pre Collection Sent</label>
        <type>Date</type>
    </fields>
    <label>Charge Group</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Charge_Group__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>A Chargegroup can only have one encounter; multiple chargegroups can have the same encounter</description>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Charge Groups</relationshipLabel>
        <relationshipName>Charge_Groups</relationshipName>
        <type>Lookup</type>
    </fields>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Delinquent_Balance__c</fullName>
        <label>Delinquent Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Delinquent_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Overdue_Balance__c</fullName>
        <label>Overdue Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Overdue_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Service__c</fullName>
        <label>Date of Service</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Liability__c</fullName>
        <label>Liability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Patient)</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collected_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collected By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delinquent_Date__c</fullName>
        <description>Date of deliquency</description>
        <label>Delinquent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Collected_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Collected By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Payment_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delinquent_Date__c</fullName>
        <description>Date of deliquency</description>
        <label>Delinquent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor_Name__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CallListUtilities.cls
/**
 * Call List utilities.
 *
 * There are Security Context Select and Delete exceptions in this class primarilly around Campaign Members.
 * The methods here are use in trigger handlers that can be fired due to portal users executing actions on payment
 * plans (Pay/create/delete/etc).  The SecurityContext check were removed b/c it is an intentional action that any user
 * should be able update the associated object when interacting with PaymentPlans from the portal.
 */

public with sharing class CallListUtilities {

    //Remove the Campaign Members for the pre collection
    public static void preCollectionCallListRemoval(Set<Id> contactIds) {
        Set<Id> membersToremove = new Set<Id>();
        if (ContactSecurityContext.CU_SELECT_CONTEXT.actionAllowed() &&
                ChargeGroupSecurityContext.SELECT_CONTEXT.actionAllowed()) {
            for (Contact c: [
                    SELECT Id, Overdue_Balance__c, Delinquent_Balance__c, (
                            SELECT Id, Pre_Collection_Sent__c
                            FROM Charge_Groups__r
                            WHERE Pre_Collection_Sent__c != null
                    )
                    FROM Contact
                    WHERE Id IN :contactIds
            ]) {

                Decimal balToCheck = 0;
                if (c.Overdue_Balance__c != null) balToCheck += c.Overdue_Balance__c;
                if (c.Delinquent_Balance__c != null) balToCheck += c.Delinquent_Balance__c;
    
                if (c.Charge_Groups__r.size() == 0
                        || balToCheck > -100 || balToCheck < -5000) {
                    membersToremove.add(c.Id);
                }
            }
        }

        //Sirono : 08-30-2016 - #128375287 Update Salesforce Campaign Names
        Map<String, String> mapCampaignMapping = CaseUtil.campaignMapping(new Set<String>{
                'PreCollections'
        });
        string preCollection = mapCampaignMapping.get('PreCollections');

        // NOTE: The read access check for CampaignMember is skipped here in order allow Community Profile users
        // to create/delete Payment plans.
        List<CampaignMember> cmListToRemove = new List<CampaignMember>([
            SELECT Id, ContactId, CampaignId
            FROM CampaignMember
            WHERE ContactId = :membersToremove
            AND Campaign.Name = :preCollection
        ]);
        if (cmListToRemove.size() > 0) {
            // NOTE: could be triggered for portal user so removing delete check
            DELETE cmListToRemove;
        }
    }

    //Remove the Campaign Members for the Early Out case.
    public static void earlyOutCallListRemoval(List<Contact> contacts) {
        Set<Id> membersToremove = new Set<Id>();
        for (Contact c : contacts) {
            Decimal balToCheck = 0;
            if (c.Overdue_Balance__c != null) balToCheck += c.Overdue_Balance__c;
            if (c.Delinquent_Balance__c != null) balToCheck += c.Delinquent_Balance__c;

            if (balToCheck == 0
                    || balToCheck > -100 || balToCheck < -5000) {
                membersToremove.add(c.Id);
            }
        }

        //Sirono : 08-30-2016 - #128375287 Update Salesforce Campaign Names
        Map<String, String> mapCampaignMapping = CaseUtil.campaignMapping(new Set<String>{
                'Early-out'
        });
        string earlyOut = mapCampaignMapping.get('Early-out');

        // NOTE: The read access check for CampaignMember is skipped here in order allow Community Profile users
        // to create/delete Payment plans.
        List<CampaignMember> cmListToRemove = new List<CampaignMember>([
            SELECT Id, ContactId, CampaignId
            FROM CampaignMember
            WHERE ContactId = :membersToremove
            AND Campaign.Name = :earlyOut
        ]);
        if (cmListToRemove.size() > 0) {
            // NOTE: could be triggered for portal user so removing delete check
            DELETE cmListToRemove;
        }
    }

    //Remove the Campaign Members for the Delinquent case.
    public static void delinquentPaymentPlanCallListRemoval(Set<Id> contactIds) {
        Set<Id> membersToremove = new Set<Id>();
        if (ContactSecurityContext.CU_SELECT_CONTEXT.actionAllowed() &&
                PaymentPlanSecurityContext.CLU_SELECT_CONTEXT.actionAllowed()) {
            for (Contact c: [
                    SELECT Id, (
                            SELECT Id, Delinquent_Date__c, Active__c
                            FROM Payment_Plans__r
                            WHERE Delinquent_Date__c != null OR Active__c = true
                    )
                    FROM Contact
                    WHERE Id IN :contactIds
            ]) {
                if (c.Payment_Plans__r.size() == 0) {
                    membersToremove.add(c.Id);
                }
            }
        }

        //Sirono : 08-30-2016 - #128375287 Update Salesforce Campaign Names
        Map<String, String> mapCampaignMapping = CaseUtil.campaignMapping(new Set<String>{
                'Delinquent Payment Plans'
        });
        string delinquent = mapCampaignMapping.get('Delinquent Payment Plans');

        // NOTE: The read access check for CampaignMember is skipped here in order allow Community Profile users
        // to create/delete Payment plans.
        List<CampaignMember> cmListToRemove = new List<CampaignMember>([
            SELECT Id, ContactId, CampaignId
            FROM CampaignMember
            WHERE ContactId = :membersToremove
            AND Campaign.Name = :delinquent
        ]);
        if (cmListToRemove.size() > 0) {
            // NOTE: could be triggered for portal user so removing delete check
            DELETE cmListToRemove;
        }
    }

    //Remove the Campaign Members for the Pre-Service case.
    public static void preServiceCallListRemoval(Set<Id> contactIds) {
        Set<Id> membersToremove = new Set<Id>();
        if (ContactSecurityContext.CU_SELECT_CONTEXT.actionAllowed() &&
                EncounterSecurityContext.CLU_SELECT_CONTEXT.actionAllowed()) {
            for (Contact c: [
                    SELECT Id, (
                            SELECT Id, Date_of_Service__c, Liability__c, Cancelled__c
                            FROM Encounters__r
                            WHERE Liability__c < 100 OR Date_of_Service__c != Today OR Cancelled__c = false
                    )
                    FROM Contact
                    WHERE Id IN :contactIds
            ]) {
                if (c.Encounters__r.size() == 0) {
                    membersToremove.add(c.Id);
                }
            }
        }

        //Sirono : 08-30-2016 - #128375287 Update Salesforce Campaign Names
        Map<String, String> mapCampaignMapping = CaseUtil.campaignMapping(new Set<String>{
                'PreService'
        });
        String preService = mapCampaignMapping.get('PreService');

        // NOTE: The read access check for CampaignMember is skipped here in order allow Community Profile users
        // to create/delete/pay Payment plans.
        List<CampaignMember> cmListToRemove = new List<CampaignMember>([
            SELECT Id, ContactId, CampaignId
            FROM CampaignMember
            WHERE ContactId = :membersToremove
            AND Campaign.Name = :preService
        ]);
        if (cmListToRemove.size() > 0) {
            // NOTE: could be triggered for portal user so removing delete check
            DELETE cmListToRemove;
        }
    }
}