src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Add_to_Payment_Plan__c</fullName>
        <formula>AND(Payment_Plan_Balance__c &gt; 0, Payment_Plan_Balance__c &lt;&gt; Invoiced_Balance__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Add to Payment Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent_Invoices__c</fullName>
        <description>Count of delinquent invoices</description>
        <label>Delinquent Invoices</label>
        <summaryFilterItems>
            <field>Invoice__c.Invoice_Status_Index__c</field>
            <operation>equals</operation>
            <value>7</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoiced_Balance__c</fullName>
        <label>Invoiced Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Invoiced_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Outstanding_Invoices__c</fullName>
        <description>Count of outstanding invoices</description>
        <label>Outstanding Invoices</label>
        <summaryFilterItems>
            <field>Invoice__c.Invoice_Status_Index__c</field>
            <operation>greaterOrEqual</operation>
            <value>4</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Overdue_Invoices__c</fullName>
        <description>Count of Overdue invoices</description>
        <label>Overdue Invoices</label>
        <summaryFilterItems>
            <field>Invoice__c.Invoice_Status_Index__c</field>
            <operation>equals</operation>
            <value>6</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
    <fields>
        <fullName>Guarantor_Status__c</fullName>
        <formula>IF(RecordType.Name == &apos;Guarantor&apos;,
CASE(Invoice_Status_Rollup2__c,
9, &quot;Delinquent&quot;,
8, &quot;Overdue&quot;,
7, &quot;Due&quot;,
6, &quot;On Payment Plan&quot;,
5, &quot;Paid&quot;,
4, &quot;Paid&quot;,
3, &quot;Paid&quot;,
2, &quot;Unknown&quot;,
1, &quot;Paid&quot;,
0, &quot;Paid&quot;,
&quot;Error&quot;),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Guarantor)</relationshipLabel>
        <relationshipName>Guarantor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <formula>CASE(Invoice_Status_Index__c,
9, &quot;Delinquent&quot;,
8, &quot;Overdue&quot;,
7, &quot;Due&quot;,
6, &quot;On Payment Plan&quot;,
5, &quot;Paid&quot;,
4, &quot;Paid&quot;,
3, &quot;Paid&quot;,
2, &quot;Unknown&quot;,
1, &quot;Invoice Voided&quot;,
0, &quot;Invoice Voided&quot;,
&quot;Error&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Status</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Installments_Completed__c</fullName>
        <formula>Original_Installment_Count__c -  Remaining_Installment_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installments Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NextPaymentDate__c</fullName>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Installment_Count__c</fullName>
        <description>payment installment months</description>
        <label>Original Installments</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Standing__c</fullName>
        <description>PPS is the status of the ACTIVE payment plan.

            Options: Past Due, In Error, Good Standing</description>
        <formula>IF(Active__c=FALSE,&quot;&quot;,IF(Delinquent__c = TRUE, &quot;Past Due&quot;, IF(Has_Error__c = TRUE, &quot;In Error&quot;, &quot;Good Standing&quot;)))</formula>
        <label>Payment Plan Standing</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Plan Number type small int</description>
        <label>Plan Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HeaderController.cls
public with sharing class HeaderController {
	public static String WARNING_MESSAGE 	    = 'Your account has overdue invoices. Please pay the balance now or set up a payment plan to avoid becoming delinquent.\n If you have any questions about the bill, please contact the Customer Service Center at (925)-231-2502.';
	public static String DELINQUENT_MESSAGE     = 'This account has delinquent invoices. Delinquent invoices will be sent to a collection agency if payment arrangements are not made within the next 30 days. Please pay the balance now or set up a payment plan.'; 
	public static String PASTDUE_MESSAGE        = ' We have not received your latest payment plan installment. Please pay your previous installment amount now or pay your account in full to avoid payment plan cancellation.'; 
	public static String PASTDUE_MANUAL_MESSAGE = ' We have not received your latest payment plan installment. Please pay your previous installment amount now or pay your account in full to avoid payment plan cancellation. If you have any questions about the bill, call the Customer Service Center at (925)-231-2502.';
	public static String ERROR_MESSAGE		    = ' Your latest payment plan installment failed. Please update your payment method or pay your previous installment amount now to keep your account current.';
	public static String DUE_STATUS  	  	    = 'Due';
	public static String OVERDUE_STATUS  	    = 'Overdue';
	public static String DELINQUENT_STATUS      = 'Delinquent';
	public static String PAYMENT_PLAN_STATUS    = 'On Payment Plan';
	public static String PLAN_STANDING_ERROR    = 'In Error';
	public static String PLAN_STANDING_GOOD     = 'Good standing';

	@AuraEnabled
	public static GuarantorWrapper getAllHeaderInfo() {
		return new GuarantorWrapper(UserInfo.getUserId());
	}

	@AuraEnabled
	public static User getUserInfo() {
		return 	[
					SELECT 
							Id,
							Contact.FirstName,
							Contact.Profile_Pointer_ID__c 
							FROM User
							WHERE Id = :UserInfo.getUserId()
				];
	}

	public class GuarantorWrapper {
		@AuraEnabled public Contact contact 				{get;set;}
		@AuraEnabled public Invoice__c invoiceOverdue 		{get;set;}
		@AuraEnabled public String messageInfo 				{get;set;}
		@AuraEnabled public String pastDueMessage 			{get;set;}
		@AuraEnabled public Payment_Plan__c paymentPlan 	{get;set;}
		@AuraEnabled public Integer newEstimatesCount	 	{get;set;}
		@AuraEnabled public Boolean version2 				{get;set;}
		@AuraEnabled public Boolean version3 				{get;set;}
		@AuraEnabled public Boolean version4 				{get;set;}
		@AuraEnabled public Boolean isInstallAmountView 	{get;set;}

		public GuarantorWrapper(Id userId) {
			this.messageInfo = '';
			this.invoiceOverdue = new Invoice__c();
			User user = [SELECT Id, ContactId FROM User WHERE Id = :userId];
			if(user.ContactId != null) {
				this.contact = [
									SELECT 
											Id,
											FirstName,
											Guarantor__c,
											Guarantor_Status__c,
											Invoiced_Balance__c,
											Overdue_Invoices__c,
											Outstanding_Invoices__c,
											Delinquent_Invoices__c,
											Add_to_Payment_Plan__c
									FROM 	Contact
									WHERE 	Id = :user.ContactId
				];

				List<Invoice__c> listInvoices = [
													SELECT
															Id,
															Due_Date__c
													FROM 	Invoice__c
													WHERE 	Guarantor__c = :contact.Id
														AND Invoice_Status__c = :DUE_STATUS
													ORDER BY CreatedDate 
													LIMIT 1
				];
				List<Payment_Plan__c> paymentPlans = [
													SELECT
															Id,
															Payment_Plan_Standing__c,
															NextPaymentDate__c,
															Installment_Amount__c,
															Installments_Completed__c,
															Original_Installment_Count__c,
															Active__c,
															Plan_Type__c
													FROM 	Payment_Plan__c
													WHERE	Guarantor__c = :user.ContactId
													ORDER BY Active__c DESC, LastModifiedDate DESC
													LIMIT 1
				];

				this.newEstimatesCount = [
											SELECT 
													COUNT()
											FROM 	Encounter__c
											WHERE   Guarantor__c = :user.ContactId AND 
													CreatedDate >= :Datetime.now().addDays(-30)
				];

				if(listInvoices.size() > 0 && listInvoices[0] != null) {
					this.invoiceOverdue = listInvoices[0];
				}
				if(paymentPlans.size() > 0 && paymentPlans[0] != null) {
					this.paymentPlan = paymentPlans[0];
				}
				if(contact.Guarantor_Status__c == OVERDUE_STATUS) {
					this.messageInfo = WARNING_MESSAGE;
				} else if(contact.Guarantor_Status__c == DELINQUENT_STATUS) {
					this.messageInfo = DELINQUENT_MESSAGE;
				}
				if(paymentPlan.Active__c && paymentPlan.Payment_Plan_Standing__c == 'Past Due' && paymentPlan.Plan_Type__c == 'Automatic') {
					this.messageInfo += PASTDUE_MESSAGE;
				}
				if(paymentPlan.Active__c && paymentPlan.Payment_Plan_Standing__c == 'Past Due' && paymentPlan.Plan_Type__c == 'Manual') {
					this.messageInfo += PASTDUE_MANUAL_MESSAGE;
				}
				if(paymentPlan.Active__c && paymentPlan.Plan_Type__c == 'Automatic' && paymentPlan.Payment_Plan_Standing__c == 'In Error') {
					this.messageInfo += ERROR_MESSAGE;
				}

				this.version2 = ((this.contact.Guarantor_Status__c == 'Due' || this.contact.Guarantor_Status__c == 'Overdue' 
					|| this.contact.Guarantor_Status__c == 'Delinquent') && this.contact.Add_to_Payment_Plan__c == false) ? true : false;
				this.version3 = ((((this.contact.Guarantor_Status__c == 'Due' || this.contact.Guarantor_Status__c == 'Overdue' 
					|| this.contact.Guarantor_Status__c == 'Delinquent') && this.contact.Add_to_Payment_Plan__c == true) 
						|| this.contact.Guarantor_Status__c == 'On Payment Plan') && (this.paymentPlan != null && this.paymentPlan.Payment_Plan_Standing__c == 'Good Standing')) ? true : false;
				this.version4 = ((((this.contact.Guarantor_Status__c == 'Due' || this.contact.Guarantor_Status__c == 'Overdue' 
					|| this.contact.Guarantor_Status__c == 'Delinquent') && this.contact.Add_to_Payment_Plan__c == true) 
						|| this.contact.Guarantor_Status__c == 'On Payment Plan') && (this.paymentPlan != null && this.paymentPlan.Payment_Plan_Standing__c != 'Good Standing')) ? true : false;
				this.isInstallAmountView = (((this.contact.Guarantor_Status__c == 'Due' || this.contact.Guarantor_Status__c == 'Overdue' || this.contact.Guarantor_Status__c == 'Delinquent') 
					&& this.contact.Add_to_Payment_Plan__c == true) || this.contact.Guarantor_Status__c == 'On Payment Plan') ? true : false;
			}
		}
	}
}