src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Delinquent_Balance__c</fullName>
        <label>Delinquent Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Delinquent_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Overdue_Balance__c</fullName>
        <label>Overdue Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Overdue_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Invoice_Date__c</fullName>
        <description>Invoice Date</description>
        <label>Invoice Date</label>
        <type>Date</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Statement__c.object
<CustomObject>
    <description>Guarantor Statement details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Statements</relationshipLabel>
        <relationshipName>Statements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Statement_Date__c</fullName>
        <description>Date of the statement</description>
        <label>Statement Date</label>
        <type>Date</type>
    </fields>
    <label>Statement</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Statements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EarlyOutSchedulerBatch.cls
/*
ADDITION: any {Invoice}.{Invoice Date} + 50 = Today and 
{Guarantor}.{Overdue Balance} < 0 and 
{Guarantor}.{Overdue Balance} + {Guarantor}.{Delinquent Balance} <= -100 and
{Guarantor}.{Overdue Balance} + {Guarantor}.{Delinquent Balance} > -5000 and
Count({Guarantor}.{Statement}.{Date} >= {Invoice}.{Invoice Date}) > 0
*/
global with sharing class EarlyOutSchedulerBatch
        implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    global Campaign callList;
    global Set<Id> existingMembers;

    global void execute(SchedulableContext SC) {
        Database.executeBatch(new EarlyOutSchedulerBatch(), 200);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        for (Campaign cl : [Select Id, Name From Campaign Where Name = 'Early Out' and isActive = true]) {
            callList = cl;
        }
        if (callList != null) {
            existingMembers = new Set<Id>();
            for (CampaignMember cm : [
                    Select Id, ContactId
                    From CampaignMember
                    Where CampaignId = :callList.Id AND ContactId != null
            ]) {
                existingMembers.add(cm.ContactId);
            }

            return Database.getQueryLocator([
                    Select Id, FirstName, LastName
                    From Contact
                    Where RecordType.Name = 'Guarantor' AND ID NOT IN :existingMembers
            ]);
        } else {
            return Database.getQueryLocator([Select Id, FirstName From Contact Where RecordType.Name = 'Guarantor-DO-NOT-EXIST']);
        }
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Contact> guarantors = (List<Contact>) scope;

        Map<Id, Contact> guarantorMap = new Map<Id, Contact>([
                Select Id, (Select Id, Name, Statement_Date__c From Statements__r Order By Statement_Date__c DESC Limit 1)
                From Contact
                Where Id IN :guarantors
        ]);

        Date dt = System.today().addDays(-50);
        if (callList != null) {
            List<CampaignMember> memberList = new List<CampaignMember>();
            for (Invoice__c invoice : [
                    Select Id, Name, Guarantor_Name__c, Invoice_Date__c,
                            Guarantor_Name__r.Overdue_Balance__c, Guarantor_Name__r.Delinquent_Balance__c
                    From Invoice__c
                    WHERE Guarantor_Name__c IN :guarantors AND Invoice_Date__c = :dt
            ]) {
                Double bal = invoice.Guarantor_Name__r.Overdue_Balance__c + invoice.Guarantor_Name__r.Delinquent_Balance__c;
                if (invoice.Guarantor_Name__r.Overdue_Balance__c < 0 && bal <= -100 && bal > -5000
                        && guarantorMap.containsKey(invoice.Guarantor_Name__c)
                        && guarantorMap.get(invoice.Guarantor_Name__c).Statements__r != null
                        && guarantorMap.get(invoice.Guarantor_Name__c).Statements__r.size() != 0
                        && guarantorMap.get(invoice.Guarantor_Name__c).Statements__r.get(0).Statement_Date__c > invoice.Invoice_Date__c
                        && !existingMembers.contains(invoice.Guarantor_Name__c)) {
                    existingMembers.add(invoice.Guarantor_Name__c);
                    memberList.add(new CampaignMember(CampaignId = callList.Id, ContactId = invoice.Guarantor_Name__c, Status = 'Sent'));
                }
            }

            if (memberList.size() > 0) {
                insert memberList;
            }
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}