src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
    <fields>
        <fullName>Estimate_Balance__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Sum of all Estimates for the guarantor</description>
        <label>Estimate Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <formula>IF( Has_Chargegroup__c, 0, Patient_Portion__c - Total_Payments__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Payments__c</fullName>
        <label>Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

call-center/src/objects/Encounter__c.object
    <fields>
        <fullName>Billed_Charge_Group_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Billed Charge Group Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

call-center/src/objects/Encounter__c.object
    <fields>
        <fullName>Encounter_Substatus__c</fullName>
        <formula>IF(OR(ISPICKVAL(Status__c, &quot;In Process&quot;), ISPICKVAL(Status__c, &quot;Error&quot;)), &quot;Unavailable&quot;,
IF(ISPICKVAL(Status__c, &quot;Cancelled&quot;), &quot;Cancelled&quot;,
IF(AND(ISPICKVAL(Status__c, &quot;Ready&quot;), Billed_Charge_Group_Count__c &gt; 0), &quot;Serviced&quot;,
IF(AND(ISPICKVAL(Status__c, &quot;Ready&quot;), Balance__c &gt; 0, Billed_Charge_Group_Count__c == 0), &quot;Payment Due&quot;,
IF(AND(ISPICKVAL(Status__c, &quot;Ready&quot;), Balance__c &lt;= 0, Billed_Charge_Group_Count__c == 0), &quot;Paid&quot;, &quot;&quot;)
)
)
)
)</formula>
        <label>Encounter Substatus</label>
        <type>Text</type>
    </fields>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer of the account</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

src/classes/EncounterUtil.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Utility class for setting the Total_Payments and BilledChargeGroupCount
 * These methods are invoked when either a Charge_Group or Payment's Encounter changes
 * TODO: remove without sharing
 */
public with sharing class EncounterUtil {

    private static String ENCOUNTERID = 'encounterId';
    private static String OBJ = 'obj';
    private static String TOTAL = 'Total';

    /**
      * Update the Total_Payments field in the Encounters with the total of
      * all associated Payments
     */
    public static void updateTotalPayments(Set<Id> encounterIds) {
        if (encounterIds.contains(null)) {
            encounterIds.remove(null);
        }

        if (encounterIds.size() == 0) {
            return;
        }

        Map<Id, Encounter__c> encountersToUpdate = new Map<Id, Encounter__c>();
        for (Id id : encounterIds) {
            encountersToUpdate.put(id, new Encounter__c(Id = id, Total_Payments__c = 0));
        }
        if (PaymentSecurityContext.EU_SELECT_CONTEXT.actionAllowed()) {
            // Get the SUM of all the associated payments
            AggregateResult[] results = [
                    SELECT Encounter__c obj, SUM(Amount__c) Total
                    FROM Payment__c
                    WHERE Encounter__c IN :encounterIds
                    GROUP BY Encounter__c
            ];

            for (AggregateResult ar : results) {
                Encounter__c enc = new Encounter__c(Id=(Id)ar.get(OBJ));
                enc.Total_Payments__c = (Decimal) ar.get(TOTAL);

                encountersToUpdate.put(enc.Id, enc);
            }

            if (EncounterSecurityContext.UPDATE_CONTEXT.actionAllowed()) {
                UPDATE encountersToUpdate.values();
            }
            updateAssociatedGuarantors(encounterIds);
        }
    }

    /*
     * Collect the guarantor Id's from the given encounters and set the
     * Estimate_Balance on each guarantor
     */
    private static void updateAssociatedGuarantors(Set<Id> encounterIds) {
        if (EncounterSecurityContext.EU_SELECT_CONTEXT.actionAllowed()) {
            List<Encounter__c> encountersWithGts = [
                    SELECT Id, Guarantor__c
                    FROM Encounter__c
                    WHERE Id IN :encounterIds
                    AND Guarantor__c != null
            ];

            Set<Id> gtIds = new Set<Id>();
            for (Encounter__c encounter: encountersWithGts) {
                gtIds.add(encounter.Guarantor__c);
            }
            updateGTEstimateBalances(gtIds);
        }
    }

    /**
     * Update the Estimate_Balance for each of the given guarantors
     *
     */
    public static void updateGTEstimateBalances(Set<Id> gtIds) {
        if (gtIds.contains(null)) {
            gtIds.remove(null);
        }

        if (gtIds.size() == 0) {
            return;
        }

        if (EncounterSecurityContext.EU_SELECT_CONTEXT_AGG.actionAllowed()) {
            // Get the SUM of the balances of the associated Encounters
            // there are no results for gtIds with no Encounters
            AggregateResult[] results = [
                    SELECT Guarantor__c obj, SUM(Balance__c) Total
                    FROM Encounter__c
                    WHERE Guarantor__c IN :gtIds
                    AND Guarantor__c != null
                    AND Encounter_Substatus__c = :Constants.EN_SUBSTATUS_PAYMENT_DUE
                    GROUP BY Guarantor__c
            ];

            Map<Id, Decimal> resultsMap = new Map<Id, Decimal>();
            for (AggregateResult ar : results) {
                resultsMap.put((Id) ar.get(OBJ), (Decimal)ar.get(TOTAL));
            }

            List<Contact> toUpdate = new List<Contact>();
            for (Id gtId : gtIds) {
                Contact gt = new Contact(Id = gtId);
                gt.RecordTypeId = RecordTypeUtil.guarantorRt;

                if (resultsMap.containsKey(gtId)) {
                    gt.Estimate_Balance__c = resultsMap.get(gtId);
                } else {
                    gt.Estimate_Balance__c = 0;
                }

                toUpdate.add(gt);
            }
            // Update Contacts.
            GuarantorService.updateGuarantorsWithEstimateBal(toUpdate);
        }
    }

    /**
     * Update the Billed_Charge_Group_Count__c field in the Encounters with the number of
     * all associated Charge Groups where Account_Status__c is Billed.
     *
     * @param Set<Id> encounterIds - the encounters to update
     **/
    public static void setBilledCGCount(Set<Id> encounterIds) {
        if (encounterIds.contains(null)) {
            encounterIds.remove(null);
        }

        if (encounterIds.isEmpty()) {
            return;
        }

        Map<Id, Encounter__c> encountersToUpdate = new Map<Id, Encounter__c>();
        for (Id id: encounterIds) {
            encountersToUpdate.put(id, new Encounter__c(Id = id, Billed_Charge_Group_Count__c = 0));
        }

        // Get Billed CG Count based on Encounter Ids. 
        List<AggregateResult> results = ChargeGroupService.getBilledCGCountByEncounterIds(encounterIds);

        for (AggregateResult ar: results) {
            Encounter__c enc = new Encounter__c(Id = (Id) ar.get(ENCOUNTERID));
            enc.Billed_Charge_Group_Count__c = (Integer) ar.get(TOTAL);

            encountersToUpdate.put(enc.Id, enc);
        }

        // Update Encounter records.
        EncounterService.updateBilledCGCount(encountersToUpdate.values());
    }
}