src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent_Date__c</fullName>
        <description>Date of deliquency</description>
        <label>Delinquent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor_Name__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payable_Amount__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DelinquentPaymentPlansSchedulerBatch.cls
/*
ADDITION: {Payment Plan}.{Delinquent Date} + 10 = Today and
{Payment Plan}.{Remaining Balance} < -100 and
{Payment Plan}.{Active} = TRUE
*/
global with sharing class DelinquentPaymentPlansSchedulerBatch
        implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    global Campaign callList;
    global Set<Id> existingMembers;

    global void execute(SchedulableContext SC) {
        Database.executeBatch(new DelinquentPaymentPlansSchedulerBatch(), 200);
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        for (Campaign cl : [Select Id, Name From Campaign Where Name = 'Delinquent Payment Plans' and isActive = true]) {
            callList = cl;
        }
        if (callList != null) {
            existingMembers = new Set<Id>();
            for (CampaignMember cm : [
                    Select Id, ContactId
                    From CampaignMember
                    Where CampaignId = :callList.Id AND ContactId != null
            ]) {
                existingMembers.add(cm.ContactId);
            }

            return Database.getQueryLocator([
                    Select Id, FirstName, LastName
                    From Contact
                    Where RecordType.Name = 'Guarantor' AND ID NOT IN :existingMembers
            ]);
        } else {
            return Database.getQueryLocator([Select Id, FirstName From Contact Where RecordType.Name = 'Guarantor-DO-NOT-EXIST']);
        }
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Contact> guarantors = (List<Contact>) scope;
        Date dt = System.today().addDays(-10);
        if (callList != null) {
            List<CampaignMember> memberList = new List<CampaignMember>();
            for (test__c pp : [
                    Select Id, Name, Guarantor_Name__c, Delinquent_Date__c, Payable_Amount__c, Active__c
                    From test__c
                    WHERE Guarantor_Name__c IN :guarantors AND Delinquent_Date__c = :dt
                    AND Payable_Amount__c < :-100 AND Active__c = true
            ]) {
                if (!existingMembers.contains(pp.Guarantor_Name__c)) {
                    existingMembers.add(pp.Guarantor_Name__c);
                    memberList.add(new CampaignMember(CampaignId = callList.Id, ContactId = pp.Guarantor_Name__c, Status = 'Sent'));
                }
            }

            if (memberList.size() > 0) {
                insert memberList;
            }
        }
    }

    global void finish(Database.BatchableContext BC) {

    }
}