src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor_Transaction_ID__c</fullName>
        <description>Id of the processor</description>
        <label>Processor Transaction ID</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <description>Credit card details</description>
    <fields>
        <fullName>Card_Type__c</fullName>
        <description>Type of Credit card used</description>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WorkWithPaymentsControllerTest.cls
@isTest
private class WorkWithPaymentsControllerTest {
	
	@isTest static void getPaymentHistoryTest() {
		User internalUser;
		System.runAs(new User(Id = UserInfo.getUserId(), UserRoleId = UserInfo.getUserRoleId())) {
			Profile profile = [
	            SELECT Id, Name
	            FROM Profile 
	            WHERE name = 'Guarantor Community'
	        ];

	        Account testAcc = new Account (
	        	Name = 'Test Account Name'
	        );
				insert testAcc;

	      	Contact guarantorContact = TestUtility.generateGuarantorContact();
	      	guarantorContact.AccountId = testAcc.Id;
	        insert guarantorContact;

	        internalUser = new User (
	        	Username = profile.Id + String.valueOf(System.now().millisecond()) + '@example.com',
	            ProfileId = profile.Id,
	            ContactId = guarantorContact.Id,
	            Alias = 'user' + System.now().millisecond(),
	            Email = profile.Id + '@example.com',
	            EmailEncodingKey = 'UTF-8',
	            LastName = 'Test',
	            CommunityNickname = profile.Id,
	            TimeZoneSidKey = 'America/Los_Angeles',
	            LocaleSidKey = 'en_US',
	            LanguageLocaleKey = 'en_US'
	        );
	  		insert internalUser;

	  		Map<String, String> recordTypeMap = new Map<String, String>();
	        for (RecordType recordType : [
                SELECT Id, Name
                FROM RecordType
                WHERE sObjectType = 'Payment_Method__c'
	        ]) {
	            recordTypeMap.put(recordType.Name, recordType.Id);
	        }

	        List<Payment_Method__c> lstPaymentMethod = new List<Payment_Method__c>();
	        Payment_Method__c paymentMethod1 = TestUtility.generatePaymentMethod(guarantorContact.Id, recordTypeMap.get('Credit Card'));
	        paymentMethod1.Card_Type__c = 'Visa';
	        paymentMethod1.Last_4__c = '1111';
        	insert paymentMethod1;
        	Payment_Method__c paymentMethod2 = TestUtility.generatePaymentMethod(guarantorContact.Id, recordTypeMap.get('Check/Cash'));
        	insert paymentMethod2;

	  		Payment__c payment1 = TestUtility.generateSironoPayment(guarantorContact.Id, 1234, 12);
	  		payment1.Payment_Method__c = paymentMethod1.Id;
	  		payment1.Method__c = 'Credit';
	        Payment__c payment2 = TestUtility.generateSironoPayment(guarantorContact.Id, 1235, 25);
	        payment2.Payment_Method__c = paymentMethod2.Id;
	  		payment2.Method__c = 'Check';
	  		payment2.Processor_Transaction_ID__c = '12345qwert';
	        List<Payment__c> lstPayment = new List<Payment__c>{payment1, payment2};
	        insert lstPayment;
	    }

	    System.runAs(internalUser) {
        	Test.startTest();

        	List<WorkWithPaymentsController.PaymentsWrapper> paymentsList = WorkWithPaymentsController.getPaymentHistory();
        	System.assertEquals(paymentsList.size(), 2);
        	for (WorkWithPaymentsController.PaymentsWrapper pw : paymentsList) {
        		if (pw.method == 'Credit') {
        			System.assertEquals(pw.description, 'Visa 1111');
        		} else {
        			System.assertEquals(pw.description, '12345qwert');
        		}
        	}
        	Test.stopTest();
        }
	}	
}