src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Service__c</fullName>
        <label>Date of Service</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Liability__c</fullName>
        <label>Liability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Patient)</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent_Date__c</fullName>
        <description>Date of deliquency</description>
        <label>Delinquent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payable_Amount__c</fullName>
        <label>Remaining Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PreServiceSchedulerBatchTest.cls
/*
 * @author Sirono 
 * @version 1.0.1
 * @Date: 09-02-2016
 * do the code coverage for the PreServiceSchedulerBatch class.
*/

@isTest
private class PreServiceSchedulerBatchTest {

    @isTest
    static void main() {
    contact con = TestUtility.generateGuarantorContact();
    insert con;

    contact con1 = TestUtility.generateGuarantorContact();
    con1.LastName = 'Test';
    con1.Profile_Pointer_Id__c = 123;
    insert con1;

    contact con2 = TestUtility.generatePatientContact();
    con2.LastName = 'Test';
    con2.Profile_Pointer_Id__c = 123456;
    con2.Guarantor__c =con1.Id;
    insert con2;

    Date dt = System.today().addDays(-10);

    test__c t = TestUtility.generatePaymentPlan(con.Id);
    t.Payable_Amount__c = -120;
    t.Active__c = true;
    t.Delinquent_Date__c = dt;
    insert t;

    test__c t1 = TestUtility.generatePaymentPlan(con1.Id);
    t1.Payable_Amount__c = -120;
    t1.Active__c = true;
    t1.Delinquent_Date__c = dt;
    insert t1;

    Campaign c = TestUtility.generateCampaign('PreService');
    c.isActive = true;
    insert c;

    CampaignMember cmm = new CampaignMember(CampaignId = c.Id, ContactId = con.Id, Status = 'Sent');
    insert cmm;

    Encounter__c encounter1 = TestUtility.generateEncounter(con.Id, -10, Date.today());
    encounter1.Patient__c = con2.Id;
    encounter1.Date_of_Service__c = System.today().addDays(2);
    encounter1.Liability__c = 101;
    encounter1.Cancelled__c = false;
    insert encounter1;

    encounter1 = TestUtility.generateEncounter(con1.Id, -10, Date.today());
    encounter1.Patient__c = con2.Id;
    encounter1.Date_of_Service__c = System.today().addDays(2);
    encounter1.Liability__c = 101;
    encounter1.Cancelled__c = false;
    insert encounter1;

    Test.startTest();
System.debug('encounter1' + encounter1);

PreServiceSchedulerBatch dpp = new PreServiceSchedulerBatch();

dpp.existingMembers = new Set<Id>();
system.schedule('schJob', '0 11 22 * 9 ?', dpp);
Test.stopTest();

List<ApexPages.Message> msgList = ApexPages.getMessages();
System.assertEquals(0, msgList.size());
}

//Cover Existing map
    @isTest 
    static void main1() {
contact con = TestUtility.generateGuarantorContact();
insert con;

contact con1 = TestUtility.generateGuarantorContact();
con1.LastName = 'Test';
con1.Profile_Pointer_Id__c = 123;
insert con1;

contact con2 = TestUtility.generatePatientContact();
con2.LastName = 'Test';
con2.Profile_Pointer_Id__c = 123456;
con2.Guarantor__c =con1.Id;
insert con2;

Date dt = System.today().addDays(-10);

test__c t = TestUtility.generatePaymentPlan(con.Id);
t.Payable_Amount__c = -120;
t.Active__c = true;
t.Delinquent_Date__c = dt;
insert t;

test__c t1 = TestUtility.generatePaymentPlan(con1.Id);
t1.Payable_Amount__c = -120;
t1.Active__c = true;
t1.Delinquent_Date__c = dt;
insert t1;

Campaign c = TestUtility.generateCampaign('PreService');
c.isActive = true;
insert c;

CampaignMember cmm = new CampaignMember(CampaignId = c.Id, ContactId = con.Id, Status = 'Sent');
insert cmm;

Encounter__c encounter1 = TestUtility.generateEncounter(con.Id, -10, Date.today());
encounter1.Patient__c = con2.Id;
encounter1.Date_of_Service__c = System.today().addDays(2);
encounter1.Liability__c = 101;
encounter1.Cancelled__c = false;
insert encounter1;

encounter1 = TestUtility.generateEncounter(con1.Id, -10, Date.today());
encounter1.Patient__c = con2.Id;
encounter1.Date_of_Service__c = System.today().addDays(2);
encounter1.Liability__c = 101;
encounter1.Cancelled__c = false;
insert encounter1;

Test.startTest();
System.debug('encounter1' + encounter1);
//insert cmm;

PreServiceSchedulerBatch dpp = new PreServiceSchedulerBatch();
Delete [Select id from CampaignMember];
System.debug('12212' + [Select id from CampaignMember]);
dpp.existingMembers = new Set<Id>();
system.schedule('schJob', '0 11 22 * 9 ?', dpp);
Test.stopTest();

List<ApexPages.Message> msgList = ApexPages.getMessages();
System.assertEquals(0, msgList.size());
}

    @isTest
    static void executBatch() {
Test.startTest();

PreServiceSchedulerBatch dppc = new PreServiceSchedulerBatch();
dppc.existingMembers = new Set<Id>();
Database.executeBatch(dppc);
Test.stopTest();

List<ApexPages.Message> msgList = ApexPages.getMessages();
System.assertEquals(0, msgList.size());
}
}