src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Encounter__c.object
<CustomObject>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

src/classes/PaymentServiceTest.cls
@isTest
public class PaymentServiceTest {
	/**
     * This method is used to test PaymentService.createNewPayment method
     **/
    @IsTest
    static void createNewPaymentTest() {
    	// Create Guarantor Contact record.
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        INSERT guarantorContact;

        // Create Encounter record.
        Encounter__c encounter = TestUtility.generateEncounter(guarantorContact.Id, 500, System.today());
        INSERT encounter;

        Test.startTest();
        PaymentService.createNewPayment(guarantorContact.Id, 123, encounter.Id, System.now(), null);
        
        List<Payment__c> paymentList = [
        	SELECT Id, Name 
        	FROM Payment__c
        ];
        // Check that record was created
        System.assertEquals(paymentList.size(), 1);
        Test.stopTest();
    }

    @IsTest
    public static void payChargeGroupsBuildRequestBodyTest {

        PaymentRequest pmtRequest = new PaymentRequest();
        pmtRequest.creditCardNumber = '';
        pmtRequest.cardHolderName = cInfo.cardHolderName;
        pmtRequest.expirationYear = cInfo.expirationYear.substring(2);
        pmtRequest.expirationMonth = cInfo.expirationMonth.substring(0,2);
        pmtRequest.cvv = cInfo.cvv;
        pmtRequest.amount = cInfo.amount;
        pmtRequest.address = cInfo.address;
        pmtRequest.city = cInfo.city;
        pmtRequest.state = cInfo.state;
        pmtRequest.zip = cInfo.zip;
    }
}