src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deposit_Date__c</fullName>
        <description>Date of deposit</description>
        <label>Deposit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer of the account</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>

src/classes/PaymentDaoTest.cls
@isTest
private class PaymentDaoTest {
	/**
     * This method is used to test PaymentDao.insertPayment method
     **/
    static testMethod void insertPaymentTest() {
    	// Create Guarantor Contact record.
        Contact guarantorContact = TestUtility.generateGuarantorContact();
        INSERT guarantorContact;

        // Create Encounter record.
        Encounter__c selectedEncounter = TestUtility.generateEncounter(guarantorContact.Id, 500, system.today());
        INSERT selectedEncounter;

        Payment__c payment = new Payment__c(
            Name = 'Test Payment',
            Guarantor__c = guarantorContact.Id,
            Amount__c = 123,
            Encounter__c = selectedEncounter.Id,
            Deposit_Date__c = System.now(),
            Method__c = null
        );

        Test.startTest();
        PaymentDao.insertPayment(payment);
        
        List<Payment__c> paymentList = [
        	SELECT Id, Name 
        	FROM Payment__c
        ];
        // Check that record was created
        System.assertEquals(paymentList.size(), 1);
        Test.stopTest();
    }
}