src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Medical_Record_Number__c</fullName>
        <description>Patient medical Record number</description>
        <label>Medical Record Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profile_Pointer_ID__c</fullName>
        <externalId>true</externalId>
        <label>Guarantor ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/GuarantorService.cls
/**
 * GuarantorService
 */

public with sharing class GuarantorService extends AbstractService {

    //Get the Guarantor's Profile_Pointer_Id__c from the given contact.
    public static String getGuarantorSironoId(Contact contact) {
        String guarantorId = '';
        if (contact == null) {
            throw new SironoServiceException('Invalid request - Contact required to retrieve SironoId');
        }
        if (contact.Profile_Pointer_Id__c != null) {
            return contact.Profile_Pointer_Id__c.toPlainString();
        } else {
            Contact gt = GuarantorDao.getGuarantor(contact.Id);
            if (gt != null) {
                guarantorId = gt.Profile_Pointer_ID__c.toPlainString();
            } else {
                throw new SironoServiceException('Guarantor not found');
            }
        }
        return guarantorId;
    }

    //Cet the Guarantor details string from the given contact.
    public static String buildGuarantorDetailString(Contact gc) {
        String details = '';
        details = gc.FirstName + (gc.MiddleName != null ? ' ' + gc.MiddleName : '')
                + (gc.LastName != null ? ' ' + gc.LastName : '')
                + (gc.Suffix != null ? ' ' + gc.Suffix : '')
                + ' (DOB: ' + (gc.Birthdate != null ? gc.Birthdate.format() : '')
                + ', MRN: ' + (gc.Medical_Record_Number__c != null ? gc.Medical_Record_Number__c : '')
                + ')';

        return details;
    }
}