src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Add_to_Payment_Plan__c</fullName>
        <formula>AND(Payment_Plan_Balance__c &gt; 0, Payment_Plan_Balance__c &lt;&gt; Invoiced_Balance__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Add to Payment Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent_Invoices__c</fullName>
        <description>Count of delinquent invoices</description>
        <label>Delinquent Invoices</label>
        <summaryFilterItems>
            <field>Invoice__c.Invoice_Status_Index__c</field>
            <operation>equals</operation>
            <value>7</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Master Guarantor for External Guarantor record</description>
        <inlineHelpText>Master Guarantor for External Guarantor record</inlineHelpText>
        <label>Guarantor</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Guarantor</relationshipLabel>
        <relationshipName>Assigned_Guarantor</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoiced_Balance__c</fullName>
        <label>Invoiced Balance</label>
        <summarizedField>Charge_Group__c.Balance__c</summarizedField>
        <summaryFilterItems>
            <field>Charge_Group__c.Has_Invoiced_Balance__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Charge_Group__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Outstanding_Invoices__c</fullName>
        <description>Count of outstanding invoices</description>
        <label>Outstanding Invoices</label>
        <summaryFilterItems>
            <field>Invoice__c.Invoice_Status_Index__c</field>
            <operation>greaterOrEqual</operation>
            <value>4</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Overdue_Invoices__c</fullName>
        <description>Count of Overdue invoices</description>
        <label>Overdue Invoices</label>
        <summaryFilterItems>
            <field>Invoice__c.Invoice_Status_Index__c</field>
            <operation>equals</operation>
            <value>6</value>
        </summaryFilterItems>
        <summaryForeignKey>Invoice__c.Guarantor__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <recordTypes>
        <fullName>Guarantor</fullName>
        <active>true</active>
        <description>Guarantor of the account or case</description>
        <label>Guarantor</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Contact.object
    <fields>
        <fullName>Guarantor_Status__c</fullName>
        <formula>IF(RecordType.Name == &apos;Guarantor&apos;,
CASE(Invoice_Status_Rollup2__c,
9, &quot;Delinquent&quot;,
8, &quot;Overdue&quot;,
7, &quot;Due&quot;,
6, &quot;On Payment Plan&quot;,
5, &quot;Paid&quot;,
4, &quot;Paid&quot;,
3, &quot;Paid&quot;,
2, &quot;Unknown&quot;,
1, &quot;Paid&quot;,
0, &quot;Paid&quot;,
&quot;Error&quot;),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Guarantor)</relationshipLabel>
        <relationshipName>Guarantor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Invoice_Status__c</fullName>
        <formula>CASE(Invoice_Status_Index__c,
9, &quot;Delinquent&quot;,
8, &quot;Overdue&quot;,
7, &quot;Due&quot;,
6, &quot;On Payment Plan&quot;,
5, &quot;Paid&quot;,
4, &quot;Paid&quot;,
3, &quot;Paid&quot;,
2, &quot;Unknown&quot;,
1, &quot;Invoice Voided&quot;,
0, &quot;Invoice Voided&quot;,
&quot;Error&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Invoice Status</label>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Installment_Amount__c</fullName>
        <label>Installment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Installments_Completed__c</fullName>
        <formula>Original_Installment_Count__c -  Remaining_Installment_Count__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Installments Completed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NextPaymentDate__c</fullName>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Original_Installment_Count__c</fullName>
        <description>payment installment months</description>
        <label>Original Installments</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Payment_Plan_Standing__c</fullName>
        <description>PPS is the status of the ACTIVE payment plan.

            Options: Past Due, In Error, Good Standing</description>
        <formula>IF(Active__c=FALSE,&quot;&quot;,IF(Delinquent__c = TRUE, &quot;Past Due&quot;, IF(Has_Error__c = TRUE, &quot;In Error&quot;, &quot;Good Standing&quot;)))</formula>
        <label>Payment Plan Standing</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Plan Number type small int</description>
        <label>Plan Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Community_Password__c</fullName>
        <label>Community Password</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Demo_Locked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Demo Locked</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/HiMSS_SummaryWidgetRESTService.cls
/**********************************************************************
 * 
 *
 * @url: /services/apexrest/rest
 * @data:
 *  {
        
    }
*************************************************************************/
@RestResource(urlMapping='/SummaryWidget/*')
global without sharing class HiMSS_SummaryWidgetRESTService {
	public static String DUE_STATUS = 'Due';

    @HttpGet
    global static void getGuarantor() {
    	RestRequest req = RestContext.request;
    	RestResponse res = RestContext.response;
    	if (res == null) {
            res = new RestResponse();
            RestContext.response = res;
        }

    	String firstName = req.params.get('firstName');
    	String lastName = req.params.get('lastName');

    	if (firstName != null && lastName != null) {
    		Guarantor portalGuarantor = HiMSS_SummaryWidgetRESTService.getPortalGuarantor(firstName, lastName);
			if (portalGuarantor != null) {
				res.responseBody = Blob.valueOf(JSON.serialize(portalGuarantor));	
			}
    	}
    }

    public static Guarantor getPortalGuarantor(String firstName, String lastName) {
		Guarantor.GuarantorUser user = HiMSS_SummaryWidgetRESTService.getUser(firstName, lastName);
		if (user != null) {
			Guarantor.GuarantorContact grtContact = HiMSS_SummaryWidgetRESTService.getGrtContact(user.contactId);
			Guarantor.Invoice grtInvoice = HiMSS_SummaryWidgetRESTService.getGuarantorInvoice(user.contactId);
			Guarantor.PaymentPlan grtPaymentPlan = HiMSS_SummaryWidgetRESTService.getGuarantorPaymentPlan(user.contactId);
			Integer newEstimatesCount = HiMSS_SummaryWidgetRESTService.getEstimatesCount(user.contactId);
			return new Guarantor(user, grtContact, grtInvoice, grtPaymentPlan, newEstimatesCount);
		} else {
			return null;
		}
    }

    public static Guarantor.GuarantorUser getUser(String firstName, String lastName) {
    	List<User> usrList = [
    					SELECT 	Id, 
    						   	ContactId,
    						   	UserName,
    						   	Community_Password__c 
    					FROM 	User 
    					WHERE 	FirstName LIKE :firstName.trim() AND
    							LastName  LIKE :lastName.trim() AND
    							Is_Demo_Locked__c = false
    	];
    	return (! usrList.isEmpty()) ? new Guarantor.GuarantorUser(usrList[0].UserName, usrList[0].Community_Password__c,  usrList[0].ContactId) : null;
    }

    public static Guarantor.GuarantorContact getGrtContact(Id contactId) {
    	Contact contact = [
							SELECT 
									Id,
									Guarantor__c,
									Guarantor_Status__c,
									Invoiced_Balance__c,
									Overdue_Invoices__c,
									Outstanding_Invoices__c,
									Delinquent_Invoices__c,
									Add_to_Payment_Plan__c
							FROM 	Contact
							WHERE 	Id = :contactId
		];
		return new Guarantor.GuarantorContact(contact.Guarantor_Status__c, contact.Outstanding_Invoices__c, 
			contact.Overdue_Invoices__c, contact.Delinquent_Invoices__c, contact.Add_to_Payment_Plan__c, contact.Invoiced_Balance__c);
    }

    public static Guarantor.Invoice getGuarantorInvoice(Id contactId) {
    	List<Invoice__c> listInvoices = [
											SELECT
													Id,
													Due_Date__c
											FROM 	Invoice__c
											WHERE 	Guarantor__c = :contactId
												AND Invoice_Status__c = :HiMSS_SummaryWidgetRESTService.DUE_STATUS
											ORDER BY CreatedDate 
											LIMIT 1
		];
		return (! listInvoices.isEmpty()) ? new Guarantor.Invoice(listInvoices[0].Due_Date__c) : null;
    }

    public static Guarantor.PaymentPlan getGuarantorPaymentPlan(Id contactId) {
    	List<Payment_Plan__c> paymentPlans = [
											SELECT
													Id,
													Payment_Plan_Standing__c,
													NextPaymentDate__c,
													Installment_Amount__c,
													Installments_Completed__c,
													Original_Installment_Count__c,
													Active__c,
													Plan_Type__c
											FROM 	Payment_Plan__c
											WHERE	Guarantor__c = :contactId
											ORDER BY Active__c DESC, LastModifiedDate DESC
											LIMIT 1
		];
		return (! paymentPlans.isEmpty()) ? new Guarantor.PaymentPlan(paymentPlans[0].NextPaymentDate__c, paymentPlans[0].Active__c, paymentPlans[0].Payment_Plan_Standing__c, paymentPlans[0].Plan_Type__c) : null;
    }

    public static Integer getEstimatesCount(Id contactId) {
    	Integer newEstimatesCount = [
									SELECT 
											COUNT()
									FROM 	Encounter__c
									WHERE   Guarantor__c = :contactId AND 
											CreatedDate >= :Datetime.now().addDays(-30)
		];
		return newEstimatesCount;
    }
}