src/objects/Encounter__c.object
<CustomObject>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Arrangement__c.object
<CustomObject>
    <fields>
        <fullName>Encounter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Encounter</label>
        <referenceTo>Encounter__c</referenceTo>
        <relationshipLabel>Payment Arrangements</relationshipLabel>
        <relationshipName>Payment_Arrangements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payment Arrangements</relationshipLabel>
        <relationshipName>Payment_Arrangements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Payment Arrangement</label>
    <nameField>
        <displayFormat>pa-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Arrangements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <description>Credit card details</description>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/PaymentArrangementSecurityContext.cls
/**
 * This class is use for Security Context of Payment Arrangement object
 **/

public with sharing class PaymentArrangementSecurityContext extends SecurityContext {

    /*// Field constants for Payment_Arrangement__c object.
    private static final String ENCOUNTER = 'Encounter__c';
    private static final String PAYMENT_METHOD = 'Payment_Method__c';

    // The fields for inserting a Payment Arrangement in PaymentArrangement
    private static final Set<String> CREATE_FIELDS = new Set<String>{
    	ENCOUNTER, PAYMENT_METHOD
    };*/

    /**
     * Constructor of class that assign variables based on parameters
     *
     * @param Set<String> fields - That contains Object's Fields
     * @param ACTION actionToPerform - That contains Action Name (Create/Update/Delete/Undelete)
     **/
    /*private PaymentArrangementSecurityContext(Set<String> fields, ACTION actionToPerform) {
        this.fieldsToCheck = fields;
        this.objectAction = actionToPerform;
    }*/

    /**
     * The create context for Payment_Arrangement__c
     **/
    //public static final PaymentArrangementSecurityContext CREATE_CONTEXT = new PaymentArrangementSecurityContext(CREATE_FIELDS, ACTION.OBJ_CREATE);

    /**
     * Override getObjectType method of SecurityContext class
     **/
    public override System.Type getObjectType() {
        //return Payment_Arrangement__c.class;
        return null;
    }
    
    /**
     * Override deleteActionAllowed method of SecurityContext class
     **/
    public override Boolean deleteActionAllowed() { 	
        //return Payment_Arrangement__c.sObjectType.getDescribe().isDeletable();
        return false;
    }
}