src/objects/Encounter__c.object
<CustomObject>
    <fields>
        <fullName>Balance__c</fullName>
        <formula>IF( Has_Chargegroup__c, 0, Patient_Portion__c - Total_Payments__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cancelled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_of_Service__c</fullName>
        <label>Date of Service</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estimate_ID__c</fullName>
        <label>Estimate ID</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Guarantor)</relationshipLabel>
        <relationshipName>Encounters1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Insurance_Discount__c</fullName>
        <label>Insurance Discount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Insurance_Portion__c</fullName>
        <label>Insurance Portion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Liability__c</fullName>
        <label>Liability</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordering_Physician__c</fullName>
        <label>Ordering Physician</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Patient_Portion__c</fullName>
        <formula>Total_Charges__c - Insurance_Total__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Patient Portion</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Patient__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patient</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Patient</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Encounters (Patient)</relationshipLabel>
        <relationshipName>Encounters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Procedure__c</fullName>
        <label>Procedure</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Charges__c</fullName>
        <label>Total Charges</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Payments__c</fullName>
        <label>Payments</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>HB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Encounter</label>
    <nameField>
        <displayFormat>en-{YYYY}{MM}-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Encounters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

call-center/src/objects/Encounter__c.object
    <fields>
        <fullName>Billed_Charge_Group_Count__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Billed Charge Group Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

src/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EncounterSecurityContext.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * This class is use for Security Context of Encounter__c object
 **/
public with sharing class EncounterSecurityContext extends SecurityContext {
	
    // Field constants for Encounter__c object
    private static final String BILLED_CHARGE_GROUP_COUNT = 'Billed_Charge_Group_Count__c';
    private static final String TOTAL_PAYMENTS = 'Total_Payments__c';

    // Below field(s) are used for Select/Read permission.
    private static final String BALANCE = 'Balance__c';
    private static final String CANCELLED = 'Cancelled__c';
    private static final String DATE_OF_SERVICE = 'Date_of_Service__c';
    private static final String ESTIMATE_ID = 'Estimate_ID__c';
    private static final String GUARANTOR = 'Guarantor__c';
    private static final String ID = 'Id';
    private static final String INSURANCE_DISCOUNT = 'Insurance_Discount__c';
    private static final String INSURANCE_PORTION = 'Insurance_Portion__c';
    private static final String LIABILITY = 'Liability__c';
    private static final String LOCATION = 'Location__c';
    private static final String NAME = 'Name';
    private static final String ORDERING_PHYSICIAN = 'Ordering_Physician__c';
    private static final String PATIENT = 'Patient__c';
    private static final String PATIENT_PORTION = 'Patient_Portion__c';
    private static final String PROCEDURE = 'Procedure__c';
    private static final String TOTAL_CHARGES = 'Total_Charges__c';
    private static final String TYPE = 'Type__c';

    // The fields for updating a Encounter__c's Total_Payments__c field in EncounterUtil.
    private static final Set<String> UPDATE_FIELDS = new Set<String>{
    	TOTAL_PAYMENTS
    };

    // The fields for updating a Encounter__c's Billed_Charge_Group_Count__c field in EncounterUtil.
    private static final Set<String> UPDATE_BILLED_CG_COUNT_FIELDS = new Set<String>{
        BILLED_CHARGE_GROUP_COUNT
    };

    // The fields for selecting a Encounter__c in EncounterDao
    private static final Set<String> SELECT_FIELDS = new Set<String>{
        ID, NAME, PATIENT, DATE_OF_SERVICE, INSURANCE_DISCOUNT, INSURANCE_PORTION, ORDERING_PHYSICIAN, PROCEDURE,
        LOCATION, PATIENT_PORTION, PROCEDURE, GUARANTOR, BALANCE, TOTAL_PAYMENTS, BALANCE, TYPE
    };

    // The fields for selecting a Encounter__c in CallListUtilities
    private static final Set<String> CLU_SELECT_FIELDS = new Set<String>{
        ID, DATE_OF_SERVICE, LIABILITY, CANCELLED
    };

    // The fields for selecting a Encounter__c in EncounterUtil.
    private static final Set<String> EU_SELECT_FIELDS = new Set<String>{
        ID, GUARANTOR
    };

    // The fields for selecting Encounter__c in EncounterUtil.
    private static final Set<String> EU_SELECT_FIELDS_AGG = new Set<String>{
        GUARANTOR, BALANCE
    };

    // The fields for selecting Encounter__c in PreServiceSchedulerBatch
    private static final Set<String> PSS_SELECT_FIELDS = new Set<String>{
        ID, NAME, GUARANTOR, LIABILITY, DATE_OF_SERVICE, CANCELLED
    };

    /**
     * Constructor of class that assign variables based on parameters
     *
     * @param Set<String> fields - That contains Object's Fields
     * @param ACTION actionToPerform - That contains Action Name (Create/Update/Delete/Undelete)
     **/
    private EncounterSecurityContext(Set<String> fields, ACTION actionToPerform) {
        this.fieldsToCheck = fields;
        this.objectAction = actionToPerform;
    }
    
    /**
     * The update context for Encounter__c's Total_Payments__c field in EncounterUtil
     **/
    public static final EncounterSecurityContext UPDATE_CONTEXT = new EncounterSecurityContext(UPDATE_FIELDS, ACTION.OBJ_UPDATE);

    /**
     * The update context for Encounter__c's Billed_Charge_Group_Count__c field in EncounterUtil
     **/
    public static final EncounterSecurityContext UPDATE_BILLED_CG_COUNT_CONTEXT = new EncounterSecurityContext(UPDATE_BILLED_CG_COUNT_FIELDS, ACTION.OBJ_UPDATE);

    /**
     * The select context for Encounter__c in EncounterDao
     **/
    public static final EncounterSecurityContext SELECT_CONTEXT = new EncounterSecurityContext(SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * The select context for Encounter__c in CallListUtilities
     **/
    public static final EncounterSecurityContext CLU_SELECT_CONTEXT = new EncounterSecurityContext(CLU_SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * The select context for Encounter__c in EncounterUtil
     **/
    public static final EncounterSecurityContext EU_SELECT_CONTEXT = new EncounterSecurityContext(EU_SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * The select context for Encounter__c in EncounterUtil
     **/
    public static final EncounterSecurityContext EU_SELECT_CONTEXT_AGG = new EncounterSecurityContext(EU_SELECT_FIELDS_AGG, ACTION.OBJ_READ);

    /**
     * The select context for Encounter__c in PreServiceSchedulerBatch
     **/
    public static final EncounterSecurityContext PSS_SELECT_CONTEXT = new EncounterSecurityContext(PSS_SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * Override getObjectType method of SecurityContext class
     **/
    public override System.Type getObjectType() {
        return Encounter__c.class;
    }
}