src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for a set of Charge Groups for a Guarantor / Patient combination</description>
    <fields>
        <fullName>All_Substatus__c</fullName>
        <label>All Substatus</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Due Date</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <description>Guarantor</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Invoices (Guarantor)</relationshipLabel>
        <relationshipName>Guarantor</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Partial_Payment_Plan__c</fullName>
        <formula>And(Invoice_Status_Index__c &lt;&gt; 4,CONTAINS(All_Substatus__c,&quot;Payment&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partial Payment Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sirono_ID__c</fullName>
        <description>Invoice ID External</description>
        <externalId>true</externalId>
        <label>Invoice ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Invoice</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

call-center/src/objects/Invoice__c.object
    <fields>
        <fullName>Age__c</fullName>
        <formula>TODAY() - Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

call-center/src/objects/Invoice__c.object
    <fields>
        <fullName>Balance__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>

call-center/src/objects/Invoice__c.object
    <fields>
        <fullName>Date__c</fullName>
        <description>Date</description>
        <label>Date</label>
        <type>Date</type>
    </fields>

call-center/src/objects/Invoice__c.object
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(AND(Balance__c &lt;&gt; NULL, Balance__c ==0), &quot;Paid&quot;,
CASE(Status_Index__c,
9, &quot;Delinquent&quot;,
8, &quot;Overdue&quot;,
7, &quot;Due&quot;,
6, &quot;On Payment Plan&quot;,
5, &quot;Credit&quot;,
4, &quot;Paid&quot;,
3, &quot;Paid&quot;,
2, &quot;Unknown&quot;,
1, &quot;Invoice Voided&quot;,
0, &quot;Invoice Voided&quot;,
&quot;Error&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>

call-center/src/objects/Invoice__c.object
    <fields>
        <fullName>Status_Index__c</fullName>
        <label>Status Index</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>

src/classes/InvoiceSecurityContext.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * This class is use for Security Context of Invoice__c object.
 **/
public with sharing class InvoiceSecurityContext extends SecurityContext {

    // Field constants for Invoice__c object
    private static final String ALL_SUBSTATUS = 'All_Substatus__c';
    private static final String BALANCE = 'Balance__c';
    private static final String STATUS_INDEX = 'Status_Index__c';

    // Below field(s) are use for Select/Read permission.
    private static final String DUE_DATE = 'Due_Date__c';
    private static final String GUARANTOR = 'Guarantor__c';
    private static final String ID = 'Id';
    private static final String AGE = 'Age__c';
    private static final String INVOICE_DATE = 'Date__c';
    private static final String NAME = 'Name';
    private static final String PARTIAL_PAYMENT_PLAN = 'Partial_Payment_Plan__c';
    private static final String SIRONO_ID = 'Sirono_Id__c';
    private static final String STATUS = 'Status__c';

    // The fields for updating a Invoice__c's Status_Index__c field in InvoiceUtil
    private static final Set<String> UPDATE_FIELDS = new Set<String> {
            STATUS_INDEX
    };

    // The fields for updating a Invoice__c's All_Substatus__c field in InvoiceUtil
    private static final Set<String> UPDATE_ALL_SUBSTATUS_FIELDS = new Set<String> {
        ALL_SUBSTATUS
    };

    // The fields for updating a Invoice__c's Balance__c field in InvoiceUtil
    private static final Set<String> UPDATE_BALANCE_FIELDS = new Set<String> {
            BALANCE
    };

    // The fields for selecting a Invoice__c in EarlyOutSchedulerBatch
    private static final Set<String> SELECT_FIELDS = new Set<String> {
        ID, NAME, GUARANTOR, INVOICE_DATE, DUE_DATE, STATUS
    };

    // The fields for selecting the details on Invoices
    private static final Set<String> DETAIL_FIELDS = new Set<String> {
        ID, NAME, BALANCE, SIRONO_ID, INVOICE_DATE, AGE, STATUS, DUE_DATE, PARTIAL_PAYMENT_PLAN
    };

    /**
     * Constructor of class that assign variables based on parameters
     *
     * @param Set<String> fields - That contains Object's Fields
     * @param ACTION actionToPerform - That contains Action Name (Create/Update/Delete/Undelete)
     **/
    private InvoiceSecurityContext(Set<String> fields, ACTION actionToPerform) {
        this.fieldsToCheck = fields;
        this.objectAction = actionToPerform;
    }
    
    /**
     * The update context for Invoice__c's Status_Index__c field in InvoiceUtil
     **/
    public static final InvoiceSecurityContext UPDATE_CONTEXT = new InvoiceSecurityContext(UPDATE_FIELDS, ACTION.OBJ_UPDATE);

    public static final InvoiceSecurityContext DETAIL_CONTEXT = new InvoiceSecurityContext(DETAIL_FIELDS, ACTION.OBJ_READ);
    /**
     * The update context for Invoice__c's All_Substatus__c field in InvoiceUtil
     **/
    public static final InvoiceSecurityContext UPDATE_ALL_SUBSTATUS_CONTEXT = new InvoiceSecurityContext(UPDATE_ALL_SUBSTATUS_FIELDS, ACTION.OBJ_UPDATE);

    /**
     * The update context for Invoice__c's Balance__c field in InvoiceUtil
     **/
    public static final InvoiceSecurityContext UPDATE_BALANCE_CONTEXT = new InvoiceSecurityContext(UPDATE_BALANCE_FIELDS, ACTION.OBJ_UPDATE);

    /**
     * The select context for Invoice__c in EarlyOutSchedulerBatch
     **/
    public static final InvoiceSecurityContext SELECT_CONTEXT = new InvoiceSecurityContext(SELECT_FIELDS, ACTION.OBJ_READ);

    /**
     * Override getObjectType method of SecurityContext class
     **/
    public override System.Type getObjectType() {
        return Invoice__c.class;
    }
}