src/objects/Payment_Plan__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Execute_on_Day__c</fullName>
        <label>Execute on Day</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>NextPaymentDate__c</fullName>
        <label>Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>Plan Number type small int</description>
        <label>Plan Type</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skip_Payment_Until__c</fullName>
        <description>Defines making payment until date</description>
        <label>Skip Payment Until</label>
        <type>Date</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PopulateNextPaymentDateBatch.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

public with sharing class PopulateNextPaymentDateBatch implements Database.Batchable<SObject>, Schedulable, Database.Stateful {

    public void execute(SchedulableContext sc) {
        Database.executeBatch(new PopulateNextPaymentDateBatch(), 1000);
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        if (PaymentPlanSecurityContext.CTH_SELECT_CONTEXT.actionAllowed()) {
            return Database.getQueryLocator([
                SELECT
                    Id, Guarantor__c, Plan_Type__c,
                    Execute_on_Day__c, NextPaymentDate__c,
                    Skip_Payment_Until__c
                FROM Payment_Plan__c
                WHERE Guarantor__c != NULL
            ]);
        }
        return null;
    }

    //pass the payment plan list to the method.
    public void execute(Database.BatchableContext bc, List<SObject> scope) {
        PaymentPlanTriggerHandler.populateNextPaymentDate((List<Payment_Plan__c>) scope, false);
    }

    public void finish(Database.BatchableContext bc) {

    }
}