src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deposit_Date__c</fullName>
        <description>Date of deposit</description>
        <label>Deposit Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mastercard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor_Transaction_ID__c</fullName>
        <description>Id of the processor</description>
        <label>Processor Transaction ID</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment__c.object
    <fields>
        <fullName>Payment_Id__c</fullName>
        <displayFormat>{0000}</displayFormat>
        <label>Payment Id</label>
        <type>AutoNumber</type>
    </fields>

src/objects/Payment_Method__c.object
<CustomObject>
    <description>Credit card details</description>
    <fields>
        <fullName>Card_Type__c</fullName>
        <description>Type of Credit card used</description>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

portal/src/classes/WorkWithPaymentsController.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

public with sharing class WorkWithPaymentsController {

    /**
     * Get the list of PaymentWrapper objects for the current user.
     *
     * @return List<PaymentWrapper> - The wrapped payments for the current user.
     */
    @AuraEnabled
    public static List<PaymentsWrapper> getPaymentHistory() {
        UserWrapper userWrapper = UserService.getCurrentUser();


        List<Payment__c> payments = PaymentService.getPayments(userWrapper.contactId);
        List<PaymentsWrapper> wrappers = new List<PaymentsWrapper>();
        for (Payment__c payment: payments) {
            wrappers.add(new PaymentsWrapper(payment));
        }
        return wrappers;
    }

    public class PaymentsWrapper {
        @AuraEnabled public String name { get; set; }
        @AuraEnabled public String method { get; set; }
        @AuraEnabled public String deposit { get; set; }
        @AuraEnabled public Decimal amount { get; set; }
        @AuraEnabled public String paymentId { get; set; }
        @AuraEnabled public String description { get; set; }

        public PaymentsWrapper(Payment__c payment) {
            this.paymentId = payment.Payment_Id__c;
            this.name = payment.Name;
            this.deposit = payment.Deposit_Date__c != null ? payment.Deposit_Date__c.date().format() : '';
            this.method = payment.Method__c;
            this.description = '';
            this.amount = payment.Amount__c;
            if (payment.Method__c == 'credit' || payment.Method__c == 'Credit') {
                this.description += payment.Payment_Method__r.Card_Type__c + ' ' + payment.Payment_Method__r.Last_4__c;
            } else if (payment.Method__c == 'check' || payment.Method__c == 'Check') {
                this.description += payment.Processor_Transaction_Id__c;
            }
            this.description = this.description.replaceAll('null', '');
        }
    }
}