src/objects/Payment__c.object
<CustomObject>
    <description>Details of a Guarantor payment made within the Sirono system</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Charge_Date__c</fullName>
        <description>Date of transaction</description>
        <label>Charge Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Customer of the account</description>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Method</label>
        <referenceTo>Payment_Method__c</referenceTo>
        <relationshipLabel>Payments</relationshipLabel>
        <relationshipName>Payments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Processor_Transaction_ID__c</fullName>
        <description>Id of the processor</description>
        <label>Processor Transaction ID</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Payment_Method__c.object
<CustomObject>
    <description>Credit card details</description>
    <fields>
        <fullName>Guarantor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Credit_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WorkWithPaymentsController.cls
//TODO remove without sharing
public without sharing class WorkWithPaymentsController {
	public static final Integer SWAP_TRUE 	= 1;
	public static final Integer SWAP_FALSE 	= 2;
	public static final Integer SWAP_EQUALS = 0;

    public static final String QUERY            = 'SELECT Id, Charge_Date__c, Payment_Method__r.Last_4__c, Processor_Transaction_Id__c, Amount__c FROM Payment__c';
    public static final String ORDER_BY         = ' ORDER BY ';
    public static final String DEFAULT_ORDER    = 'Charge_Date__c DESC';
    public static final String LIMIT_SUFFIX     = ' LIMIT 50000';


    @AuraEnabled
    public static List<Payment__c> getPaymentHistory(String criteria, String orderType) {
        if(String.isBlank(criteria)) {
            criteria = DEFAULT_ORDER;
        } else {
        	criteria += orderType.center(orderType.length() + 2);
        }
		List<Payment__c> result;
		User currentUser = [SELECT Id, ContactId FROM User WHERE Id = :userInfo.getUserId()];
        String whereQuery = ' WHERE  Guarantor__c =\'' + currentUser.ContactId + '\'';

        String finalQuery = QUERY + whereQuery + ORDER_BY + criteria + LIMIT_SUFFIX; 
        result = Database.query(finalQuery);
        if(criteria == DEFAULT_ORDER) {
        	sortList(result);
        }
        return result;
    }

	//Items should be also sort by Amount (not only by date)
	private static void sortList(List<Payment__c> paymentList) {
		for(Integer i = 0; i < paymentList.size(); i++) {
			for(Integer j = paymentList.size() - 1; j > i; j--) {
				if(swapValues(paymentList.get(j), paymentList.get(j - 1))) {
					Payment__c temp = paymentList.get(j);
					paymentList[j] = paymentList[j - 1];
					paymentList[j - 1] = temp;
				}
			}
		}
	}

	//DESC
	private static Boolean swapValues(Payment__c first, Payment__c second) {
		Integer compareDate = compareDateTime(first.Charge_Date__c, second.Charge_Date__c);
		if(compareDate == SWAP_EQUALS) {
			return compareAmount(first.Amount__c, second.Amount__c);
		}
		if(compareDate == SWAP_TRUE) {
			return true;
		}
		return false;
	}
	//DESC    1 - true; 2 - false; 0 - equals
	private static Integer compareDateTime(Datetime first, Datetime second) {
		if(first == null && second != null) {
			return SWAP_TRUE;
		}
		if(first != null && second == null) {
			return SWAP_FALSE;
		}
		if(first == null && second == null) {
			return SWAP_EQUALS;
		}
		//accurate to minutes
		//Long dt1Long = first.getTime();
		//Long dt2Long = second.getTime();
		//Long milliseconds = dt2Long - dt1Long;
		//Long seconds = milliseconds / 1000;
		//Long minutes = seconds / 60;
		//Long hours = minutes / 60;
		//if(minutes == 0) {
		//	return SWAP_EQUALS;
		//}
		//if(minutes < 0) {
		//	return SWAP_TRUE;
		//}
		//return SWAP_FALSE;

		if(first.date() == second.date()) {
			return SWAP_EQUALS;
		}
		if(first.date() < second.date()) {
			return SWAP_TRUE;
		}
		return SWAP_FALSE;


	}
	//DESC
	private static Boolean compareAmount(Decimal second, Decimal first) {
		
		if(first == null) {
			return true;
		}
		if(second == null) {
			return false;
		}
		return first < second;
	}
}