src/objects/Payment_Method__c.object
<CustomObject>
    <description>Credit card details</description>
    <fields>
        <fullName>Card_Holder_Name__c</fullName>
        <description>Name of the card Holder</description>
        <label>Card Holder Name</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <description>Type of Credit card used</description>
        <label>Card Type</label>
        <picklist>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MasterCard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discover</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Express</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expiration_Date__c</fullName>
        <description>MM/YY (i.e. 02/16)</description>
        <label>Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_4__c</fullName>
        <label>Last 4</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Payment Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

call-center/src/objects/Payment_Method__c.object
    <fields>
        <fullName>Display_Name__c</fullName>
        <formula>TEXT(Type__c) &amp;
CASE(Type__c,
&quot;Credit Card&quot;,  &quot; &quot; &amp; TEXT(Card_Type__c) &amp; &quot;-&quot; &amp;  Last_4__c,
&quot;ACH&quot;, &quot; &quot; &amp; TEXT(Account_Number__c),
&quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Display Name</label>
        <type>Text</type>
    </fields>

src/classes/CardInformation.cls
/*
 * Copyright (c) 2017-present Sirono LLC, All rights reserved
 */

/**
 * Data associated with a credit card.
 */
public with sharing class CardInformation {
    @AuraEnabled
    public String sfId {get; set;}
    @AuraEnabled
    public String displayName {get; set;}
    @AuraEnabled
    public String cardType {get; set;}
    @AuraEnabled
    public Boolean isSaved {get; set;}
    @AuraEnabled
    public String password { get; set; }
    @AuraEnabled
    public string creditCardNumber { get; set; }
    @AuraEnabled
    public string cardHolderName { get; set; }
    @AuraEnabled
    public string expirationDate{get;set;}
    @AuraEnabled
    public string expirationYear { get; set; }
    @AuraEnabled
    public string expirationMonth { get; set; }
    @AuraEnabled
    public string cvv { get; set; }
    @AuraEnabled
    public string amount { get; set; }
    @AuraEnabled
    public string address { get; set; }
    @AuraEnabled
    public string city { get; set; }
    @AuraEnabled
    public string state { get; set; }
    @AuraEnabled
    public string zip { get; set; }

    public CardInformation() {
        this.sfId = '';
        this.displayName = '';
        this.cardType = '';
        this.isSaved = false;

        this.password = '';
        this.creditCardNumber = '';
        this.cardHolderName = '';
        this.expirationDate = '';
        this.expirationYear = String.valueOf(Datetime.now().year());
        this.expirationMonth = String.valueOf(Datetime.now().month()).length() == 1 ? '0'+ String.valueOf(Datetime.now().month()) :  String.valueOf(Datetime.now().month());
        this.cvv = '';
        this.amount = '0';
        this.address = '';
        this.city = '';
        this.state = '';
        this.zip = '';
    }

    public CardInformation(Payment_Method__c card) {
        this.sfId = card.Id;
        this.cardHolderName = card.Card_Holder_Name__c;
        this.cardType = card.Card_Type__c;
        this.displayName = card.Display_Name__c;
        this.creditCardNumber = '****-****-****-' + card.Last_4__c;
        this.isSaved = true;

        if (card.Expiration_Date__c != null) {
            Integer monthKey = card.Expiration_Date__c.month();
            Integer yearKey = card.Expiration_Date__c.year();
            this.expirationMonth = monthKey > 10 ? String.valueOf(monthKey) : '0' + String.valueOf(monthKey);
            this.expirationYear = String.valueOf(yearKey);
        }
    }
}