src/objects/Sirono_Call_Center_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Configuration for Sirono Call Center application.</description>
    <fields>
        <fullName>Auto_Create_Overdue_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for statements with overdue balances.</description>
        <inlineHelpText>When enabled, cases are automatically created for statements with overdue balances.</inlineHelpText>
        <label>Auto Create Overdue Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Create_Payment_Plan_Error_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for payment plans with errors.</description>
        <inlineHelpText>When enabled, cases are automatically created for payment plans with errors.</inlineHelpText>
        <label>Auto Create Payment Plan Error Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Auto_Create_Precollection_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When enabled, cases are automatically created for statements with delinquent balances.</description>
        <inlineHelpText>When enabled, cases are automatically created for statements with delinquent balances.</inlineHelpText>
        <label>Auto Create Precollection Cases</label>
        <type>Checkbox</type>
    </fields>
    <label>Sirono Call Center Settings</label>
</CustomObject>

src/classes/SironoCallCenterSettingsUtil.cls
/**
 * Created by swells on 7/20/2017.
 */

public with sharing class SironoCallCenterSettingsUtil {

    public static Sirono_Call_Center_Settings__c getSironoCallCenterSettings() {
        Sirono_Call_Center_Settings__c sironoCallCenterSettings = Sirono_Call_Center_Settings__c.getOrgDefaults();
        if (Test.isRunningTest()) {
            sironoCallCenterSettings.Auto_Create_Overdue_Cases__c = true;
            sironoCallCenterSettings.Auto_Create_Precollection_Cases__c = true;
            sironoCallCenterSettings.Auto_Create_Payment_Plan_Error_Cases__c = true;
        }
        return sironoCallCenterSettings;
    }
}