src/objects/test__c.object
<CustomObject>
    <description>Guarantor Payment Plan details</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Activates plan</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Delinquent_Date__c</fullName>
        <description>Date of deliquency</description>
        <label>Delinquent Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor_Name__c</fullName>
        <label>Guarantor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Guarantor</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Payment Plans</relationshipLabel>
        <relationshipName>Payment_Plans</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Plan</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PaymentPlanTriggerHandler.cls
public with sharing class PaymentPlanTriggerHandler {
	public static void afterInsert(List<test__c> newList){
		checkCallListRemove(newList, null);
	}
	
	public static void afterUpdate(List<test__c> newList, Map<Id, test__c> oldMap){
		checkCallListRemove(newList, oldMap);
	}
	
	private static void checkCallListRemove(List<test__c> newList, Map<Id, test__c> oldMap){
		Set<Id> contactIds = new Set<Id>();
		for(test__c pp : newList){
			if(!pp.Active__c && pp.Delinquent_Date__c == null && pp.Guarantor_Name__c != null &&
			(oldMap == null || pp.Delinquent_Date__c != oldMap.get(pp.Id).Delinquent_Date__c
				|| pp.Active__c != oldMap.get(pp.Id).Active__c
				|| pp.Guarantor_Name__c != oldMap.get(pp.Id).Guarantor_Name__c)){
				contactIds.add(pp.Guarantor_Name__c);	
			}
		}
		
		if(contactIds.size() > 0){
			CallListUtilities.DelinquentPaymentPlanCallListRemoval(contactIds);
		}
	}
}